alter table ARC_SAP alter column NUM_LOTE bigint;

ALTER TABLE AS_ITM_STR ADD PROVEEDOR VARCHAR(18);
ALTER TABLE AS_ITM_STR ADD DEDUCIBLE VARCHAR(3);
ALTER TABLE AS_ITM_STR ADD COLOR VARCHAR(10);
ALTER TABLE AS_ITM_STR ADD MEDIDA VARCHAR(4);
ALTER TABLE AS_ITM_STR ADD DISENO VARCHAR(4);
ALTER TABLE AS_ITM_STR ADD MARCA VARCHAR(15);
ALTER TABLE AS_ITM_STR ADD PRESENTACION VARCHAR(10);