--------------------------------------------------------
--  DDL for Sequence SQ_ID_ARTS
--------------------------------------------------------

   CREATE SEQUENCE  "DEVS_EC"."SQ_ID_ARTS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 702 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ID_DEVS
--------------------------------------------------------

   CREATE SEQUENCE  "DEVS_EC"."SQ_ID_DEVS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 582 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DV_ARTS
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_ARTS" 
   (	"ID_ART" NUMBER(38,0), 
	"ID_DEVS" NUMBER(38,0), 
	"ID_ITM" NUMBER(38,0), 
	"QN_DEV" NUMBER(38,0), 
	"MO_DEV" NUMBER(38,0), 
	"AI_LN_ITM" NUMBER(38,0) DEFAULT 0, 
	"TAX_DEV" NUMBER, 
	"TY_TAX" VARCHAR2(4 BYTE), 
	"TY_REGITM" VARCHAR2(2 BYTE), 
	"QN_TRN" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DEVS_EC"."DV_ARTS"."ID_ART" IS 'IDENTIFICADOR ARTICULO EN DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_ARTS"."ID_DEVS" IS 'IDENTIFICADOR TICKET EN DV_TICKET';
   COMMENT ON COLUMN "DEVS_EC"."DV_ARTS"."ID_ITM" IS 'IDENTIFICADOR ARTICULO EN ARTS';
   COMMENT ON COLUMN "DEVS_EC"."DV_ARTS"."QN_DEV" IS 'CANTIDAD EN DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_ARTS"."MO_DEV" IS 'MONTO EN DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_ARTS"."AI_LN_ITM" IS 'LINEA DE ITEM EN TRX, 0 AGRUPA ITEMS';
   COMMENT ON COLUMN "DEVS_EC"."DV_ARTS"."TY_REGITM" IS 'P=PESABLE, U=UNITARIO, A=ALTERADO';
   COMMENT ON COLUMN "DEVS_EC"."DV_ARTS"."QN_TRN" IS 'CANTIDAD ITEM EN TRX';
--------------------------------------------------------
--  DDL for Table DV_DEVCLTE
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_DEVCLTE" 
   (	"ID_DEVS" NUMBER(38,0), 
	"ID_CPR" NUMBER(38,0), 
	"TY_CPR" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DEVS_EC"."DV_DEVCLTE"."TY_CPR" IS 'C=CEDULA
R=RUC
P=PASAPORTE';
--------------------------------------------------------
--  DDL for Table DV_EFEC
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_EFEC" 
   (	"ID_DEVS" NUMBER(38,0), 
	"ID_WS" NUMBER(38,0) DEFAULT 0, 
	"ID_TRN" NUMBER(38,0) DEFAULT 0, 
	"MONTO" NUMBER(38,0) DEFAULT 0, 
	"ESTADO" NUMBER(2,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DEVS_EC"."DV_EFEC"."ID_DEVS" IS 'IDENTIFICADOR DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_EFEC"."ID_WS" IS 'TERMINAL POS';
   COMMENT ON COLUMN "DEVS_EC"."DV_EFEC"."ID_TRN" IS 'TRANSACCION DE PAGO';
   COMMENT ON COLUMN "DEVS_EC"."DV_EFEC"."MONTO" IS 'MONTO DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_EFEC"."ESTADO" IS '0=POR CONFIRMAR, 1=REGISTRADO, 2=EN COBRO POS, 3=PAGADO';
--------------------------------------------------------
--  DDL for Table DV_FACT
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_FACT" 
   (	"ID_DEVS" NUMBER(38,0), 
	"ID_WS" NUMBER(38,0), 
	"ID_TRN" NUMBER(38,0) DEFAULT 0, 
	"MONTO" NUMBER(38,0) DEFAULT 0, 
	"ESTADO" NUMBER(2,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DEVS_EC"."DV_FACT"."ID_DEVS" IS 'IDENTIFICADOR DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_FACT"."ID_WS" IS 'TERMINAL POS';
   COMMENT ON COLUMN "DEVS_EC"."DV_FACT"."ID_TRN" IS 'TRANSACCION DE CAMBIO';
   COMMENT ON COLUMN "DEVS_EC"."DV_FACT"."MONTO" IS 'MONTO DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_FACT"."ESTADO" IS '0=POR CONFIRMAR, 1=REGISTRADO, 2=EN ESPERA POS, 3=PAGADO';
--------------------------------------------------------
--  DDL for Table DV_GFCD
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_GFCD" 
   (	"ID_DEVS" NUMBER(38,0), 
	"NUM_GFCD" VARCHAR2(255 BYTE), 
	"MONTO" NUMBER(38,0) DEFAULT 0, 
	"ESTADO" NUMBER(2,0) DEFAULT 0, 
	"ARCHIVO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DEVS_EC"."DV_GFCD"."ID_DEVS" IS 'IDENTIFICADOR DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_GFCD"."NUM_GFCD" IS 'TRACK TARJETA GIFTCARD';
   COMMENT ON COLUMN "DEVS_EC"."DV_GFCD"."MONTO" IS 'MONTO GIFTCARD';
   COMMENT ON COLUMN "DEVS_EC"."DV_GFCD"."ESTADO" IS '0=EN CONSULTA, 1=AUTORIZADA, 2=RECHAZADA, 3=VUELVA A INTENTAR';
   COMMENT ON COLUMN "DEVS_EC"."DV_GFCD"."ARCHIVO" IS 'NOMBRE DE ARCHIVO GENERADO PARA CONSULTA';
--------------------------------------------------------
--  DDL for Table DV_LABS
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_LABS" 
   (	"ID_DEVS" NUMBER(38,0), 
	"ID_WS" NUMBER(38,0) DEFAULT 0, 
	"ID_TRN" NUMBER(38,0) DEFAULT 0, 
	"MONTO" NUMBER(38,0) DEFAULT 0, 
	"ESTADO" NUMBER(2,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DV_MDPTCK
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_MDPTCK" 
   (	"ID_DEVS" NUMBER(38,0), 
	"TY_TND" VARCHAR2(4 BYTE), 
	"MONTO" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DV_STATUS
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_STATUS" 
   (	"ID_ESTADO" NUMBER, 
	"NM_ESTADO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DEVS_EC"."DV_STATUS"."ID_ESTADO" IS 'IDENTIFICADOR';
   COMMENT ON COLUMN "DEVS_EC"."DV_STATUS"."NM_ESTADO" IS 'NOMBRE ESTADO';
--------------------------------------------------------
--  DDL for Table DV_TICKET
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_TICKET" 
   (	"ID_DEVS" NUMBER(38,0), 
	"ID_TRN" NUMBER(38,0), 
	"ID_TIPOD" NUMBER, 
	"ID_ESTADO" NUMBER DEFAULT 0, 
	"FECHA_REG" DATE DEFAULT SYSDATE, 
	"FECHA_ACT" DATE DEFAULT SYSDATE, 
	"IDREG" NUMBER, 
	"ID_BSN_UN" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DEVS_EC"."DV_TICKET"."ID_DEVS" IS 'IDENTIFICADOR';
   COMMENT ON COLUMN "DEVS_EC"."DV_TICKET"."ID_TRN" IS 'ID TRX ARTS';
   COMMENT ON COLUMN "DEVS_EC"."DV_TICKET"."ID_TIPOD" IS 'TIPO DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_TICKET"."ID_ESTADO" IS 'ESTADO DEVOLUCION';
   COMMENT ON COLUMN "DEVS_EC"."DV_TICKET"."FECHA_REG" IS 'FECHA DE REGISTRO';
   COMMENT ON COLUMN "DEVS_EC"."DV_TICKET"."FECHA_ACT" IS 'FECHA DE ACTUALIZACION';
   COMMENT ON COLUMN "DEVS_EC"."DV_TICKET"."IDREG" IS 'USUARIO QUE REGISTRA';
   COMMENT ON COLUMN "DEVS_EC"."DV_TICKET"."ID_BSN_UN" IS 'ID TIENDA ARTS';
--------------------------------------------------------
--  DDL for Table DV_TIPOD
--------------------------------------------------------

  CREATE TABLE "DEVS_EC"."DV_TIPOD" 
   (	"ID_TIPOD" NUMBER, 
	"NM_TIPOD" VARCHAR2(50 BYTE), 
	"AC_TIPOD" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DEVS_EC"."DV_TIPOD"."ID_TIPOD" IS 'IDENTIFICADOR';
   COMMENT ON COLUMN "DEVS_EC"."DV_TIPOD"."NM_TIPOD" IS 'NOMBRE DEL TIPO';
   COMMENT ON COLUMN "DEVS_EC"."DV_TIPOD"."AC_TIPOD" IS 'ACTIVACION DEL TIPO, 1:SI, 0:NO';


REM INSERTING into DEVS_EC.DV_STATUS
SET DEFINE OFF;
Insert into DEVS_EC.DV_STATUS (ID_ESTADO,NM_ESTADO) values ('2','REGISTRADA');
Insert into DEVS_EC.DV_STATUS (ID_ESTADO,NM_ESTADO) values ('3','IMPRESA');
Insert into DEVS_EC.DV_STATUS (ID_ESTADO,NM_ESTADO) values ('4','TRX. SUSPENDIDA');
Insert into DEVS_EC.DV_STATUS (ID_ESTADO,NM_ESTADO) values ('6','EJECUTADA');
Insert into DEVS_EC.DV_STATUS (ID_ESTADO,NM_ESTADO) values ('5','EN COBRO');
Insert into DEVS_EC.DV_STATUS (ID_ESTADO,NM_ESTADO) values ('0','TEMP');
Insert into DEVS_EC.DV_STATUS (ID_ESTADO,NM_ESTADO) values ('1','POR CONFIRMAR');

REM INSERTING into DEVS_EC.DV_TIPOD
SET DEFINE OFF;
Insert into DEVS_EC.DV_TIPOD (ID_TIPOD,NM_TIPOD,AC_TIPOD) values ('99','Laboratorio','99');
Insert into DEVS_EC.DV_TIPOD (ID_TIPOD,NM_TIPOD,AC_TIPOD) values ('1','Giftcard','1');
Insert into DEVS_EC.DV_TIPOD (ID_TIPOD,NM_TIPOD,AC_TIPOD) values ('2','Efectivo','1');
Insert into DEVS_EC.DV_TIPOD (ID_TIPOD,NM_TIPOD,AC_TIPOD) values ('3','Cambio Cliente Factura','1');
--------------------------------------------------------
--  DDL for Index DV_ARTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVS_EC"."DV_ARTS_PK" ON "DEVS_EC"."DV_ARTS" ("ID_ART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DV_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVS_EC"."DV_STATUS_PK" ON "DEVS_EC"."DV_STATUS" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DV_TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVS_EC"."DV_TICKET_PK" ON "DEVS_EC"."DV_TICKET" ("ID_DEVS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DV_TIPOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEVS_EC"."DV_TIPOD_PK" ON "DEVS_EC"."DV_TIPOD" ("ID_TIPOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DV_ARTS
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_ARTS" MODIFY ("ID_ART" NOT NULL ENABLE);
  ALTER TABLE "DEVS_EC"."DV_ARTS" ADD CONSTRAINT "DV_ARTS_PK" PRIMARY KEY ("ID_ART")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DV_DEVCLTE
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_DEVCLTE" MODIFY ("ID_DEVS" NOT NULL ENABLE);
  ALTER TABLE "DEVS_EC"."DV_DEVCLTE" MODIFY ("ID_CPR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DV_EFEC
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_EFEC" MODIFY ("ID_DEVS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DV_FACT
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_FACT" MODIFY ("ID_DEVS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DV_GFCD
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_GFCD" MODIFY ("ID_DEVS" NOT NULL ENABLE);
  ALTER TABLE "DEVS_EC"."DV_GFCD" MODIFY ("MONTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DV_LABS
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_LABS" MODIFY ("ID_DEVS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DV_STATUS
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_STATUS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DEVS_EC"."DV_STATUS" ADD CONSTRAINT "DV_STATUS_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DV_TICKET
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_TICKET" MODIFY ("ID_DEVS" NOT NULL ENABLE);
  ALTER TABLE "DEVS_EC"."DV_TICKET" ADD CONSTRAINT "DV_TICKET_PK" PRIMARY KEY ("ID_DEVS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DV_TIPOD
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_TIPOD" MODIFY ("ID_TIPOD" NOT NULL ENABLE);
  ALTER TABLE "DEVS_EC"."DV_TIPOD" ADD CONSTRAINT "DV_TIPOD_PK" PRIMARY KEY ("ID_TIPOD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DV_ARTS
--------------------------------------------------------

  ALTER TABLE "DEVS_EC"."DV_ARTS" ADD CONSTRAINT "DV_ARTS_FK1" FOREIGN KEY ("ID_DEVS")
	  REFERENCES "DEVS_EC"."DV_TICKET" ("ID_DEVS") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_DV_ARTS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DEVS_EC"."TR_DV_ARTS" 
  before insert on DEVS_EC.DV_ARTS
  for each row
declare

begin
    SELECT SQ_ID_ARTS.NEXTVAL
      INTO :NEW.ID_ART
      FROM DUAL;
  
end TR_DV_ARTS;
/
ALTER TRIGGER "DEVS_EC"."TR_DV_ARTS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_DV_TICKET
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DEVS_EC"."TR_DV_TICKET" 
  before insert on DEVS_EC.DV_TICKET
  for each row
declare

begin
    SELECT SQ_ID_DEVS.NEXTVAL
      INTO :NEW.ID_DEVS
      FROM DUAL;
  
end TR_DV_TICKET;
/
ALTER TRIGGER "DEVS_EC"."TR_DV_TICKET" ENABLE;
