--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "EYES_EC"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 117121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table FE_MESSAGE
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FE_MESSAGE" 
   (	"ID_MESSAGE" NUMBER, 
	"EVENT_DATE" DATE, 
	"CHANNEL" VARCHAR2(1 BYTE), 
	"PM_SOURCE" VARCHAR2(18 BYTE), 
	"MESSAGE_GROUP" VARCHAR2(1 BYTE), 
	"MESSAGE_NUMBER" NUMBER(*,0), 
	"SOURCE_NUMBER" VARCHAR2(15 BYTE), 
	"EVENT_NUMBER" VARCHAR2(4 BYTE), 
	"SEVERITY" NUMBER(1,0), 
	"DATA" VARCHAR2(150 BYTE), 
	"ID_EQUIPO" NUMBER, 
	"COD_USUARIO" NUMBER, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE, 
	"ID_LOCAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FM_EQUIPO
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FM_EQUIPO" 
   (	"ID_EQUIPO" NUMBER, 
	"DES_CLAVE" VARCHAR2(18 BYTE), 
	"DES_EQUIPO" VARCHAR2(25 BYTE), 
	"IP" VARCHAR2(15 BYTE), 
	"IND_ONLINE" NUMBER(1,0), 
	"IND_ACTIVO" NUMBER(1,0), 
	"ID_TIPO" NUMBER, 
	"ID_LOCAL" NUMBER, 
	"COD_USUARIO" NUMBER DEFAULT 0, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE, 
	"ID_NEGOCIO" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FM_TIP_ESTADO
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FM_TIP_ESTADO" 
   (	"ID_TIP_ESTADO" NUMBER(9,0), 
	"VAL_TIP_ESTADO" NUMBER(2,0), 
	"DES_TIP_ESTADO" VARCHAR2(75 BYTE), 
	"ABR_TIP_ESTADO" VARCHAR2(10 BYTE), 
	"BGCOLOR_TIP_ESTADO" VARCHAR2(7 BYTE), 
	"CSSFONT_TIP_ESTADO" VARCHAR2(250 BYTE), 
	"COD_USUARIO" NUMBER(9,0), 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FM_TIPO_EQUIPO
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FM_TIPO_EQUIPO" 
   (	"ID_TIPO" NUMBER, 
	"COD_TIPO" VARCHAR2(3 BYTE), 
	"DES_TIPO" VARCHAR2(25 BYTE), 
	"COD_USUARIO" NUMBER, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FM_TIP_SEVER
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FM_TIP_SEVER" 
   (	"ID_TIP_SEVER" NUMBER, 
	"VAL_TIP_SEVER" NUMBER, 
	"DES_TIP_SEVER" VARCHAR2(75 BYTE), 
	"ABR_TIP_SEVER" VARCHAR2(10 BYTE), 
	"BGCOLOR_TIP_SEVER" VARCHAR2(7 BYTE), 
	"CSSFONT_TIP_SEVER" VARCHAR2(250 BYTE), 
	"COD_USUARIO" NUMBER, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FP_EJECUCION
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FP_EJECUCION" 
   (	"ID_EJECUCION" NUMBER, 
	"ID_PROCESO" NUMBER, 
	"EXECUTION_DATE" DATE, 
	"ID_EQUIPO" NUMBER, 
	"TIP_ESTADO" NUMBER(2,0), 
	"DATA" VARCHAR2(150 BYTE), 
	"COD_USUARIO" NUMBER, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE, 
	"ID_LOCAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FP_INGRESO_MENSAJE
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FP_INGRESO_MENSAJE" 
   (	"DES_TRAMA" VARCHAR2(250 BYTE), 
	"IND_PROCESADO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FP_MONITOR
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FP_MONITOR" 
   (	"ID_EQUIPO" NUMBER, 
	"ID_PROCESO" NUMBER, 
	"TIP_ESTADO" NUMBER(2,0), 
	"ID_LOCAL" NUMBER, 
	"ID_NEGOCIO" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FP_MONITOR_DET
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FP_MONITOR_DET" 
   (	"ID_EQUIPO" NUMBER, 
	"ID_PROCESO" NUMBER, 
	"ID_EJECUCION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FP_PROCESO
--------------------------------------------------------

  CREATE TABLE "EYES_EC"."FP_PROCESO" 
   (	"ID_PROCESO" NUMBER, 
	"DES_CLAVE" VARCHAR2(18 BYTE), 
	"DES_PROCESO" VARCHAR2(50 BYTE), 
	"COD_USUARIO" NUMBER, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE, 
	"ABR_PROCESO" VARCHAR2(18 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
    CREATE TABLE "EYES_EC"."STR_STS" 
   (	
  	ID_STR_STS 		NUMBER,
  	TML				NUMBER,
  	STR_CD			NUMBER(*,0),
  	LOG_NM			VARCHAR2(8 BYTE),
  	NMB_CL			NUMBER,
  	CL_FL			NUMBER,
  	DT_TM			DATE,
  	MNTR			NUMBER,
  	CL_CTL_FL		NUMBER,
  	INDICAT_0		NUMBER,
  	INDICAT_1		NUMBER,
  	RSRVD			VARCHAR2(46 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
    CREATE TABLE "EYES_EC"."WS_STS" 
   (	
	ID_WS_STS 		NUMBER,
  	PRD				NUMBER,
  	TML				NUMBER,
  	OPR				NUMBER,
  	STR_CD			NUMBER(*,0),
  	TRN_NMB			NUMBER,
  	NMB_LO			NUMBER,
  	AMT_LO			NUMBER,
  	NMB_PKP			NUMBER,
  	AMT_PKP			NUMBER,
  	GS_PSTV			NUMBER,
  	GS_NV			NUMBER
  	AMT_MSC			NUMBER,
  	NMB_TRN			NUMBER,
  	TL_AMT_CSH		NUMBER,
  	TL_AMT_CHK		NUMBER,
  	TL_AMT_FDS		NUMBER,
  	TL_AMT_MSC_1	NUMBER,
  	TL_AMT_MSC_2	NUMBER,
  	TL_AMT_MSC_3	NUMBER,
  	TL_AMT_MF		NUMBER,
  	TL_AMT_STR		NUMBER,
  	TRN_TY			NUMBER,
  	STS				NUMBER,
  	STS_2			NUMBER,
  	ULT_NUM_FACT    VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


REM INSERTING into EYES_EC.FM_TIP_ESTADO
SET DEFINE OFF;
Insert into EYES_EC.FM_TIP_ESTADO (ID_TIP_ESTADO,VAL_TIP_ESTADO,DES_TIP_ESTADO,ABR_TIP_ESTADO,BGCOLOR_TIP_ESTADO,CSSFONT_TIP_ESTADO,COD_USUARIO,FEC_ACTUALIZACION) values ('1','20','Iniciado','STR','#33691E','color:#FFF','1103',to_date('27/10/15','DD/MM/RR'));
Insert into EYES_EC.FM_TIP_ESTADO (ID_TIP_ESTADO,VAL_TIP_ESTADO,DES_TIP_ESTADO,ABR_TIP_ESTADO,BGCOLOR_TIP_ESTADO,CSSFONT_TIP_ESTADO,COD_USUARIO,FEC_ACTUALIZACION) values ('2','10','Finalizado','END','#A0A0A0','color:#FFF','1103',to_date('27/10/15','DD/MM/RR'));
Insert into EYES_EC.FM_TIP_ESTADO (ID_TIP_ESTADO,VAL_TIP_ESTADO,DES_TIP_ESTADO,ABR_TIP_ESTADO,BGCOLOR_TIP_ESTADO,CSSFONT_TIP_ESTADO,COD_USUARIO,FEC_ACTUALIZACION) values ('3','30','Finalizado con Alerta','WAR','#FF9800','color:#FFF','1103',to_date('27/10/15','DD/MM/RR'));
Insert into EYES_EC.FM_TIP_ESTADO (ID_TIP_ESTADO,VAL_TIP_ESTADO,DES_TIP_ESTADO,ABR_TIP_ESTADO,BGCOLOR_TIP_ESTADO,CSSFONT_TIP_ESTADO,COD_USUARIO,FEC_ACTUALIZACION) values ('4','40','Finalizado con Error','ERR','#F44336','color:#FFF','1103',to_date('27/10/15','DD/MM/RR'));
Insert into EYES_EC.FM_TIP_ESTADO (ID_TIP_ESTADO,VAL_TIP_ESTADO,DES_TIP_ESTADO,ABR_TIP_ESTADO,BGCOLOR_TIP_ESTADO,CSSFONT_TIP_ESTADO,COD_USUARIO,FEC_ACTUALIZACION) values ('5','50','en Curso','PRC','#2962FF','color:#FFF','1103',to_date('27/10/15','DD/MM/RR'));

REM INSERTING into EYES_EC.FM_TIPO_EQUIPO
SET DEFINE OFF;
Insert into EYES_EC.FM_TIPO_EQUIPO (ID_TIPO,COD_TIPO,DES_TIPO,COD_USUARIO,FEC_ACTUALIZACION) values ('1','CNT','Controlador','1101',to_date('22/04/13','DD/MM/RR'));
Insert into EYES_EC.FM_TIPO_EQUIPO (ID_TIPO,COD_TIPO,DES_TIPO,COD_USUARIO,FEC_ACTUALIZACION) values ('2','POS','Terminal POS','1101',to_date('23/04/13','DD/MM/RR'));
Insert into EYES_EC.FM_TIPO_EQUIPO (ID_TIPO,COD_TIPO,DES_TIPO,COD_USUARIO,FEC_ACTUALIZACION) values ('3','SRV','Servidor','1101',to_date('24/08/15','DD/MM/RR'));

REM INSERTING into EYES_EC.FM_TIP_SEVER
SET DEFINE OFF;
Insert into EYES_EC.FM_TIP_SEVER (ID_TIP_SEVER,VAL_TIP_SEVER,DES_TIP_SEVER,ABR_TIP_SEVER,BGCOLOR_TIP_SEVER,CSSFONT_TIP_SEVER,COD_USUARIO,FEC_ACTUALIZACION) values ('5','5','Severidad 5','5','#00695C','color:#FFF','1103',to_date('29/10/15','DD/MM/RR'));
Insert into EYES_EC.FM_TIP_SEVER (ID_TIP_SEVER,VAL_TIP_SEVER,DES_TIP_SEVER,ABR_TIP_SEVER,BGCOLOR_TIP_SEVER,CSSFONT_TIP_SEVER,COD_USUARIO,FEC_ACTUALIZACION) values ('4','4','Severidad 4','4','#2962FF','color:#FFF','1103',to_date('29/10/15','DD/MM/RR'));
Insert into EYES_EC.FM_TIP_SEVER (ID_TIP_SEVER,VAL_TIP_SEVER,DES_TIP_SEVER,ABR_TIP_SEVER,BGCOLOR_TIP_SEVER,CSSFONT_TIP_SEVER,COD_USUARIO,FEC_ACTUALIZACION) values ('3','3','Severidad 3','3','#FFC400','color:#333','1103',to_date('29/10/15','DD/MM/RR'));
Insert into EYES_EC.FM_TIP_SEVER (ID_TIP_SEVER,VAL_TIP_SEVER,DES_TIP_SEVER,ABR_TIP_SEVER,BGCOLOR_TIP_SEVER,CSSFONT_TIP_SEVER,COD_USUARIO,FEC_ACTUALIZACION) values ('2','2','Severidad 2','2','#EF6C00','color:#FFF','1103',to_date('29/10/15','DD/MM/RR'));
Insert into EYES_EC.FM_TIP_SEVER (ID_TIP_SEVER,VAL_TIP_SEVER,DES_TIP_SEVER,ABR_TIP_SEVER,BGCOLOR_TIP_SEVER,CSSFONT_TIP_SEVER,COD_USUARIO,FEC_ACTUALIZACION) values ('1','1','Severidad 1','1','#F44336','color:#FFF','1103',to_date('29/10/15','DD/MM/RR'));

REM INSERTING into EYES_EC.FP_PROCESO
SET DEFINE OFF;
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('4','CONS_CPR_O','Consulta Cedula, Padron o Ruc',null,to_date('26/08/15','DD/MM/RR'),'Con.CedPadRuc.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('5','CONS_CURE_O','Consulta Cupon Redimible',null,to_date('26/08/15','DD/MM/RR'),'Con.CpnRed.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('6','CONS_CUST_O','Consulta Customer',null,to_date('26/08/15','DD/MM/RR'),'Con.Cust.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('7','TSL_READ_O','Lectura de TSL',null,to_date('26/08/15','DD/MM/RR'),'Lec.TSL(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('8','CONS_DEV_O','Consulta Devolucion',null,to_date('26/08/15','DD/MM/RR'),'Con.Dev.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('9','UPD_DEV_O','Actualizacion de Devolucion',null,to_date('26/08/15','DD/MM/RR'),'Act.Dev.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('10','UPD_ITEM_O','Actualizacion de  Items',null,to_date('26/08/15','DD/MM/RR'),'Act.Item.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('11','UPD_MOTO_O','Actualizacion de Motos',null,to_date('26/08/15','DD/MM/RR'),'Act.Moto.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('12','CONS_RET_O','Consulta Factura para Retencion',null,to_date('26/08/15','DD/MM/RR'),'Con.FactRet.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('13','GEN_SUTRX_O','Generador de Transacciones Suspendidas',null,to_date('26/08/15','DD/MM/RR'),'Gen.TrxSusp.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('14','OPER_UPD_P','Actualizacion de Operador',null,to_date('26/08/15','DD/MM/RR'),'Act.Opera.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('15','UPD_CPR_P','Actualizacion de Cedula, Padron o Ruc',null,to_date('26/08/15','DD/MM/RR'),'Act.CedPadRuc.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('16','ACT_GFC_P','Activacion de Giftcard',null,to_date('26/08/15','DD/MM/RR'),'Act.Gift.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('17','SRCH_ITEM_P','Busqueda de Archivos Item',null,to_date('26/08/15','DD/MM/RR'),'Bsc.Item.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('18','SRCH_MOTO_P','Busqueda de Archivos Moto',null,to_date('26/08/15','DD/MM/RR'),'Bsc.Moto.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('19','SRCH_PRNT_P','Busqueda de Archivos de Impreson',null,to_date('26/08/15','DD/MM/RR'),'Bsc.ArcImpr.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('20','OPER_UPD_O','Actualizacion de Operador',null,to_date('26/08/15','DD/MM/RR'),'Act.Opera (O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('21','TSL_READ_P','Lectura de TSL',null,to_date('26/08/15','DD/MM/RR'),'Lec.TSL.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('22','UPD_ITEM_P','Actualizacion de Items',null,to_date('26/08/15','DD/MM/RR'),'Act.Item.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('23','UPD_MOTO_P','Actualizacion de Motos',null,to_date('26/08/15','DD/MM/RR'),'Act.Moto.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('24','GEN_SUTRX_P','Generador de Transacciones Suspendidas',null,to_date('26/08/15','DD/MM/RR'),'Gen.TrxSusp.(P)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('25','CONS_CUDA_O','Consulta Customer Data',null,to_date('26/08/15','DD/MM/RR'),'Con.CustData.(O)');
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('92744','CH_ITEM_P',null,null,to_date('04/12/15','DD/MM/RR'),null);
Insert into EYES_EC.FP_PROCESO (ID_PROCESO,DES_CLAVE,DES_PROCESO,COD_USUARIO,FEC_ACTUALIZACION,ABR_PROCESO) values ('117078','L_READ_P',null,null,to_date('10/12/15','DD/MM/RR'),null);
--------------------------------------------------------
--  DDL for Index FM_TIP_ESTADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYES_EC"."FM_TIP_ESTADO_PK" ON "EYES_EC"."FM_TIP_ESTADO" ("ID_TIP_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKFP_DISPOSITIVO
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYES_EC"."XPKFP_DISPOSITIVO" ON "EYES_EC"."FM_EQUIPO" ("ID_EQUIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKFP_EJEC_PROC
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYES_EC"."XPKFP_EJEC_PROC" ON "EYES_EC"."FP_EJECUCION" ("ID_EJECUCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKFP_MONITOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYES_EC"."XPKFP_MONITOR" ON "EYES_EC"."FP_MONITOR" ("ID_EQUIPO", "ID_PROCESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKFP_MONITOR_MSG
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYES_EC"."XPKFP_MONITOR_MSG" ON "EYES_EC"."FP_MONITOR_DET" ("ID_EQUIPO", "ID_PROCESO", "ID_EJECUCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKFP_PROCESO
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYES_EC"."XPKFP_PROCESO" ON "EYES_EC"."FP_PROCESO" ("ID_PROCESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKFP_TIPO_DISPOSITIVO
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYES_EC"."XPKFP_TIPO_DISPOSITIVO" ON "EYES_EC"."FM_TIPO_EQUIPO" ("ID_TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XPKMESSAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "EYES_EC"."XPKMESSAGE" ON "EYES_EC"."FE_MESSAGE" ("ID_MESSAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  CREATE UNIQUE INDEX "EYES_EC"."STR_STS_IDX" ON "EYES_EC"."STR_STS" ("ID_STR_STS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  CREATE UNIQUE INDEX "EYES_EC"."WS_STS_IDX" ON "EYES_EC"."WS_STS" ("ID_WS_STS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "EYES_EC"."STR_STS" ADD CONSTRAINT "XPK_STR_STS" PRIMARY KEY ("ID_STR_STS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EYES_EC"."STR_STS" MODIFY ("ID_STR_STS" NOT NULL ENABLE);
  
  ALTER TABLE "EYES_EC"."WS_STS" ADD CONSTRAINT "XPK_WS_STS" PRIMARY KEY ("ID_WS_STS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EYES_EC"."WS_STS" MODIFY ("ID_WS_STS" NOT NULL ENABLE);
  ALTER TABLE "EYES_EC"."WS_STS" MODIFY ("PRD" NOT NULL ENABLE);
  ALTER TABLE "EYES_EC"."WS_STS" MODIFY ("TML" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FE_MESSAGE
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FE_MESSAGE" ADD CONSTRAINT "XPKMESSAGE" PRIMARY KEY ("ID_MESSAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EYES_EC"."FE_MESSAGE" MODIFY ("ID_MESSAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FM_EQUIPO
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FM_EQUIPO" MODIFY ("ID_EQUIPO" NOT NULL ENABLE);
  ALTER TABLE "EYES_EC"."FM_EQUIPO" ADD CONSTRAINT "FM_EQUIPO_PK" PRIMARY KEY ("ID_EQUIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FM_TIP_ESTADO
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FM_TIP_ESTADO" MODIFY ("ID_TIP_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "EYES_EC"."FM_TIP_ESTADO" ADD CONSTRAINT "FM_TIP_ESTADO_PK" PRIMARY KEY ("ID_TIP_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FM_TIPO_EQUIPO
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FM_TIPO_EQUIPO" ADD CONSTRAINT "XPKFP_TIPO_DISPOSITIVO" PRIMARY KEY ("ID_TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EYES_EC"."FM_TIPO_EQUIPO" MODIFY ("ID_TIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FP_EJECUCION
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FP_EJECUCION" ADD CONSTRAINT "XPKFP_EJEC_PROC" PRIMARY KEY ("ID_EJECUCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EYES_EC"."FP_EJECUCION" MODIFY ("ID_EJECUCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FP_MONITOR
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FP_MONITOR" ADD CONSTRAINT "XPKFP_MONITOR" PRIMARY KEY ("ID_EQUIPO", "ID_PROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EYES_EC"."FP_MONITOR" MODIFY ("ID_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "EYES_EC"."FP_MONITOR" MODIFY ("ID_EQUIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FP_MONITOR_DET
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FP_MONITOR_DET" ADD CONSTRAINT "XPKFP_MONITOR_MSG" PRIMARY KEY ("ID_EQUIPO", "ID_PROCESO", "ID_EJECUCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EYES_EC"."FP_MONITOR_DET" MODIFY ("ID_EJECUCION" NOT NULL ENABLE);
  ALTER TABLE "EYES_EC"."FP_MONITOR_DET" MODIFY ("ID_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "EYES_EC"."FP_MONITOR_DET" MODIFY ("ID_EQUIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FP_PROCESO
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FP_PROCESO" ADD CONSTRAINT "XPKFP_PROCESO" PRIMARY KEY ("ID_PROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EYES_EC"."FP_PROCESO" MODIFY ("DES_CLAVE" NOT NULL ENABLE);
  ALTER TABLE "EYES_EC"."FP_PROCESO" MODIFY ("ID_PROCESO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FM_EQUIPO
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FM_EQUIPO" ADD CONSTRAINT "R_10" FOREIGN KEY ("ID_TIPO")
	  REFERENCES "EYES_EC"."FM_TIPO_EQUIPO" ("ID_TIPO") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FP_EJECUCION
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FP_EJECUCION" ADD CONSTRAINT "R_3" FOREIGN KEY ("ID_PROCESO")
	  REFERENCES "EYES_EC"."FP_PROCESO" ("ID_PROCESO") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FP_MONITOR
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FP_MONITOR" ADD CONSTRAINT "R_14" FOREIGN KEY ("ID_PROCESO")
	  REFERENCES "EYES_EC"."FP_PROCESO" ("ID_PROCESO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FP_MONITOR_DET
--------------------------------------------------------

  ALTER TABLE "EYES_EC"."FP_MONITOR_DET" ADD CONSTRAINT "R_16" FOREIGN KEY ("ID_EQUIPO", "ID_PROCESO")
	  REFERENCES "EYES_EC"."FP_MONITOR" ("ID_EQUIPO", "ID_PROCESO") ENABLE;
