--------------------------------------------------------
--  DDL for Sequence SQ_ARC_ITM
--------------------------------------------------------

   CREATE SEQUENCE  "PRCFLJ_EC"."SQ_ARC_ITM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 38901 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ARC_MOV
--------------------------------------------------------

   CREATE SEQUENCE  "PRCFLJ_EC"."SQ_ARC_MOV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1341 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ID_ARCITEM
--------------------------------------------------------

   CREATE SEQUENCE  "PRCFLJ_EC"."SQ_ID_ARCITEM"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 4382 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ID_FLJART
--------------------------------------------------------

   CREATE SEQUENCE  "PRCFLJ_EC"."SQ_ID_FLJART"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 542 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "PRCFLJ_EC"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table ARC_EXPRC
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."ARC_EXPRC" 
   (	"ID_ARCPRC" NUMBER(38,0), 
	"NUM_LINLO" NUMBER(38,0), 
	"EXCEPCION" CHAR(1 BYTE), 
	"DECIDE" CHAR(1 BYTE), 
	"IDREG" NUMBER(38,0), 
	"FECHA" DATE DEFAULT SYSDATE, 
	"NUM_LINEX" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PRCFLJ_EC"."ARC_EXPRC"."EXCEPCION" IS 'A-U-D';
   COMMENT ON COLUMN "PRCFLJ_EC"."ARC_EXPRC"."DECIDE" IS 'S-N';
--------------------------------------------------------
--  DDL for Table ARC_ITEMS
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."ARC_ITEMS" 
   (	"ID_ARCITEM" NUMBER(38,0), 
	"ID_ARCPRC" NUMBER(38,0) DEFAULT 0, 
	"ESTADO" NUMBER DEFAULT 0, 
	"ARCHIVO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARC_MOV
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."ARC_MOV" 
   (	"ID_MOV" NUMBER, 
	"ID_ARCPRC" NUMBER, 
	"ID_ESTPRC" NUMBER, 
	"FEC_MOV" DATE DEFAULT SYSDATE, 
	"HOR_MOV" VARCHAR2(8 BYTE), 
	"IDREG" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARC_PRC
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."ARC_PRC" 
   (	"ID_ARCPRC" NUMBER(38,0), 
	"NOM_ARCPRC" VARCHAR2(200 BYTE), 
	"NUM_ITEMS" NUMBER(38,0), 
	"COD_TIENDA" NUMBER(38,0), 
	"ID_ESTPRC" NUMBER(3,0) DEFAULT 0, 
	"FEC_PROC" DATE DEFAULT SYSDATE, 
	"NOM_ARCLOTE" VARCHAR2(200 BYTE), 
	"COD_NEGOCIO" NUMBER, 
	"ID_ARCSAP" NUMBER(38,0) DEFAULT 0, 
	"ID_DPT_PS" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
--------------------------------------------------------
--  DDL for Table MOTO_FILES
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."MOTO_FILES" 
   (	"ID_MOTOFILE" NUMBER(38,0), 
	"NOM_MOTOFILE" VARCHAR2(200 BYTE) 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARC_PRCEX
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."ARC_PRCEX" 
   (	"ID_ARCPRC" NUMBER(38,0), 
	"NOM_ARCEX" VARCHAR2(200 BYTE), 
	"NUM_ITEMS" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARC_SAP
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."ARC_SAP" 
   (	"ID_ARCSAP" NUMBER(38,0), 
	"COD_TIENDA" NUMBER(38,0), 
	"NUM_LOTE" NUMBER(38,0), 
	"ARCITEM" VARCHAR2(200 BYTE), 
	"NUM_ITEM" NUMBER(38,0) DEFAULT 0, 
	"ARCEAN" VARCHAR2(200 BYTE), 
	"NUM_EAN" NUMBER(38,0) DEFAULT 0, 
	"ARCERRI" VARCHAR2(200 BYTE), 
	"NUM_ERRI" NUMBER(38,0) DEFAULT 0, 
	"ARCERRE" VARCHAR2(200 BYTE), 
	"NUM_ERRE" NUMBER(38,0) DEFAULT 0, 
	"FECHA" DATE DEFAULT SYSDATE, 
	"ID_ESTPRC" NUMBER(38,0) DEFAULT 2
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EST_PRC
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."EST_PRC" 
   (	"ID_ESTPRC" NUMBER(3,0), 
	"NOM_ESTPRC" VARCHAR2(200 BYTE), 
	"COL_ESTPRC" VARCHAR2(7 BYTE), 
	"CSF_ESTADO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FLJ_PRC
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."FLJ_PRC" 
   (	"ID_FLJPRC" NUMBER(38,0), 
	"ID_FTIPO" NUMBER(38,0), 
	"ID_ARCPRC" NUMBER(38,0), 
	"NUM_FLEJES" NUMBER(38,0), 
	"CD_ITM" VARCHAR2(25 BYTE), 
	"MO_ITM" NUMBER(14,0), 
	"NM_ITM" VARCHAR2(50 BYTE), 
	"CB_ITM" NUMBER(18,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FLJ_TIPO
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."FLJ_TIPO" 
   (	"ID_FTIPO" NUMBER(38,0), 
	"NOM_FTIPO" VARCHAR2(200 BYTE), 
	"EST_FTIPO" NUMBER, 
	"COD_FTIPO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMP_FLJ
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."IMP_FLJ" 
   (	"ID_FLEJE" NUMBER, 
	"COD_TIENDA" NUMBER, 
	"COD_FTIPO" CHAR(1 BYTE), 
	"ARCHIVO" VARCHAR2(250 BYTE), 
	"IDREG" NUMBER, 
	"FECHA" DATE DEFAULT SYSDATE, 
	"ESTADO" NUMBER DEFAULT 0, 
	"COD_NEGOCIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PRCFLJ_EC"."IMP_FLJ"."ESTADO" IS '0:TEMP, 1:IMPR';
--------------------------------------------------------
--  DDL for Table IMP_FLJART
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."IMP_FLJART" 
   (	"ID_FLEJE" NUMBER, 
	"CD_ITM" NUMBER, 
	"QN_ITM" NUMBER, 
	"ID_FLJART" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRC_PRC
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."PRC_PRC" 
   (	"ID_PRCPRC" NUMBER(38,0), 
	"ID_ARCPRC" NUMBER(38,0), 
	"FEC_PRCPRC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table ARTICBALANZA
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."ARTICBALANZA" 
   (	"ARTICULO" VARCHAR2(20 BYTE) DEFAULT '', 
	"DESCRIPCION" VARCHAR2(40 BYTE) DEFAULT '', 
	"PRECIO_PUB" NUMBER(10,2) DEFAULT 0.00, 
	"PRECIO_COM" NUMBER(10,2) DEFAULT 0.00, 
	"PORC_RECARGO" NUMBER(4,2) DEFAULT 0.00, 
	"IND_IVA" CHAR(1 BYTE) DEFAULT '', 
	"IND_AL_PESO" CHAR(1 BYTE) DEFAULT 0, 
	"COD_SECCION" VARCHAR2(4 BYTE) DEFAULT '', 
	"COD_SUBSEC" VARCHAR2(4 BYTE) DEFAULT '', 
	"JERARQUIA_SAP" VARCHAR2(10 BYTE) DEFAULT '', 
	"NOMBRE_GRUPO" VARCHAR2(60 BYTE) DEFAULT '', 
	"FCH_ULT_CAMBIO" DATE DEFAULT NULL, 
	"DIAS_REFRIGER" NUMBER(3,0) DEFAULT 0, 
	"DIAS_CONGELAC" NUMBER(3,0) DEFAULT 0, 
	"IND_EMPACADO" CHAR(1 BYTE) DEFAULT 0, 
	"PROCESADO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_USERBALANZA
--------------------------------------------------------

  CREATE TABLE "PRCFLJ_EC"."T_USERBALANZA" 
   (	"LOGIN_I" VARCHAR2(10 BYTE) DEFAULT '', 
	"NOMBRE_USER" VARCHAR2(30 BYTE) DEFAULT '', 
	"CLAVE" VARCHAR2(15 BYTE) DEFAULT '', 
	"FCH_ULT_CAMBIO" DATE DEFAULT NULL, 
	"PROCESADO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRCFLJ_EC.ARTICBALANZA
SET DEFINE OFF;
REM INSERTING into PRCFLJ_EC.T_USERBALANZA
SET DEFINE OFF;

REM INSERTING into PRCFLJ_EC.EST_PRC
SET DEFINE OFF;
Insert into PRCFLJ_EC.EST_PRC (ID_ESTPRC,NOM_ESTPRC,COL_ESTPRC,CSF_ESTADO) values ('4','GENERAR FLEJES','#8BC34A','color:#FFF');
Insert into PRCFLJ_EC.EST_PRC (ID_ESTPRC,NOM_ESTPRC,COL_ESTPRC,CSF_ESTADO) values ('7','EN PROCESO','#EC407A','color:#FFF');
Insert into PRCFLJ_EC.EST_PRC (ID_ESTPRC,NOM_ESTPRC,COL_ESTPRC,CSF_ESTADO) values ('2','PROCESAR','#7A2A9C','color:#FFF');
Insert into PRCFLJ_EC.EST_PRC (ID_ESTPRC,NOM_ESTPRC,COL_ESTPRC,CSF_ESTADO) values ('3','RECHAZADO','#F44336','color:#FFF');
Insert into PRCFLJ_EC.EST_PRC (ID_ESTPRC,NOM_ESTPRC,COL_ESTPRC,CSF_ESTADO) values ('6','ACTIVAR PRECIOS','#33691E','color:#FFF');
Insert into PRCFLJ_EC.EST_PRC (ID_ESTPRC,NOM_ESTPRC,COL_ESTPRC,CSF_ESTADO) values ('5','IMPRESION','#689F38','color:#FFF');
Insert into PRCFLJ_EC.EST_PRC (ID_ESTPRC,NOM_ESTPRC,COL_ESTPRC,CSF_ESTADO) values ('0','EN RECEPCION','#C8C8C8','color:#333');
Insert into PRCFLJ_EC.EST_PRC (ID_ESTPRC,NOM_ESTPRC,COL_ESTPRC,CSF_ESTADO) values ('1','EXCEPCIONES','#FFB300','color:#FFF');
Insert into PRCFLJ_EC.EST_PRC (ID_ESTPRC,NOM_ESTPRC,COL_ESTPRC,CSF_ESTADO) values ('8','PROCESADO','#C8C8C8','color:#FFF');

REM INSERTING into PRCFLJ_EC.FLJ_TIPO
SET DEFINE OFF;
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (1, 'INDIVIDUAL', 1, 'I');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (2, 'DE ROPA', 1, 'R');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (3, 'MAYORISTA', 0, 'M');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (4, 'PERCHA', 1, 'P');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (5, 'DIFERIDO', 1, 'D');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (6, 'CAJA', 1, 'V');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (7, 'HABLADOR', 1, 'H');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (8, 'GRANDE PERCHA', 0, 'G');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (9, 'REDONDA PEQUEÑA', 0, 'D');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (10, 'INVERSA CAJA', 0, 'N');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (11, 'MAYORISTA CAJA', 1, 'Z');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (12, 'MAYORISTA UNIDAD', 1, 'U');
INSERT into PRCFLJ_EC.FLJ_TIPO (ID_FTIPO,NOM_FTIPO,EST_FTIPO,COD_FTIPO) VALUES (13, 'ETIQUETA CAJA', 0, 'C');

--------------------------------------------------------
--  DDL for Index ARC_ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCFLJ_EC"."ARC_ITEMS_PK" ON "PRCFLJ_EC"."ARC_ITEMS" ("ID_ARCITEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARC_MOV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCFLJ_EC"."ARC_MOV_PK" ON "PRCFLJ_EC"."ARC_MOV" ("ID_MOV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARC_PRC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCFLJ_EC"."ARC_PRC_PK" ON "PRCFLJ_EC"."ARC_PRC" ("ID_ARCPRC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index MOTO_FILES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCFLJ_EC"."MOTO_FILES_PK" ON "PRCFLJ_EC"."MOTO_FILES" ("ID_MOTOFILE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EST_PRC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCFLJ_EC"."EST_PRC_PK" ON "PRCFLJ_EC"."EST_PRC" ("ID_ESTPRC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FLJ_TIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCFLJ_EC"."FLJ_TIPO_PK" ON "PRCFLJ_EC"."FLJ_TIPO" ("ID_FTIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMP_FLJART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCFLJ_EC"."IMP_FLJART_PK" ON "PRCFLJ_EC"."IMP_FLJART" ("ID_FLJART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IMP_FLJ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRCFLJ_EC"."IMP_FLJ_PK" ON "PRCFLJ_EC"."IMP_FLJ" ("ID_FLEJE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARC_ITEMS
--------------------------------------------------------

  ALTER TABLE "PRCFLJ_EC"."ARC_ITEMS" MODIFY ("ID_ARCITEM" NOT NULL ENABLE);
  ALTER TABLE "PRCFLJ_EC"."ARC_ITEMS" ADD CONSTRAINT "ARC_ITEMS_PK" PRIMARY KEY ("ID_ARCITEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARC_MOV
--------------------------------------------------------

  ALTER TABLE "PRCFLJ_EC"."ARC_MOV" ADD CONSTRAINT "ARC_MOV_PK" PRIMARY KEY ("ID_MOV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRCFLJ_EC"."ARC_MOV" MODIFY ("ID_MOV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARC_PRC
--------------------------------------------------------

  ALTER TABLE "PRCFLJ_EC"."ARC_PRC" MODIFY ("ID_ARCPRC" NOT NULL ENABLE);
  ALTER TABLE "PRCFLJ_EC"."ARC_PRC" ADD CONSTRAINT "ARC_PRC_PK" PRIMARY KEY ("ID_ARCPRC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  
--------------------------------------------------------
--  Constraints for Table MOTO_FILES
--------------------------------------------------------

  ALTER TABLE "PRCFLJ_EC"."MOTO_FILES" MODIFY ("ID_MOTOFILE" NOT NULL ENABLE);
  ALTER TABLE "PRCFLJ_EC"."MOTO_FILES" ADD CONSTRAINT "MOTO_FILES_PK" PRIMARY KEY ("ID_MOTOFILE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EST_PRC
--------------------------------------------------------

  ALTER TABLE "PRCFLJ_EC"."EST_PRC" MODIFY ("ID_ESTPRC" NOT NULL ENABLE);
  ALTER TABLE "PRCFLJ_EC"."EST_PRC" ADD CONSTRAINT "EST_PRC_PK" PRIMARY KEY ("ID_ESTPRC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FLJ_TIPO
--------------------------------------------------------

  ALTER TABLE "PRCFLJ_EC"."FLJ_TIPO" MODIFY ("ID_FTIPO" NOT NULL ENABLE);
  ALTER TABLE "PRCFLJ_EC"."FLJ_TIPO" ADD CONSTRAINT "FLJ_TIPO_PK" PRIMARY KEY ("ID_FTIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMP_FLJ
--------------------------------------------------------

  ALTER TABLE "PRCFLJ_EC"."IMP_FLJ" MODIFY ("ID_FLEJE" NOT NULL ENABLE);
  ALTER TABLE "PRCFLJ_EC"."IMP_FLJ" ADD CONSTRAINT "IMP_FLJ_PK" PRIMARY KEY ("ID_FLEJE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMP_FLJART
--------------------------------------------------------

  ALTER TABLE "PRCFLJ_EC"."IMP_FLJART" MODIFY ("ID_FLJART" NOT NULL ENABLE);
  ALTER TABLE "PRCFLJ_EC"."IMP_FLJART" ADD CONSTRAINT "IMP_FLJART_PK" PRIMARY KEY ("ID_FLJART")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARC_PRC
--------------------------------------------------------

  ALTER TABLE "PRCFLJ_EC"."ARC_PRC" ADD CONSTRAINT "ARC_PRC_FK1" FOREIGN KEY ("ID_ESTPRC")
	  REFERENCES "PRCFLJ_EC"."EST_PRC" ("ID_ESTPRC") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_ARC_ITEMS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRCFLJ_EC"."TR_ARC_ITEMS" 
  before insert on PRCFLJ_EC.ARC_ITEMS
  for each row
declare

begin
    SELECT SQ_ID_ARCITEM.NEXTVAL
      INTO :NEW.ID_ARCITEM
      FROM DUAL;
  
end TR_ARC_ITEMS;
/
ALTER TRIGGER "PRCFLJ_EC"."TR_ARC_ITEMS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_ARC_LTM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRCFLJ_EC"."TR_ARC_LTM" 
  before insert on PRCFLJ_EC.ARC_ITEMS
  for each row
declare

begin
    SELECT SQ_ARC_ITM.NEXTVAL
      INTO :NEW.ID_ARCITEM
      FROM DUAL;
  
end TR_ARC_LTM;
/
ALTER TRIGGER "PRCFLJ_EC"."TR_ARC_LTM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_ARC_MOV
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRCFLJ_EC"."TR_ARC_MOV" 
  before insert on PRCFLJ_EC.ARC_MOV
  for each row
declare

begin
    SELECT SQ_ARC_MOV.NEXTVAL
      INTO :NEW.ID_MOV
      FROM DUAL;
  
end TR_ARC_MOV;
/
ALTER TRIGGER "PRCFLJ_EC"."TR_ARC_MOV" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_IMP_FLJART
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRCFLJ_EC"."TR_IMP_FLJART" 
  before insert on PRCFLJ_EC.IMP_FLJART
  for each row
declare

begin
    SELECT SQ_ID_FLJART.NEXTVAL
      INTO :NEW.ID_FLJART
      FROM DUAL;
  
end TR_ID_FLJART;
/
ALTER TRIGGER "PRCFLJ_EC"."TR_IMP_FLJART" ENABLE;
