--------------------------------------------------------
--  DDL for Sequence SQ_BDVAL
--------------------------------------------------------

   CREATE SEQUENCE  "TDVAL_EC"."SQ_BDVAL"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 202 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BDVAL
--------------------------------------------------------

  CREATE TABLE "TDVAL_EC"."BDVAL" 
   (	"ID_BDVAL" NUMBER, 
	"ESTADO" NUMBER DEFAULT 0, 
	"FECHA" DATE DEFAULT SYSDATE, 
	"IDREG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TDVAL_EC"."BDVAL"."ID_BDVAL" IS 'IDENTIFICADOR BOLSA DE VALORES';
   COMMENT ON COLUMN "TDVAL_EC"."BDVAL"."ESTADO" IS '0=EN REGISTRO, 1=ENTREGADO, 2=DEVUELTO';
   COMMENT ON COLUMN "TDVAL_EC"."BDVAL"."FECHA" IS 'FECHA DE REGISTRO';
   COMMENT ON COLUMN "TDVAL_EC"."BDVAL"."IDREG" IS 'USUARIO ARMS';
--------------------------------------------------------
--  DDL for Table BDV_RET
--------------------------------------------------------

  CREATE TABLE "TDVAL_EC"."BDV_RET" 
   (	"ID_BDVAL" NUMBER, 
	"ID_TRN" NUMBER(38,0), 
	"CD_STR_RT" VARCHAR2(255 BYTE), 
	"CD_WS" VARCHAR2(50 BYTE), 
	"CD_OPR" VARCHAR2(20 BYTE), 
	"AI_TRN" NUMBER(38,0), 
	"DE_TND" VARCHAR2(255 BYTE), 
	"MO_TND_FN_TRN" NUMBER(14,0), 
	"TS_TICKET" DATE, 
	"TS_TRN_BGN" DATE, 
	"TS_TRN_END" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."ID_BDVAL" IS 'AGRUPADOR DE RETIROS. IDENTIFICADOR BOLSA DE VALORES';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."ID_TRN" IS 'IDENTIFICADOR TRANSACCION: TR_TRN.ID_TRN';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."CD_STR_RT" IS 'TIENDA: TR_TRN.ID_BSN_UN<->PA_STR_RTL.ID_STR_RT>>CD_STR_RT';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."CD_WS" IS 'TERMINAL: TR_TRN_ID_WS<->AS_WS.ID_WS>>CD_WS';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."CD_OPR" IS 'OPERADOR: TR_TRN.ID_OPR<->PA_OPR.ID_OPR>>CD_OPR';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."AI_TRN" IS 'NUM.TRANSACCION: TR_TRN.AI_TRN';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."DE_TND" IS 'MEDIOPAGO: TR_TRN.IDTRN<->TR_LTM_TND_CTL_TND.ID_TRN>>ID_TND<->AS_TND.ID_TND>>DE_TND';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."MO_TND_FN_TRN" IS 'IMPORTE: TR_TRN.IDTRN<->TR_LTM_TND_CTL_TND.ID_TRN>>MO_TND_FN_TRN';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."TS_TICKET" IS 'FECHA TICKET: TR_TRN.DC_DY_BSN';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."TS_TRN_BGN" IS 'INICIO TRX: TR_TRN.TS_TRN_BGN';
   COMMENT ON COLUMN "TDVAL_EC"."BDV_RET"."TS_TRN_END" IS 'FIN TRX: TR_TRN.TS_TRN_END';

--------------------------------------------------------
--  DDL for Index BDVAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDVAL_EC"."BDVAL_PK" ON "TDVAL_EC"."BDVAL" ("ID_BDVAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BDV_RET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDVAL_EC"."BDV_RET_PK" ON "TDVAL_EC"."BDV_RET" ("ID_BDVAL", "ID_TRN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BDVAL
--------------------------------------------------------

  ALTER TABLE "TDVAL_EC"."BDVAL" MODIFY ("ID_BDVAL" NOT NULL ENABLE);
  ALTER TABLE "TDVAL_EC"."BDVAL" ADD CONSTRAINT "BDVAL_PK" PRIMARY KEY ("ID_BDVAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BDV_RET
--------------------------------------------------------

  ALTER TABLE "TDVAL_EC"."BDV_RET" MODIFY ("ID_BDVAL" NOT NULL ENABLE);
  ALTER TABLE "TDVAL_EC"."BDV_RET" MODIFY ("ID_TRN" NOT NULL ENABLE);
  ALTER TABLE "TDVAL_EC"."BDV_RET" ADD CONSTRAINT "BDV_RET_PK" PRIMARY KEY ("ID_BDVAL", "ID_TRN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BDV_RET
--------------------------------------------------------

  ALTER TABLE "TDVAL_EC"."BDV_RET" ADD CONSTRAINT "BDV_RET_FK1" FOREIGN KEY ("ID_BDVAL")
	  REFERENCES "TDVAL_EC"."BDVAL" ("ID_BDVAL") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_BDVAL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TDVAL_EC"."TR_BDVAL" 
  before insert on TDVAL_EC.BDVAL
  for each row
declare

begin
    SELECT SQ_BDVAL.NEXTVAL
      INTO :NEW.ID_BDVAL
      FROM DUAL;
  
end TR_BDVAL;
/
ALTER TRIGGER "TDVAL_EC"."TR_BDVAL" ENABLE;
