
USE ARTS_EC
GO

   CREATE TABLE [dbo].[AS_BANK](
	[ID_BANK] [int] NOT NULL,
	[DES_BANK] [varchar](200) NULL,
	[NM_BANK] [varchar](100) NULL,
	PRIMARY KEY (ID_BANK)
   )
   
   CREATE TABLE [dbo].[AS_BANK_CTA](
	[ID_BANK] [int] NOT NULL,
	[NM_REFERENCIA] [varchar](100) NOT NULL,
	[CTA_BANK] [varchar](200) NOT NULL,
	[CD_SAP] [varchar](100) NOT NULL,
	[CD_CTA] [varchar](100) NOT NULL,
	[CD_CTACTB] [varchar](100) NOT NULL,
	[ID_CTAB] [int] NOT NULL,
	PRIMARY KEY (ID_CTAB)
	)
	
  CREATE TABLE AS_ITM
   (	
	ID_ITM				int IDENTITY (1, 1) NOT NULL,
    CD_ITM				bigint NOT NULL,
	NM_ITM 				VARCHAR(50), 
	ID_MRHRC_GP 		int NULL, 
	RP_SLS_CRT			decimal(19,4) NOT NULL DEFAULT 0, 
	CP_ITM				decimal(19,4) NULL, 
	RP_SLS_SPL			decimal(19,4) NULL, 
	ID_ITM_IVA			int NULL,
	FL_ITM_DSC			bit NULL DEFAULT 0, 
	FL_RP_RQ			bit NULL DEFAULT 0, 
	FL_WM_RQ			bit NULL DEFAULT 0, 
	FL_QY_RQ			bit NULL DEFAULT 0, 
	FL_QY_ALW			bit NULL DEFAULT 1, 
	ID_SPR 				int NULL, 
	ID_BRN 				int NULL, 
	ID_TY_ITM 			int not NULL DEFAULT 0, 
	RP_SLS_PRM 			decimal(19,4) NULL, 
	DT_STR_RP_PRM 		datetime, 
	DT_END_RP_PRM 		datetime, 
	ID_UOM 				int NULL, 
	ID_ITM_IMG 			int NULL, 
	TS_UPDT_RP_SLS_CRT	datetime, 
	FL_GNR_ITM 			bit NULL DEFAULT 0, 
	FL_ITM_KIT_CMP 		bit NULL DEFAULT 0, 
	DE_ITM 				VARCHAR(45), 
	CD_SAP 				bigint NULL,
	REF_SAP				VARCHAR(15), 
	JERARQUIA			VARCHAR(10),
	PRIMARY KEY (ID_ITM)
   )
   
   CREATE UNIQUE INDEX IX_AS_ITM ON AS_ITM (CD_ITM) 
   
   CREATE TABLE [dbo].[AS_ITM_SPL_FMY](
	[ID_SPL_FMY] [int] NULL,
	[DES_SPL_FMY] [varchar](200) NULL,
	[ID_SECESP] [int] IDENTITY(1,1) NOT NULL
   )
   
   CREATE TABLE AS_ITM_STR
   (
	ID_ITM 			int NOT NULL, 
	ID_BSN_UN 		int NOT NULL, 
	SLS_PRC 		decimal(14,3), 
	FL_AZN_FR_SLS 	bit NULL DEFAULT 0, 
	TX_A 			int NOT NULL DEFAULT 0, 
	TX_B 			int NOT NULL DEFAULT 0, 
	TX_C 			int NOT NULL DEFAULT 0, 
	TX_D 			int NOT NULL DEFAULT 0, 
	ID_SPL_FMY 		int NOT NULL DEFAULT 0, 
	TX_E 			int NOT NULL DEFAULT 0, 
	TX_F 			int NOT NULL DEFAULT 0, 
	TX_G 			int NOT NULL DEFAULT 0, 
	TX_H 			int NOT NULL DEFAULT 0,
	FLG_MAY 		int NOT NULL DEFAULT 0, 
	QTY_MAY 		int NOT NULL DEFAULT 0,
	PRC_MAY 		decimal(14,3),
	PROVEEDOR		VARCHAR(18),
	DEDUCIBLE		VARCHAR(3),
	COLOR			VARCHAR(10),
	MEDIDA			VARCHAR(4),
	DISENO			VARCHAR(4),
	MARCA			VARCHAR(15),
	PRESENTACION	VARCHAR(10),
	FL_ACUM_MOV_DAT 		int NOT NULL DEFAULT 0,
	FL_CP_COM_USED 			int NOT NULL DEFAULT 0,
	FL_MULT_VAL 			int NOT NULL DEFAULT 0,
	FL_SLS_EXCEP_LOG 		int NOT NULL DEFAULT 0,
	FL_CHG_ITEM_CHG_FILE 	int NOT NULL DEFAULT 0,
	FL_VAL_ONLY_PTS 		int NOT NULL DEFAULT 0,
	FL_PTS_SLS 				int NOT NULL DEFAULT 0,
	FL_ITM_LNK_DEP 			int NOT NULL DEFAULT 0,
	FL_ITM_SLS_TIM 			int NOT NULL DEFAULT 0,
	FL_ITEM_COMB 			int NOT NULL DEFAULT 0,
	RST_SLS_TYP 			int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_ITM, ID_BSN_UN)
   ) 
   
   CREATE TABLE AS_RPSTY_TND
   (
	ID_RPSTY_TND 	int IDENTITY (1, 1) NOT NULL, 
	TY_RPSTY_TND 	VARCHAR(2), 
	NM_RPSTY_TND 	VARCHAR(40), 
	DE_TND_RPSTY 	VARCHAR(255), 
	CD_TND_RPSTY 	VARCHAR(4), 
	ID_BSN_UN 		int NULL,
	PRIMARY KEY (ID_RPSTY_TND)
   )
   
   CREATE TABLE AS_SF
   (	
	ID_RPSTY_TND 	int NOT NULL, 
	DE_SF_STR		VARCHAR(255),
	PRIMARY KEY (ID_RPSTY_TND)
   )
   
   CREATE TABLE AS_TL
   (	
	ID_RPSTY_TND 		int NOT NULL, 
	SC_TL 				VARCHAR(2), 
	TS_STS_TL 			datetime, 
	CP_BLNC_DFLT_OPN 	decimal(14,3) NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_RPSTY_TND)
   )
   
   CREATE TABLE AS_TL_OPR
   (
	ID_RPSTY_TND 	int NOT NULL, 
	ID_OPR 			int NOT NULL,
	PRIMARY KEY (ID_RPSTY_TND, ID_OPR)
   )
   
  CREATE TABLE AS_TL_WS
   (	
	ID_RPSTY_TND 	int NOT NULL, 
	ID_WS 			int NOT NULL,
	PRIMARY KEY (ID_RPSTY_TND, ID_WS)
   ) 
   
  CREATE TABLE AS_TND
   (	
	ID_TND 			int NOT NULL, 
	TY_TND 			VARCHAR(4) NOT NULL, 
	DE_TND 			VARCHAR(255), 
	LU_CLS_TND 		int NULL, 
	FL_TND_DSBL 	bit NULL DEFAULT 0, 
	MDP_SAP 		VARCHAR(4),
	PRIMARY KEY (ID_TND)
   )

  CREATE TABLE AS_WS
   (	
	ID_WS 			int IDENTITY (1, 1) NOT NULL, 
	CD_WS 			VARCHAR(50) NOT NULL, 
	NM_WS 			VARCHAR(100), 
	NM_WS_MF 		VARCHAR(150), 
	NM_MDL_WS_TML 	VARCHAR(150), 
	ID_BSN_UN 		int NULL,
	PRIMARY KEY (ID_WS)
   ) 
   
  CREATE TABLE CERT_STR (
	ID 				int NULL,
	ID_STR_REC_TOT 	int NULL,
	ID_USU 			int NULL,
	ESTADO 			bit NULL,
	ID_TND 			int NULL,
	FCH_CERT 		datetime NULL
   )
   
  CREATE TABLE CO_ALS_ELTNC_CPN_ITM_CD
   (	
	ID_TRN 		int NOT NULL,
	SQN_NMB 	int NOT NULL,
	ITM_CD 		decimal(14,3) NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN, SQN_NMB)
   )
   
 CREATE TABLE CO_ASSC_CPN
   (
	ID_TRN int NOT NULL,
	SQN_NBR int NOT NULL,
	ID_CPN int NOT NULL,
	PRIMARY KEY (ID_TRN, SQN_NBR)
   )

  CREATE TABLE CO_AUT_CPN_DTA
   (	
	ID_TRN 			int NOT NULL,
	MF_CPN_AMT 		decimal(14,3) NOT NULL DEFAULT 0, 
	STR_CPN_AMT 	decimal(14,3) NOT NULL DEFAULT 0, 
	MF_CPN_CNT 		decimal(14,3) NOT NULL DEFAULT 0, 
	STR_CPN_CNT 	decimal(14,3) NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN)
   ) 
   
  CREATE TABLE CO_BNS_RDM_PNTS
   (	
	ID_TRN 		int NOT NULL, 
	SQN_NMB 	int NOT NULL, 
	ITM_CD 		decimal(14,3) NOT NULL DEFAULT 0, 
	VL 			decimal(14,3) NOT NULL DEFAULT 0, 
	MR_FLS 		decimal(14,3) NOT NULL DEFAULT 0, 
	FMY 		decimal(14,3) NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN, SQN_NMB)
   )
   
  CREATE TABLE CO_CNY
   (	
	ID_CNY 		int IDENTITY (1, 1) NOT NULL, 
	DE_CNY 		VARCHAR(255), 
	CD_CY_ISO 	VARCHAR(2), 
	SY_CNY 		VARCHAR(40),
	PRIMARY KEY (ID_CNY)
   )
   
   CREATE TABLE CO_CPN_DT
   (	
	ID_TRN 		int NOT NULL, 
	CPN_ID 		VARCHAR(27) NOT NULL, 
	PRM_ID 		VARCHAR(7), 
	CT_ID 		VARCHAR(16), 
	FRMT_ID 	VARCHAR(5), 
	FL_PRT 		bit NOT NULL DEFAULT 0, 
	ITM_CD 		VARCHAR(14), 
	VL_DSC 		decimal(19,4) NOT NULL DEFAULT 0.00, 
	APLY 		VARCHAR(1), 
	INIT_DT 	datetime, 
	EXP_DT 		datetime, 
	SPRTR 		int NOT NULL DEFAULT 0, 
	LG_ID 		VARCHAR(2), 
	STS 		int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN, CPN_ID)
   ) 
   
 CREATE TABLE CO_CPN_TO_RDM
   (
	ID_CPN 		int IDENTITY (1, 1) NOT NULL,
	CD_CPN 		VARCHAR(25),
	TM_STMP	 	VARCHAR(18),
	STS 		VARCHAR(1),
	BGN_DT 		VARCHAR(8),
	EP_DT 		VARCHAR(8),
	MXM_RDM 	VARCHAR(10),
	NMB_RDM 	VARCHAR(10),
	LS_RDM 		VARCHAR(8),
	PRCNT_OFF 	VARCHAR(3),
	PRIMARY KEY (ID_CPN)
   )
   
  CREATE TABLE CO_CPN_TRCKNG
   (	
	ID_TRN 		int NOT NULL, 
	LOG_FLS 	decimal(14,3) NOT NULL DEFAULT 0, 
	CMPGN_NMB 	decimal(14,3) NOT NULL DEFAULT 0, 
	MFG_NMB 	decimal(14,3) NOT NULL DEFAULT 0, 
	PRM_CD 		decimal(14,3) NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE CO_CPR_CER
   (	
	ID_CPR 		bigint NOT NULL, 
	CD_CPR 		VARCHAR(20), 
	TY_CPR 		VARCHAR(1), 
	RG_INT 		int NOT NULL DEFAULT 0, 
	NOMBRE 		VARCHAR(250), 
	DIRECCION 	VARCHAR(250), 
	COD_CIUDAD 	int NULL, 
	TELEFONO 	VARCHAR(20), 
	CORREO 		VARCHAR(250),
	COD_REGION  int NULL DEFAULT 0,
	GENERO 		VARCHAR(10),
	PRIMARY KEY (ID_CPR)
   )
   CREATE INDEX CO_CPR_CER_ID_IDX ON CO_CPR_CER (ID_CPR)
   
   CREATE INDEX CO_CPR_CER_CD_IDX ON CO_CPR_CER (CD_CPR)
        
  CREATE TABLE CO_EPS_LOG 
   (	
    ID_EPS_LOG 		int IDENTITY (1, 1) NOT NULL, 
	CD_STR_RT 		int NOT NULL,
	EXECUTION_DATE 	datetime, 
	BUSINESS_DATE 	datetime, 
	HEADER 			NVARCHAR(33),
	DATA 			NVARCHAR(479), 
	PRIMARY KEY (ID_EPS_LOG)
   )
   
  CREATE UNIQUE INDEX XPKFP_EPS_LOG ON CO_EPS_LOG (ID_EPS_LOG)
  
  CREATE TABLE CO_EXT_CER
   (	
	ID_CPR 			int IDENTITY (1, 1) NOT NULL, 
	CD_CPR 			VARCHAR(50), 
	NOMBRE 			VARCHAR(250), 
	DIRECCION 		VARCHAR(250), 
	TELEFONO 		VARCHAR(20), 
	CORREO 			VARCHAR(250), 
	NACIONALIDAD 	VARCHAR(50),
	PRIMARY KEY (ID_CPR)
   )
   
 CREATE TABLE CO_FLAG_PROCES 
   (	
    FLAG_PROCESAMIENTO 	VARCHAR(4), 
	DES_PROCES 			VARCHAR(200),
	PRIMARY KEY (FLAG_PROCESAMIENTO)
   )
   
   CREATE TABLE CO_GASTO_COD(
	CD_GASTO char(6) NULL,
	NM_CUENTA varchar(200) NULL,
	BR_CUENTA varchar(50) NULL,
	CD_CUENTA char(5) NULL,
	FL_GAS int NULL,
	FL_CANT int NULL,
	CD_SAP int NULL
	)
	
 CREATE TABLE CO_GASTO_EFE_CER
   (
    ID_TRN 		int NOT NULL,
	CED 		VARCHAR(10),
	ALM 		VARCHAR(20),
	FECHA 		VARCHAR(10),
	COMP 		VARCHAR(6),
	SECCION 	VARCHAR(30),
	COD 		VARCHAR(6),
	TIPO 		VARCHAR(2),
	CANT 		VARCHAR(3),
	VALOR 		int NULL,
	OBS 		VARCHAR(30),
	PRIMARY KEY (ID_TRN)
   )
   
   CREATE TABLE [dbo].[CO_LOST_DTND](
	[ID_TRN] [int] NOT NULL,
	[ID_TND] [int] NOT NULL,
	[AI_LN_ITM] [int] NOT NULL,
	[TY_TND] [int] NULL
   )

   CREATE TABLE CO_LTM_RTN
   (
    ID_TRN 		int NOT NULL,
	AI_LN_ITM 	int NULL,
	RTN_NMB 	VARCHAR(20),
	PRIMARY KEY (ID_TRN)
   )
   
    CREATE TABLE CO_GERENTE_CER
   (
    ID_GERENTE 		int NOT NULL,
	TIENDA 			VARCHAR(10),
	NOMBRE 			VARCHAR(20),
	PRIMARY KEY (ID_GERENTE)
   )
   
   CREATE TABLE CO_GASTO_TIPO(
	CD_GASTO char(6) NULL,
	CD_TIPO char(2) NULL,
	NM_TIPO varchar(200) NULL,
	BR_TIPO varchar(50) NULL,
	FL_PROV int NULL
	)
   
  CREATE TABLE CO_MOTO_CER
   (	
	ID_MOTO 		int IDENTITY (1, 1) NOT NULL, 
	SRL_NBR 		VARCHAR(20), 
	CHASIS 			VARCHAR(20), 
	ANO_MOD 		VARCHAR(4), 
	CLASE 			VARCHAR(15), 
	COLOR 			VARCHAR(15), 
	CILINDRAJE 		VARCHAR(10), 
	CAPACIDAD 		VARCHAR(3), 
	CPN 			VARCHAR(20), 
	GRAVAMEN 		VARCHAR(1), 
	SUBCATEGORIA 	VARCHAR(10), 
	COMBUSTIBLE 	VARCHAR(15), 
	CARROCERIA 		VARCHAR(15), 
	CKD 			VARCHAR(20), 
	MARCA 			VARCHAR(20), 
	MODELO 			VARCHAR(18), 
	PAIS_ORIG 		VARCHAR(20), 
	TONELAJE 		VARCHAR(20), 
	MANDANTE 		VARCHAR(3), 
	MATERIAL 		VARCHAR(18), 
	MOTOR 			VARCHAR(20), 
	NUM_SRI 		VARCHAR(20), 
	FECHA_CPN 		VARCHAR(8), 
	CENTRO 			VARCHAR(4), 
	STATUS 			VARCHAR(1),
	EJES 			VARCHAR(1) DEFAULT '2',
	RUEDAS 			VARCHAR(1) DEFAULT '2',
	ID_ITM			int NULL,
	PRIMARY KEY (ID_MOTO)
   )
   
  CREATE TABLE CO_MRHRC_GP
   (	
	ID_MRHRC_GP 	int IDENTITY (1, 1) NOT NULL,
	CD_MRHRC_GP 	int NOT NULL DEFAULT 0,
	NM_MRHRC_GP 	VARCHAR(50), 
	DE_MRHRC_GP 	VARCHAR(255), 
	ID_DPT_PS 		int NULL,
	CD_MRHRC_CER 	VARCHAR(6),
	PORC_REC 		int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_MRHRC_GP)
   )

  CREATE TABLE CO_PAD_CER
   (	
	ID_CPR 		int NOT NULL, 
	CD_CPR 		VARCHAR(20), 
	RECINTO 	VARCHAR(80), 
	MESA 		VARCHAR(4), 
	JUNTA 		VARCHAR(1), 
	FUNCION 	VARCHAR(75), 
	DIRECCION 	VARCHAR(250),
	PRIMARY KEY (ID_CPR)
   )
   
   CREATE TABLE CO_PORTA_FERR
   (	
    ID_CPR int not null, 
	CD_CPR VARCHAR(20), 
	CTA_ACRE VARCHAR(20),
	PRIMARY KEY (ID_CPR)
   )

  CREATE TABLE CO_PRFRD_CT_DT
   (	
	ID_TRN 			int NOT NULL, 
	CTAC_ID 		VARCHAR(18), 
	PNTS 			decimal(14,3) NOT NULL DEFAULT 0, 
	CPN_AMT 		decimal(14,3) NOT NULL DEFAULT 0, 
	CPN_CNT 		decimal(14,3) NOT NULL DEFAULT 0, 
	MSG_CNT 		decimal(14,3) NOT NULL DEFAULT 0, 
	TSFRD_TR_CNT 	decimal(14,3) NOT NULL DEFAULT 0, 
	TSFRD_TR_AMT 	decimal(14,3) NOT NULL DEFAULT 0, 
	BNS_PNT 		decimal(14,3) NOT NULL DEFAULT 0, 
	RDM_PNT 		decimal(14,3) NOT NULL DEFAULT 0, 
	ENR_MTH 		decimal(14,3) NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE CO_PRFRD_CT_SCN_PNT_DT
   (	
	ID_TRN 		int NOT NULL, 
	CLB_NMB 	decimal(14,3) NOT NULL DEFAULT 0, 
	PNT 		decimal(14,3) NOT NULL DEFAULT 0, 
	RDM_PNT 	decimal(14,3) NOT NULL DEFAULT 0, 
	BNS_PNT 	decimal(14,3) NOT NULL DEFAULT 0, 
	SLS 		decimal(14,3) NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN)
   )
   
  CREATE TABLE CO_RDM_CPN_DT
   (	
	ID_TRN 		int NOT NULL, 
	CPN_ID 		VARCHAR(27) NOT NULL, 
	VL_DSC 		decimal(19,4) NOT NULL DEFAULT 0.00, 
	TM_STP 		VARCHAR(10), 
	TRN_NMB 	int NULL, 
	WS 			VARCHAR(4), 
	STR 		VARCHAR(4),
	PRIMARY KEY (ID_TRN, CPN_ID)
   )

  CREATE TABLE CO_REL_CER
   (	
	ID_CPR 				bigint NOT NULL, 
	PROVINCIA 			VARCHAR(25), 
	CANTON 				VARCHAR(25), 
	PARROQUIA 			VARCHAR(30), 
	ZONA 				VARCHAR(40), 
	RECINTO 			VARCHAR(80), 
	MESA 				VARCHAR(250), 
	JUNTA 				VARCHAR(5), 
	CIRCUNSCRIPCION 	VARCHAR(75),
	FUNCION	 			VARCHAR(250),
	GENERO				VARCHAR(10),
	PRIMARY KEY (ID_CPR)
   )
   
   CREATE TABLE CO_GFTCRD_DT (
	ID_TRN 			int NOT NULL,
	AI_LN_ITM  		int NOT NULL,
	TM				VARCHAR(6) NULL,
	CRD_NBR			VARCHAR(16) NULL,
	AMNT			int NULL,
	REF_NBR			VARCHAR(6) NULL,
	AUT_NBR			VARCHAR(6) NULL,
	RSP_CD			VARCHAR(2) NULL,
	STS				int NULL,
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )
   
   CREATE TABLE CO_ILIM_DT (
	ID_TRN 			int NOT NULL,
	AI_LN_ITM  		int NOT NULL,
	TM				VARCHAR(6) NULL,
	AMNT			int NULL,
	REF_NBR			VARCHAR(6) NULL,
	TML_ID			VARCHAR(8) NULL,
	MRCHNT_ID		VARCHAR(15) NULL,
	AUT_NBR			VARCHAR(6) NULL,
	ILIM_DT			VARCHAR(199) NULL,
	FL_VD			int NULL,
	PRIMARY KEY (ID_TRN,AI_LN_ITM)
   )
   
   CREATE TABLE CO_PTS_RDM_DT (
	ID_TRN 			int NOT NULL,
	AI_LN_ITM  		int NOT NULL,
	TM				VARCHAR(6) NULL,
	DSC				int NULL,
	CD_NGC			VARCHAR(1) NULL,
	REF_NBR			VARCHAR(6) NULL,
	AUT_NBR			VARCHAR(6) NULL,
	TYP				VARCHAR(1) NULL,
	BIN				VARCHAR(16) NULL,
	PTS 			int NULL,
	CD_ITM			bigint NOT NULL,
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )
	  
  CREATE TABLE CO_RTNC_CER 
   (
	ID_TRN 			int NOT NULL,
	AI_LN_ITM  		int NOT NULL,
	INDICADOR  		int NOT NULL,
	TERMINAL 		VARCHAR(4),
	TIQUETE 		VARCHAR(15),
	FECHA 			VARCHAR(8),
	VOUCHER 		VARCHAR(15),
	NUMERO_SRI 		VARCHAR(50),
	MONTO 			int NULL,
	BASE_IMP 		VARCHAR(20),
	PORCENTAJE 		int NULL,
	CLNT_ID 		VARCHAR(13),
	CLNT_NM 		VARCHAR(60),
	TIPO_PAG		int NULL,
	TIPO 			int NULL,
	TY_TND			VARCHAR(4),
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )
   
   CREATE TABLE [dbo].[CO_RTNC_TY](
	[ID_TY_RTNC] [int] IDENTITY(1,1) NOT NULL,
	[DES_TY_RTNC] [varchar](200) NULL,
	PRIMARY KEY (ID_TY_RTNC)
   )

  CREATE TABLE CO_SOCIEDAD_CER
   (	
	COD_SOC 		int IDENTITY (1, 1) NOT NULL, 
	CLAVE_CONT 		VARCHAR(2),
	PRIMARY KEY (COD_SOC)
   )
	  
  CREATE TABLE CO_STR_USU_CER 
   (
	ID_TRN 			int NOT NULL,
	AI_LN_ITM  		int NOT NULL,
	STRING 		VARCHAR(300),
	PRIMARY KEY (ID_TRN,AI_LN_ITM)
   )
   
   CREATE TABLE CO_TY_DIF 
   (
	ID_TY_DIF 		int NOT NULL,
	COD_DIF  		VARCHAR(2),
	HOST 			VARCHAR(3),
	DES_DIF			VARCHAR(100),
	PRIMARY KEY (ID_TY_DIF)
   )

  CREATE TABLE CO_TY_TX
   (	
	ID_TY_TX 	int IDENTITY (1, 1) NOT NULL, 
	TY_TX 		VARCHAR(4) NOT NULL, 
	PE_TX 		int NOT NULL,
	PRIMARY KEY (ID_TY_TX)
   )

  CREATE TABLE CO_USED_TGTD_CPNS
   (	
	ID_TRN 		int NOT NULL, 
	CTAC_ID 	decimal(14,3) NOT NULL DEFAULT 0, 
	TGTD_CPN 	decimal(14,3) NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN)
   )
   
  CREATE TABLE CO_VALE_EMP_CER
   (
	ID_TRN 		int NOT NULL,
	CED 		VARCHAR(10),
	COD_SOC_SAP     VARCHAR(2),
	COMP 		VARCHAR(6),
	COD 		VARCHAR(4),
	CUOTAS 		VARCHAR(3),
	VALOR 		int null,
	OBS 		VARCHAR(30),
	PRIMARY KEY (ID_TRN)
   )
   
   CREATE TABLE [dbo].[CO_VALE_EMP_COD](
	[ID_COD] [int] IDENTITY(1,1) NOT NULL,
	[CD_COD] [int] NULL,
	[NM_COD] [varchar](200) NULL,
	PRIMARY KEY (ID_COD)
   )
   
	CREATE TABLE CO_RESERVA
   (	
	ID_RSV				int IDENTITY (1, 1) NOT NULL,
	ID_ITM				int NOT NULL,
	ID_BSN_UN 			int NOT NULL, 
	CD_RSV 				int NOT NULL, 
	FECHA_DSD 			datetime, 
	FECHA_HST			datetime, 
	NUM_SERIE			[varchar](20) NULL,
	FL_RSV_USED			bit NULL DEFAULT 0, 
	
	PRIMARY KEY (ID_RSV, ID_ITM, ID_BSN_UN)
   )

   

  CREATE TABLE EXCPTN_LOG
   (	
	ID_TRN 		int NOT NULL, 
	SQN_NBR 	int NOT NULL, 
	LOG_DATA 	VARCHAR(30),
	PRIMARY KEY (ID_TRN, SQN_NBR)
   )
   
  CREATE TABLE ID_DPT_PS
   (	
	ID_DPT_PS 		int IDENTITY (1, 1) NOT NULL,
	NM_DPT_PS 		VARCHAR(50), 
	CD_DPT_CER 		VARCHAR(6), 
	COD_NEGOCIO 	int NOT NULL DEFAULT 0,
	PORC_REC		int NOT NULL DEFAULT 0,
	PORC_DESEMP 	int NOT NULL DEFAULT 0,
	PORC_BOSOL 		int NOT NULL DEFAULT 0,
	QTY_MRHRC_GP    int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_DPT_PS)
   )

  CREATE TABLE ID_PS
   (	
	ID_ITM_PS 	bigint NOT NULL, 
	ID_ITM 		int NOT NULL,
	ID_BSN_UN 		int NOT NULL,
	PRTY	VARCHAR(6), 
	PRIMARY KEY (ID_ITM_PS, ID_ITM, ID_BSN_UN)
   )
   
  CREATE TABLE LE_STR_REC_TOT
  (
  	ID_STR_REC_TOT			int IDENTITY (1, 1) NOT NULL, 
  	REC_TYP					VARCHAR(1) NOT NULL,
  	STR_CD					int NOT NULL,
  	STR_ID					int NOT NULL,
  	TM_STP					DATETIME NOT NULL,
  	LS_TML					int NULL,
  	RESRT					int NULL,
  	GS_PLS					int NOT NULL,
  	GS_MNS					int NOT NULL,
  	SLS_TRN_CNT				int NOT NULL,
  	LON_TND_AMT_CSH			int NOT NULL,
  	LON_TND_AMT_CHK			int NOT NULL,
  	LON_TND_AMT_FDS			int NOT NULL,
  	LON_TND_AMT_MSC1		int NOT NULL,
  	LON_TND_AMT_MSC2		int NOT NULL,
  	LON_TND_AMT_MSC3		int NOT NULL,
  	LON_TND_AMT_MF_CPN		int NOT NULL,
  	LON_TND_AMT_STR_CPN		int NOT NULL,
  	PKP_TND_AMT_CSH			int NOT NULL,
  	PKP_TND_AMT_CHK			int NOT NULL,
  	PKP_TND_AMT_FDS			int NOT NULL,
  	PKP_TND_AMT_MSC1		int NOT NULL,
  	PKP_TND_AMT_MSC2		int NOT NULL,
  	PKP_TND_AMT_MSC3		int NOT NULL,
  	PKP_TND_AMT_MF_CPN		int NOT NULL,
  	PKP_TND_AMT_STR_CPN		int NOT NULL,
  	CNTD_TND_AMT_CSH		int NOT NULL,
  	CNTD_TND_AMT_CHK		int NOT NULL,
  	CNTD_TND_AMT_FDS		int NOT NULL,
  	CNTD_TND_AMT_MSC1		int NOT NULL,
  	CNTD_TND_AMT_MSC2		int NOT NULL,
  	CNTD_TND_AMT_MSC3		int NOT NULL,
  	CNTD_TND_AMT_MF_CPN		int NOT NULL,
  	CNTD_TND_AMT_STR_CPN	int NOT NULL,
  	NT_TND_AMT_CSH			int NOT NULL,
  	NT_TND_AMT_CHK			int NOT NULL,
  	NT_TND_AMT_FDS			int NOT NULL,
  	NT_TND_AMT_MSC1			int NOT NULL,
  	NT_TND_AMT_MSC2			int NOT NULL,
  	NT_TND_AMT_MSC3			int NOT NULL,
  	NT_TND_AMT_MF_CPN		int NOT NULL,
  	NT_TND_AMT_STR_CPN		int NOT NULL,
  	OPN_TND_AMT_CSH			int NOT NULL,
  	OPN_TND_AMT_CHK			int NOT NULL,
  	OPN_TND_AMT_FDS			int NOT NULL,
  	OPN_TND_AMT_MSC1		int NOT NULL,
  	OPN_TND_AMT_MSC2		int NOT NULL,
  	OPN_TND_AMT_MSC3		int NOT NULL,
  	OPN_TND_AMT_MF_CPN		int NOT NULL,
  	OPN_TND_AMT_STR_CPN		int NOT NULL,
  	MSC_TRN_AMT				int NOT NULL,
  	PRD_TM_STP				DATETIME NOT NULL,
  	TXBL_EXM_AMT			int NOT NULL,
  	TX_EXM_AMT_A			int NOT NULL,
  	TX_EXM_AMT_B			int NOT NULL,
  	TX_EXM_AMT_C			int NOT NULL,
  	TX_EXM_AMT_D			int NOT NULL,
  	TXBL_EXM_AMT_A			int NOT NULL,
  	TXBL_EXM_AMT_B			int NOT NULL,
  	TXBL_EXM_AMT_C			int NOT NULL,
  	TXBL_EXM_AMT_D			int NOT NULL,
  	TX_EXM_AMT_E			int NOT NULL,
  	TX_EXM_AMT_F			int NOT NULL,
  	TX_EXM_AMT_G			int NOT NULL,
  	TX_EXM_AMT_H			int NOT NULL,
  	TXBL_EXM_AMT_E			int NOT NULL,
  	TXBL_EXM_AMT_F			int NOT NULL,
  	TXBL_EXM_AMT_G			int NOT NULL,
  	TXBL_EXM_AMT_H			int NOT NULL,
  	MF_AUT_CPN_AMT			int NOT NULL,
  	STR_AUT_CPN_AMT			int NOT NULL,
  	DBLD_CPN_AMT			int NOT NULL,
  	PC_TRN_AMT				int NOT NULL,
  	PC_TRN_CNT				int NOT NULL,
  	PC_AUT_CPN_CNT			int NOT NULL,
  	PC_AUT_CPN_AMT			int NOT NULL,
  	FL_RCLD					int NOT NULL,
  	FL_PRNTD				int NOT NULL,
  	PRD_TYP					VARCHAR(1),
  	PRIMARY KEY (ID_STR_REC_TOT)
  )
  
  CREATE TABLE LE_IND_REC_TOT
  (
  	ID_IND_REC_TOT			int IDENTITY (1, 1) NOT NULL, 
  	REC_TYP					VARCHAR(1) NOT NULL,
  	STR_CD					int NOT NULL,
  	ACNT_ID					int NOT NULL,
  	STR_TM_STP				DATETIME NOT NULL,
  	TM_STP					DATETIME NOT NULL,
  	TRN_NMB					int NULL,
  	RESRT					int NULL,
  	GS_PLS					int NOT NULL,
  	GS_MNS					int NOT NULL,
  	SLS_TRN_CNT				int NOT NULL,
  	LON_TND_AMT_CSH			int NOT NULL,
  	LON_TND_AMT_CHK			int NOT NULL,
  	LON_TND_AMT_FDS			int NOT NULL,
  	LON_TND_AMT_MSC1		int NOT NULL,
  	LON_TND_AMT_MSC2		int NOT NULL,
  	LON_TND_AMT_MSC3		int NOT NULL,
  	LON_TND_AMT_MF_CPN		int NOT NULL,
  	LON_TND_AMT_STR_CPN		int NOT NULL,
  	PKP_TND_AMT_CSH			int NOT NULL,
  	PKP_TND_AMT_CHK			int NOT NULL,
  	PKP_TND_AMT_FDS			int NOT NULL,
  	PKP_TND_AMT_MSC1		int NOT NULL,
  	PKP_TND_AMT_MSC2		int NOT NULL,
  	PKP_TND_AMT_MSC3		int NOT NULL,
  	PKP_TND_AMT_MF_CPN		int NOT NULL,
  	PKP_TND_AMT_STR_CPN		int NOT NULL,
  	CNTD_TND_AMT_CSH		int NOT NULL,
  	CNTD_TND_AMT_CHK		int NOT NULL,
  	CNTD_TND_AMT_FDS		int NOT NULL,
  	CNTD_TND_AMT_MSC1		int NOT NULL,
  	CNTD_TND_AMT_MSC2		int NOT NULL,
  	CNTD_TND_AMT_MSC3		int NOT NULL,
  	CNTD_TND_AMT_MF_CPN		int NOT NULL,
  	CNTD_TND_AMT_STR_CPN	int NOT NULL,
  	NT_TND_AMT_CSH			int NOT NULL,
  	NT_TND_AMT_CHK			int NOT NULL,
  	NT_TND_AMT_FDS			int NOT NULL,
  	NT_TND_AMT_MSC1			int NOT NULL,
  	NT_TND_AMT_MSC2			int NOT NULL,
  	NT_TND_AMT_MSC3			int NOT NULL,
  	NT_TND_AMT_MF_CPN		int NOT NULL,
  	NT_TND_AMT_STR_CPN		int NOT NULL,
  	ITM_SLS_AMT				int NOT NULL,
  	DS_AMT					int NOT NULL,
  	RFD_AMT					int NOT NULL,
  	DS_RTN_AMT				int NOT NULL,
  	MSC_RCPT_AMT			int NOT NULL,
  	MSC_PYOT_AMT			int NOT NULL,
  	DSC_AMT					int NOT NULL,
  	TXBL_AMT_EXM			int NOT NULL,
  	ITM_CNCL_AMT			int NOT NULL,
  	DS_CNCL_AMT				int NOT NULL,
  	CR_TRN_AMT				int NOT NULL,
  	TND_FE_AMT				int NOT NULL,
  	MSC_TRN_AMT				int NOT NULL,
  	TND_CSH_AMT				int NOT NULL,
  	TND_EXC_AMT				int NOT NULL,
  	TXBL_AMT_A				int NOT NULL,
  	TX_AMT_A				int NOT NULL,
  	TXBL_AMT_B				int NOT NULL,
  	TX_AMT_B				int NOT NULL,
  	TXBL_AMT_C				int NOT NULL,
  	TX_AMT_C				int NOT NULL,
  	TXBL_AMT_D				int NOT NULL,
  	TX_AMT_D				int NOT NULL,
	STD_ALN_GS_PLS			int NOT NULL,
	STD_ALN_GS_MNS			int NOT NULL,
  	VD_TRN_AMT				int NOT NULL,
  	TRG_TRN_AMT				int NOT NULL,
  	ITM_SLS_CNT				int NOT NULL,
  	ITM_SLS_KY_CNT			int NOT NULL,
  	ITM_SLS_LKP_KY_CNT		int NOT NULL,
  	TRDG_STP				int NOT NULL,
  	DS_CNT					int NOT NULL,
  	RFD_CNT					int NOT NULL,
  	DS_RTN_CNT				int NOT NULL,
  	MSC_RCPT_CNT			int NOT NULL,
  	MSC_PYOT_CNT			int NOT NULL,
  	DSC_CNT					int NOT NULL,
  	TX_EXM_CNT				int NOT NULL,
  	ITM_CNCL_CNT			int NOT NULL,
  	DS_CNCL_CNT				int NOT NULL,
  	CR_TRN_CNT				int NOT NULL,
  	SPL_SGN_OFF_CNT			int NOT NULL,
  	NO_SLS_TRN_CNT			int NOT NULL,
  	NT_TND_NMB_CSH			int NOT NULL,
  	NT_TND_NMB_CHK			int NOT NULL,
  	NT_TND_NMB_FDS			int NOT NULL,
  	NT_TND_NMB_MSC1			int NOT NULL,
  	NT_TND_NMB_MSC2			int NOT NULL,
  	NT_TND_NMB_MSC3			int NOT NULL,
  	NT_TND_NMB_MF_CPN		int NOT NULL,
  	NT_TND_NMB_STR_CPN		int NOT NULL,
  	LO_CNT					int NOT NULL,
  	PKP_CNT					int NOT NULL,
  	STD_ALN_TRN_CNT			int NOT NULL,
  	VD_TRN_CNT				int NOT NULL,
  	TRG_TRN_CNT				int NOT NULL,
  	STD_ALN_TX_AMT			int NOT NULL,
  	TXBL_AMT_E				int NOT NULL,
  	TX_AMT_E				int NOT NULL,
  	TXBL_AMT_F				int NOT NULL,
  	TX_AMT_F				int NOT NULL,
  	TXBL_AMT_G				int NOT NULL,
  	TX_AMT_G				int NOT NULL,
  	TXBL_AMT_H				int NOT NULL,
  	TX_AMT_H				int NOT NULL,
  	SLS_PNT					int NOT NULL,
  	BNS_PNT					int NOT NULL,
  	RDM_PNT					int NOT NULL,
  	MF_AUT_CPN_AMT			int NOT NULL,
  	STR_AUT_CPN_AMT			int NOT NULL,
  	DBLD_CPN_AMT			int NOT NULL,
  	PC_TRN_AMT				int NOT NULL,
  	PC_TRN_CNT				int NOT NULL,
  	PC_AUT_CPN_CNT			int NOT NULL,
  	PC_AUT_CPN_AMT			int NOT NULL,
  	CPN_TR_AMT_1			int NOT NULL,
  	CPN_TR_AMT_2			int NOT NULL,
  	CPN_TR_AMT_3			int NOT NULL,
  	CPN_TR_AMT_4			int NOT NULL,
  	CPN_TR_AMT_5			int NOT NULL,
  	CPN_TR_AMT_6			int NOT NULL,
  	CPN_CNT_1				int NOT NULL,
  	CPN_CNT_2				int NOT NULL,
  	CPN_CNT_3				int NOT NULL,
  	CPN_CNT_4				int NOT NULL,
  	CPN_CNT_5				int NOT NULL,
  	CPN_CNT_6				int NOT NULL,
  	PRD_TYP					VARCHAR(1),
  	PRIMARY KEY (ID_IND_REC_TOT)
  )
  

  CREATE TABLE LE_TND_REC_TOT
  (
  	ID_TND_REC_TOT			int IDENTITY (1, 1) NOT NULL, 
  	REC_TYP					VARCHAR(1) NOT NULL,
  	STR_CD					int NOT NULL,
  	ACNT_ID					int NOT NULL,
  	TM_STP					DATETIME NOT NULL,
  	RESRT					VARCHAR(8) NULL,
  	TND_AMT_CSH_1			int NOT NULL,
  	TND_AMT_CSH_2			int NOT NULL,
  	TND_AMT_CSH_3			int NOT NULL,
  	TND_AMT_CSH_4			int NOT NULL,
  	TND_AMT_CSH_5			int NOT NULL,
  	TND_AMT_CSH_6			int NOT NULL,
  	TND_AMT_CHK_1			int NOT NULL,
  	TND_AMT_CHK_2			int NOT NULL,
  	TND_AMT_CHK_3			int NOT NULL,
  	TND_AMT_CHK_4			int NOT NULL,
  	TND_AMT_CHK_5			int NOT NULL,
  	TND_AMT_CHK_6			int NOT NULL,
  	TND_AMT_FDS_1			int NOT NULL,
  	TND_AMT_FDS_2			int NOT NULL,
  	TND_AMT_FDS_3			int NOT NULL,
  	TND_AMT_FDS_4			int NOT NULL,
  	TND_AMT_FDS_5			int NOT NULL,
  	TND_AMT_FDS_6			int NOT NULL,
  	TND_AMT_MSC1_1			int NOT NULL,
  	TND_AMT_MSC1_2			int NOT NULL,
  	TND_AMT_MSC1_3			int NOT NULL,
  	TND_AMT_MSC1_4			int NOT NULL,
  	TND_AMT_MSC1_5			int NOT NULL,
  	TND_AMT_MSC1_6			int NOT NULL,
  	TND_AMT_MSC2_1			int NOT NULL,
  	TND_AMT_MSC2_2			int NOT NULL,
  	TND_AMT_MSC2_3			int NOT NULL,
  	TND_AMT_MSC2_4			int NOT NULL,
  	TND_AMT_MSC2_5			int NOT NULL,
  	TND_AMT_MSC2_6			int NOT NULL,
  	TND_AMT_MSC3_1			int NOT NULL,
  	TND_AMT_MSC3_2			int NOT NULL,
  	TND_AMT_MSC3_3			int NOT NULL,
  	TND_AMT_MSC3_4			int NOT NULL,
  	TND_AMT_MSC3_5			int NOT NULL,
  	TND_AMT_MSC3_6			int NOT NULL,
  	TND_AMT_MF_CPN_1		int NOT NULL,
  	TND_AMT_MF_CPN_2		int NOT NULL,
  	TND_AMT_MF_CPN_3		int NOT NULL,
  	TND_AMT_MF_CPN_4		int NOT NULL,
  	TND_AMT_MF_CPN_5		int NOT NULL,
  	TND_AMT_MF_CPN_6		int NOT NULL,
  	TND_AMT_STR_CPN_1		int NOT NULL,
  	TND_AMT_STR_CPN_2		int NOT NULL,
  	TND_AMT_STR_CPN_3		int NOT NULL,
  	TND_AMT_STR_CPN_4		int NOT NULL,
  	TND_AMT_STR_CPN_5		int NOT NULL,
  	TND_AMT_STR_CPN_6		int NOT NULL,
  	TND_CNT_CSH_1			int NOT NULL,
  	TND_CNT_CSH_2			int NOT NULL,
  	TND_CNT_CSH_3			int NOT NULL,
  	TND_CNT_CSH_4			int NOT NULL,
  	TND_CNT_CSH_5			int NOT NULL,
  	TND_CNT_CSH_6			int NOT NULL,
  	TND_CNT_CHK_1			int NOT NULL,
  	TND_CNT_CHK_2			int NOT NULL,
  	TND_CNT_CHK_3			int NOT NULL,
  	TND_CNT_CHK_4			int NOT NULL,
  	TND_CNT_CHK_5			int NOT NULL,
  	TND_CNT_CHK_6			int NOT NULL,
  	TND_CNT_FDS_1			int NOT NULL,
  	TND_CNT_FDS_2			int NOT NULL,
  	TND_CNT_FDS_3			int NOT NULL,
  	TND_CNT_FDS_4			int NOT NULL,
  	TND_CNT_FDS_5			int NOT NULL,
  	TND_CNT_FDS_6			int NOT NULL,
  	TND_CNT_MSC1_1			int NOT NULL,
  	TND_CNT_MSC1_2			int NOT NULL,
  	TND_CNT_MSC1_3			int NOT NULL,
  	TND_CNT_MSC1_4			int NOT NULL,
  	TND_CNT_MSC1_5			int NOT NULL,
  	TND_CNT_MSC1_6			int NOT NULL,
  	TND_CNT_MSC2_1			int NOT NULL,
  	TND_CNT_MSC2_2			int NOT NULL,
  	TND_CNT_MSC2_3			int NOT NULL,
  	TND_CNT_MSC2_4			int NOT NULL,
  	TND_CNT_MSC2_5			int NOT NULL,
  	TND_CNT_MSC2_6			int NOT NULL,
  	TND_CNT_MSC3_1			int NOT NULL,
  	TND_CNT_MSC3_2			int NOT NULL,
  	TND_CNT_MSC3_3			int NOT NULL,
  	TND_CNT_MSC3_4			int NOT NULL,
  	TND_CNT_MSC3_5			int NOT NULL,
  	TND_CNT_MSC3_6			int NOT NULL,
  	TND_CNT_MF_CPN_1		int NOT NULL,
  	TND_CNT_MF_CPN_2		int NOT NULL,
  	TND_CNT_MF_CPN_3		int NOT NULL,
  	TND_CNT_MF_CPN_4		int NOT NULL,
  	TND_CNT_MF_CPN_5		int NOT NULL,
  	TND_CNT_MF_CPN_6		int NOT NULL,
  	TND_CNT_STR_CPN_1		int NOT NULL,
  	TND_CNT_STR_CPN_2		int NOT NULL,
  	TND_CNT_STR_CPN_3		int NOT NULL,
  	TND_CNT_STR_CPN_4		int NOT NULL,
  	TND_CNT_STR_CPN_5		int NOT NULL,
  	TND_CNT_STR_CPN_6		int NOT NULL,
  	TND_AMT_CSH_7			int NOT NULL,
  	TND_AMT_CSH_8			int NOT NULL,
  	TND_AMT_CSH_9			int NOT NULL,
  	TND_AMT_CHK_7			int NOT NULL,
  	TND_AMT_CHK_8			int NOT NULL,
  	TND_AMT_CHK_9			int NOT NULL,
  	TND_AMT_FDS_7			int NOT NULL,
  	TND_AMT_FDS_8			int NOT NULL,
  	TND_AMT_FDS_9			int NOT NULL,
  	TND_AMT_MSC1_7			int NOT NULL,
  	TND_AMT_MSC1_8			int NOT NULL,
  	TND_AMT_MSC1_9			int NOT NULL,
  	TND_AMT_MSC2_7			int NOT NULL,
  	TND_AMT_MSC2_8			int NOT NULL,
  	TND_AMT_MSC2_9			int NOT NULL,
  	TND_AMT_MSC3_7			int NOT NULL,
  	TND_AMT_MSC3_8			int NOT NULL,
  	TND_AMT_MSC3_9			int NOT NULL,
  	TND_AMT_MF_CPN_7		int NOT NULL,
  	TND_AMT_MF_CPN_8		int NOT NULL,
  	TND_AMT_MF_CPN_9		int NOT NULL,
  	TND_AMT_STR_CPN_7		int NOT NULL,
  	TND_AMT_STR_CPN_8		int NOT NULL,
  	TND_AMT_STR_CPN_9		int NOT NULL,
  	TND_CNT_CSH_7			int NOT NULL,
  	TND_CNT_CSH_8			int NOT NULL,
  	TND_CNT_CSH_9			int NOT NULL,
  	TND_CNT_CHK_7			int NOT NULL,
  	TND_CNT_CHK_8			int NOT NULL,
  	TND_CNT_CHK_9			int NOT NULL,
  	TND_CNT_FDS_7			int NOT NULL,
  	TND_CNT_FDS_8			int NOT NULL,
  	TND_CNT_FDS_9			int NOT NULL,
  	TND_CNT_MSC1_7			int NOT NULL,
  	TND_CNT_MSC1_8			int NOT NULL,
  	TND_CNT_MSC1_9			int NOT NULL,
  	TND_CNT_MSC2_7			int NOT NULL,
  	TND_CNT_MSC2_8			int NOT NULL,
  	TND_CNT_MSC2_9			int NOT NULL,
  	TND_CNT_MSC3_7			int NOT NULL,
  	TND_CNT_MSC3_8			int NOT NULL,
  	TND_CNT_MSC3_9			int NOT NULL,
  	TND_CNT_MF_CPN_7		int NOT NULL,
  	TND_CNT_MF_CPN_8		int NOT NULL,
  	TND_CNT_MF_CPN_9		int NOT NULL,
  	TND_CNT_STR_CPN_7		int NOT NULL,
  	TND_CNT_STR_CPN_8		int NOT NULL,
  	TND_CNT_STR_CPN_9		int NOT NULL,
  	PRD_TYP					VARCHAR(1),
  	PRIMARY KEY (ID_TND_REC_TOT)
  )
	  
  CREATE TABLE LO_EXTDST
   (	
	ID_RPSTY_TND 		int NOT NULL, 
	FL_ENBL 			bit NOT NULL DEFAULT 1, 
	NM_RPSTY_EXTRN 		VARCHAR(40), 
	DE_RPSTY_EXTRN 		VARCHAR(255), 
	ID_EXTDST 			int NULL, 
	ID_ACNT_DS 			int NULL,
	PRIMARY KEY (ID_RPSTY_TND)
   )

  CREATE TABLE MGR_OVRD
   (	
	ID_TRN 		int NOT NULL, 
	SQN_NBR		int NOT NULL, 
	NBR 		VARCHAR(20), 
	RSN 		VARCHAR(128), 
	INDX 		int NULL, 
	INTLS 		VARCHAR(3),
	PRIMARY KEY (ID_TRN, SQN_NBR)
   )

  CREATE TABLE MGR_OVRD_RSN
   (	
	ID_RSN 			VARCHAR(125), 
	DES_RSN_EN 		VARCHAR(250), 
	DES_RSN_ES 		VARCHAR(250),
	PRIMARY KEY (ID_RSN)
   )
   
  CREATE TABLE PA_OPR
   (	
	ID_OPR 		int IDENTITY (1, 1) NOT NULL, 
	CD_OPR 		VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_OPR)
   )
   
  CREATE UNIQUE INDEX UNQ_OPR ON PA_OPR (CD_OPR) 
  
  CREATE TABLE PA_ADQUIRIENTE
   (
	ID_ADQ int IDENTITY(1,1) NOT NULL,
	CD_ADQ int NOT NULL,
	DES_ADQ varchar(50) NOT NULL,
	PRIMARY KEY (ID_ADQ)
   )
   
   CREATE TABLE [dbo].[PA_ADQ_CER](
	[ID_ADQCER] [int] IDENTITY(1,1) NOT NULL,
	[CD_ADQCER] [char](2) NULL,
	[DE_ADQCER] [varchar](50) NULL
	)
	
	CREATE TABLE [dbo].[PA_ADQ_CODES](
	[ID_CODE] [int] IDENTITY(1,1) NOT NULL,
	[CD_ADQCER] [char](2) NULL,
	[CD_CODE] [varchar](50) NULL,
	[DE_CODE] [varchar](100) NULL
	)
   
   CREATE TABLE [dbo].[PA_BIN](
	[ID_BIN] [bigint] IDENTITY(1,1) NOT NULL,
	[CD_BIN] [bigint] NOT NULL,
	[EST_BIN] [int] NOT NULL DEFAULT ((1)),
	[FL_PROC] [int] NOT NULL DEFAULT ((0)),
	[ID_OPCHDR] [int] NOT NULL DEFAULT ((0)),
	[NET_ID] [varchar](2) NOT NULL DEFAULT ('CC'),
	[HOST] [varchar](3) NOT NULL DEFAULT ('SYS'),
	[FL_CRDA] [int] NOT NULL DEFAULT ((1)),
	[FL_FTM] [int] NOT NULL DEFAULT ((0)),
	[FL_MANA] [int] NOT NULL DEFAULT ((0)),
	[FL_BILL] [int] NOT NULL DEFAULT ((1)),
	[FL_POINTS] [int] NOT NULL DEFAULT ((0)),
	[JER_SAP] [char](1) NULL DEFAULT ((0)),
	[DES_BIN] [varchar](15) NOT NULL,
	[CD_FRANK] [int] NULL DEFAULT ((0)),
	[FL_BSOL] [int] NOT NULL DEFAULT ((0)),
	[CD_CARD_TY] [int] NOT NULL DEFAULT ((0)),
	[FL_RET] [int] NOT NULL DEFAULT ((0)),
	[FL_PIN] [int] NOT NULL DEFAULT ((0)),
	[FL_CVC] [int] NOT NULL DEFAULT ((0)),
	[FL_CHANGE] [int] NOT NULL DEFAULT ((0)),
	[IDREG] [int] NOT NULL DEFAULT ((0)),
	[FECHA] [datetime] NOT NULL DEFAULT (getdate()),
	[FL_DBLC] [int] NULL DEFAULT ((0)),
	[CD_CARDPID] [char](2) NULL,
	[ID_TND] [int] NULL,
	[FL_DIF_CINT] [int] NULL DEFAULT ((0)),
	[FL_DIF_SINT] [int] NULL DEFAULT ((0)),
	[CD_CARDACE] [char](2) NULL,
	[LEN_ACNT_NUM] [int] NULL DEFAULT ((16)),
	[FL_SETOPC] [int] NULL  DEFAULT ((0)),
	PRIMARY KEY (ID_BIN)
	)
	
   CREATE TABLE [PA_BIN_CARDTY]
   (
	[ID_CARDTY] [int] IDENTITY(1,1) NOT NULL,
	[CD_CARDTY] [int] NOT NULL DEFAULT ((0)),
	[DES_CARDTY] [varchar](100) NULL,
	[LENID_CARDTY] [int] NULL DEFAULT ((16)),
	PRIMARY KEY (ID_CARDTY)
	)
	
	CREATE TABLE [dbo].[PA_BIN_CPID_CTAB](
	[CD_CARDPID] [char](2) NULL, 
	[CD_STR] [int] NULL, 
	[ID_CTAB] [int] NULL,  
	[ID_CTAB_DIF] [int] NULL  
	) 
	
	CREATE TABLE [PA_BIN_CPID]
	(
	[ID_CARDPID] [int] IDENTITY(1,1) NOT NULL,
	[CD_CARDPID] [char](2) NOT NULL,
	[DES_CARDPID] [varchar](50) NULL,
	[CD_INI_DEP] [char](2) NULL,
	[BIN_ENV] [int] NULL,
	[CD_ADQ] [char](3) NULL,
	[ORD_RECAP] [char](2) NULL,
	[FL_ADVICE] [bit] NULL DEFAULT ((1)),
	[FL_MASK] [bit] NULL DEFAULT ((1)),
	[LEN_ACNT_NUM] [int] NULL DEFAULT ((16)),
	[ID_CTAB] [int] NULL DEFAULT ((0)),
	[CD_CARDACE] [char](2) NULL,
	[ID_CTAB_DIF] [int] NULL DEFAULT ((0)),
	PRIMARY KEY (ID_CARDPID)
	) 

	CREATE TABLE [PA_BIN_FRANK]
	(
	[ID_FRANK] [int] IDENTITY(1,1) NOT NULL,
	[CD_FRANK] [int] NOT NULL DEFAULT ((0)),
	[DES_FRANK] [varchar](50) NULL,
	PRIMARY KEY (ID_FRANK)
	) 
	
	CREATE TABLE [PA_BIN_GRPSEC]
	(
	[ID_GRPSEC] [int] IDENTITY(1,1) NOT NULL,
	[DES_GRPSEC] [varchar](100) NULL,
	[FL_INCL] [int] NOT NULL DEFAULT ((1)),
	[IDREG] [int] NOT NULL DEFAULT ((0)),
	[FECHA] [datetime] NOT NULL DEFAULT (getdate()),
	[ESTADO] [int] NOT NULL DEFAULT ((0)),
	PRIMARY KEY (ID_GRPSEC)
	)

	CREATE TABLE PA_BIN_OPCBIN
	(
	[ID_OPCHDR] [int] NULL,
	[CD_BIN] [int] NULL,
	[SET_BIN] [int] NULL DEFAULT ((0))
	)
	
	CREATE TABLE PA_BIN_OPCCPID
	(
	[ID_OPCHDR] [int] NULL,
	[CD_CARDPID] [char](2) NULL,
	[PRIORITY] [int] NULL DEFAULT ((0))
	)
		
	CREATE TABLE [PA_BIN_OPCDET]
	(
	[ID_OPCDET] [int] IDENTITY(1,1) NOT NULL,
	[ID_OPCHDR] [int] NOT NULL,
	[NUM_DIFER] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCDET_NUM_DIFER]  DEFAULT ((0)),
	[DIF_1] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCDET_DIF_1]  DEFAULT ((0)),
	[DIF_2] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCDET_DIF_2]  DEFAULT ((0)),
	[DIF_4] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCDET_DIF_4]  DEFAULT ((0)),
	[DIF_8] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCDET_DIF_8]  DEFAULT ((0)),
	[DIF_16] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCDET_DIF_16]  DEFAULT ((0)),
	[MNT_MIN_SLS] [bigint] NOT NULL CONSTRAINT [DF_PA_BIN_OPCDET_MNT_MIN_SLS]  DEFAULT ((0)),
	[RS_DIF_1] [int] NOT NULL DEFAULT ((0)), 
	[RS_DIF_2] [int] NOT NULL DEFAULT ((0)), 
	[RS_DIF_4] [int] NOT NULL DEFAULT ((0)), 
	[RS_DIF_8] [int] NOT NULL DEFAULT ((0)),
	[RS_DIF_16] [int] NOT NULL DEFAULT ((0)), 
	[FI_DIF_1] [datetime] NULL, 
	[FT_DIF_1] [datetime] NULL, 
	[FI_DIF_2] [datetime] NULL, 
	[FT_DIF_2] [datetime] NULL, 
	[FI_DIF_4] [datetime] NULL, 
	[FT_DIF_4] [datetime] NULL, 
	[FI_DIF_8] [datetime] NULL, 
	[FT_DIF_8] [datetime] NULL, 
	[FI_DIF_16] [datetime] NULL, 
	[FT_DIF_16] [datetime] NULL, 
	[MNT_DIF_1] [bigint] NULL CONSTRAINT [DF_PA_BIN_OPCDET_MNT_DIF_1]  DEFAULT ((0)), 
	[MNT_DIF_2] [bigint] NULL CONSTRAINT [DF_PA_BIN_OPCDET_MNT_DIF_2]  DEFAULT ((0)), 
	[MNT_DIF_4] [bigint] NULL CONSTRAINT [DF_PA_BIN_OPCDET_MNT_DIF_4]  DEFAULT ((0)), 
	[MNT_DIF_8] [bigint] NULL CONSTRAINT [DF_PA_BIN_OPCDET_MNT_DIF_8]  DEFAULT ((0)), 
	[MNT_DIF_16] [bigint] NULL CONSTRAINT [DF_PA_BIN_OPCDET_MNT_DIF_16]  DEFAULT ((0)), 
	PRIMARY KEY (ID_OPCDET)
	)
	
	CREATE TABLE [PA_BIN_OPCHDR]
	(
	[ID_OPCHDR] [int] IDENTITY(1,1) NOT NULL,
	[CD_CARDACE] [char](2) NOT NULL,
	[CD_OPCSLS] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCHDR_CD_OPCSLS]  DEFAULT ((0)),
	[ID_GRPSEC] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCHDR_ID_GRPSEC]  DEFAULT ((0)),
	[OPC_DIFER] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCHDR_MAX_NUM_CUOTA]  DEFAULT ((0)),
	[DES_OPCHDR] [varchar](200) NULL,
	[IDREG] [int] NOT NULL CONSTRAINT [DF_PA_BIN_OPCHDR_IDREG]  DEFAULT ((1)),
	[FECHA] [datetime] NOT NULL CONSTRAINT [DF_PA_BIN_OPCHDR_FECHA]  DEFAULT (getdate()),
	[LEN_ACNT_NUM] [int] NULL DEFAULT ((16)),
	[DIF_1] [int] NULL CONSTRAINT [DF_PA_BIN_OPCHDR_DIF_1]  DEFAULT ((0)),
	[DIF_2] [int] NULL CONSTRAINT [DF_PA_BIN_OPCHDR_DIF_2]  DEFAULT ((0)),
	[DIF_4] [int] NULL CONSTRAINT [DF_PA_BIN_OPCHDR_DIF_4]  DEFAULT ((0)),
	[DIF_8] [int] NULL CONSTRAINT [DF_PA_BIN_OPCHDR_DIF_8]  DEFAULT ((0)),
	[DIF_16] [int] NULL CONSTRAINT [DF_PA_BIN_OPCHDR_DIF_16]  DEFAULT ((0)),
	[IND_ACTIVO] [int] NULL CONSTRAINT [DF_PA_BIN_OPCHDR_IND_ACTIVO]  DEFAULT ((0)), 
	[FEC_INI] [datetime] NULL,
	[FEC_TER] [datetime] NULL, 
	[FEC_ACT] [datetime] NULL DEFAULT (getdate()), 
	[PRIORITY] [int] NULL DEFAULT ((0)),
	PRIMARY KEY (ID_OPCHDR)
	)
	
	CREATE TABLE [PA_BIN_OPCSTR] 
	(
	[ID_OPCHDR] [int] NULL, 
	[CD_STR] [int] NULL, 
	[ID_OPCDET] [int] NULL DEFAULT ((0)), 
	[NUM_DIFER] [int] NULL DEFAULT ((0))
	)
	
	CREATE TABLE [PA_BIN_PROCFL]
	(
	[ID_PROCFL] [int] IDENTITY(1,1) NOT NULL,
	[CD_PROCFL] [int] NOT NULL,
	[DES_PROCFL] [varchar](50) NULL,
	PRIMARY KEY (ID_PROCFL)
	)
	
	CREATE TABLE [dbo].[PA_BIN_RANGO](
	[INICIO] [int] NULL,
	[FIN] [int] NULL,
	[CD_CARDPID] [char](2) NULL,
	[ID_CTAB] [int] NULL
	)
	
	CREATE TABLE [dbo].[PA_BIN_RANK](
	[ID_RANGO] [int] IDENTITY(1,1) NOT NULL,
	[CD_RANGO] [int] NULL,
	[CD_CARDPID] [char](2) NULL,
	[IND_ACTIVO] [int] NULL DEFAULT ((0)),
	[ID_REG] [int] NULL,
	[FECHA] [datetime] NULL DEFAULT (getdate()) 
	)
	
	CREATE TABLE [PA_BIN_SECC]
	(
	[ID_GRPSEC] [int] NOT NULL,
	[ID_DPT_PS] [int] NOT NULL
	)

  CREATE TABLE PA_REC_ELEC
  (
	ID_REC 		int IDENTITY(1,1) NOT NULL,
	CD_ITM 		int NOT NULL,
	FL_PIN 		int NOT NULL DEFAULT 0,
	FL_PRC 		int NOT NULL DEFAULT 0,
	MO_MIN 		int NOT NULL DEFAULT 0,
	MO_MAX 		int NOT NULL DEFAULT 0,
	FL_DEC 		int NOT NULL DEFAULT 0,
	LEN_ID 		int NOT NULL DEFAULT 0,
	MET_ENVIO 	int NOT NULL DEFAULT 0,
	FL_PROMO 	int NOT NULL DEFAULT 0,
	ID_OPE 		int NOT NULL DEFAULT 0,
	IDREG 		int NOT NULL DEFAULT 0,
	FECHA 		date NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	ESTADO 		int NOT NULL DEFAULT 0,
	DES_REC 	varchar(20) NULL,
	PRIMARY KEY (ID_REC)
   ) 
   
   CREATE TABLE PA_REC_METNV
   (
	ID_METNV INT IDENTITY NOT NULL,
	DES_METNV CHAR(2),
	NM_METNV VARCHAR(40),
	PRIMARY KEY (ID_METNV)
   )
   
   CREATE TABLE PA_REC_OPER
   (
	ID_OPE int IDENTITY(1,1) NOT NULL,
	CD_ADQ int NOT NULL,
	DES_OPE varchar(50) NOT NULL,
	PRIMARY KEY (ID_OPE)
   ) 

  CREATE TABLE PA_STR_RTL
   (	
	ID_BSN_UN 	int IDENTITY (1, 1) NOT NULL, 
	DE_STR_RT 	VARCHAR(255), 
	CD_STR_RT 	int NOT NULL, 
	IVA_TAX 	VARCHAR(1) DEFAULT 'I', 
	INC_PRC 	VARCHAR(1) DEFAULT 'S', 
	IMP_1 		int NOT NULL DEFAULT 0, 
	IMP_2 		int NOT NULL DEFAULT 0, 
	IMP_3 		int NOT NULL DEFAULT 0, 
	IMP_4 		int NOT NULL DEFAULT 0, 
	IMP_5 		int NOT NULL DEFAULT 0, 
	IMP_6 		int NOT NULL DEFAULT 0, 
	IMP_7 		int NOT NULL DEFAULT 0, 
	IMP_8 		int NOT NULL DEFAULT 0,
	CE_COBE		VARCHAR(20) NULL,
	NO_AFIL_FL 		int NOT NULL DEFAULT 1,
	ID_CTAB 	int NULL DEFAULT 0,
	PRIMARY KEY (ID_BSN_UN)
   )
   
   CREATE TABLE PA_STR_STS
   (	
	ID_BSN_UN 	int NOT NULL, 
	DC_DY_BSN datetime NOT NULL, 
	ID_CLD_PRD int NOT NULL, 
	PRIMARY KEY (ID_BSN_UN)
   )
   
   CREATE TABLE [dbo].[PI_CONTROL](
	[COD_TIENDA] [int] NOT NULL,
	[FECHA_CIERRE] [date] NOT NULL,
	[AGR] [varchar](1) NULL,
	[FER] [varchar](1) NULL,
	[MOT] [varchar](1) NULL,
	[REC] [varchar](1) NULL,
	[GIF] [varchar](1) NULL,
	[ILI] [varchar](1) NULL,
	[BOL] [varchar](1) NULL,
	[FOP] [varchar](1) NULL,
	[VAL] [varchar](1) NULL,
	[CTC] [varchar](1) NULL,
	[SOA] [varchar](1) NULL,
	[CUP] [varchar](1) NULL,
	[GAE] [varchar](1) NULL,
	[CJC] [varchar](1) NULL,
	[SOB] [varchar](1) NULL,
	[EFC] [varchar](1) NULL,
	[TRJ] [varchar](1) NULL,
	[RET] [varchar](1) NULL,
	[VAE] [varchar](1) NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[ID_TRX_CIERRE] [int] NOT NULL,
	[TIENDA] [varchar](3) NULL,
	[SECUENCIA_EFC] [int] NULL,
	[CICLO_EFC] [int] NULL,
	[SECUENCIA_TRJ] [int] NULL,
	[RECEPCION_CAJAS] [varchar](1) NULL,
	[CONTABILIZAR] [varchar](1) NULL,
 CONSTRAINT [PK__PI_CONTR__86C141BA0932FA18] PRIMARY KEY CLUSTERED 
(
	[COD_TIENDA] ASC,
	[FECHA_CIERRE] ASC,
	[FECHA_REGISTRO] ASC,
	[ID_TRX_CIERRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

	CREATE TABLE [dbo].[PI_DESCUENTOS_PROV](
	[TIENDA] [varchar](3) NULL,
	[FECHA] [date] NULL,
	[COD_PROMOCION] [varchar](25) NULL,
	[COD_PROVEEDOR] [varchar](20) NULL,
	[MATERIAL] [varchar](18) NULL,
	[CANTIDAD] [varchar](7) NULL,
	[TOTAL] [varchar](20) NULL,
	[NOM_PROMOCION] [varchar](255) NULL,
	[CEBE] [varchar](10) NULL,
	[FECHA_LECTURA] [datetime] NULL
	)
	
   CREATE TABLE [PI_METODOS_PAGO_EQUIVALENCIA](
	[TY_TND] [int] NOT NULL,
	[ID_SAP] [varchar](4) NOT NULL,
   CONSTRAINT [PK_PI_FORMAS_PAGO_EQUIVALENCIA] PRIMARY KEY CLUSTERED 
   (
	[TY_TND] ASC,
	[ID_SAP] ASC
   )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
   ) ON [PRIMARY]

   CREATE TABLE [PI_PARAMETROS](
	[ID] [nvarchar](10) NULL,
	[DESCRIPCION] [nvarchar](4) NOT NULL
   ) ON [PRIMARY]

   CREATE TABLE [PI_SECUENCIA](
	[TIENDA] [varchar](3) NOT NULL,
	[EAN] [int] NOT NULL,
	[MATERIALES] [int] NOT NULL,
   PRIMARY KEY CLUSTERED 
   (
	[TIENDA] ASC
   )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
   ) ON [PRIMARY]
   
   CREATE TABLE [PI_VALES_EMPLEADOS_EQUIVALENCIA](
	[ID_TOS] [varchar](4) NOT NULL,
	[ID_SAP] [varchar](3) NOT NULL,
   CONSTRAINT [PK_PI_VALES_EMPLEADOS_EQUIVALENCIA] PRIMARY KEY CLUSTERED 
   (
	[ID_TOS] ASC,
	[ID_SAP] ASC
   )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
   ) ON [PRIMARY]
   
   CREATE TABLE [PI_WPUUMS](
	[TIENDA] [varchar](3) NULL,
	[BELEGDATUM] [date] NOT NULL,
	[BELEGWAERS] [varchar](4) NULL,
	[QUALARTNR] [varchar](4) NULL,
	[ARTNR] [varchar](20) NULL,
	[UMSMENGE] [varchar](20) NULL,
	[MONTO] [varchar](20) NULL,
	[DESCUENTO] [varchar](20) NULL,
	[KONDVALUE] [varchar](20) NULL,
	[IDENTIFICADOR] [varchar](21) NULL,
	[ESTADO] [varchar](1) NULL,
	[FECHA_LECTURA] [datetime] NULL,
	[COD_ITM] [bigint] NULL DEFAULT ((0))
   ) ON [PRIMARY]
   
   CREATE TABLE [PI_SECUENCIA_INICIAL](
	[cod_tienda] [int] NULL,
	[SECUENCIA_EFC] [int] NULL,
	[CICLO_EFC] [int] NULL,
	[SECUENCIA_TRJ] [int] NULL
	) ON [PRIMARY]

  CREATE TABLE RTNC_USD
   (	
	ID_TRN 		int NOT NULL, 
	USD_DT 		datetime NOT NULL,
	PRIMARY KEY (ID_TRN)
   )
   
  CREATE TABLE TR_BSN_EOD
   (	
	ID_TRN 		int NOT NULL, 
	CL_END 		int NOT NULL default 0, 
	FL_EOD 		int NOT NULL DEFAULT 0,
	FEC_EOD 	DATETIME,
	PRIMARY KEY (ID_TRN)
   )
   
   CREATE TABLE [dbo].[TR_BSN_EOD_SUM](
	[ID_TRN] [int] NOT NULL,
	[ID_TND] [int] NOT NULL,
	[TY_TND] [int] NOT NULL,
	[MO_TND] [decimal](14, 3) NOT NULL CONSTRAINT [DF_TR_BSN_EOD_SUM_MO_TND]  DEFAULT ((0)),
	[MO_LON] [decimal](14, 3) NOT NULL CONSTRAINT [DF_TR_BSN_EOD_SUM_MO_LON]  DEFAULT ((0)),
	[MO_PKP] [decimal](14, 3) NOT NULL CONSTRAINT [DF_TR_BSN_EOD_SUM_MO_PKP]  DEFAULT ((0)),
	[MO_OVR] [decimal](14, 3) NOT NULL CONSTRAINT [DF_TR_BSN_EOD_SUM_MO_OVR]  DEFAULT ((0)),
	[MO_MSS] [decimal](14, 3) NOT NULL CONSTRAINT [DF_TR_BSN_EOD_SUM_MO_MSS]  DEFAULT ((0)),
	ID_OPR int NOT NULL DEFAULT 0,
	[TY_SUM] [int] NOT NULL DEFAULT ((0)),
	[MO_LST] [decimal](14, 3) NOT NULL CONSTRAINT [DF_TR_BSN_EOD_SUM_MO_LST]  DEFAULT ((0))
   )
   
   CREATE TABLE [dbo].[TR_DEP_BOD](
	[ID_TRN] [int] NOT NULL,
	[TY_DEP] [char](3) NOT NULL,
	[MO_DEP] [decimal](14, 3) NOT NULL,
	[TY_TND] [int] NOT NULL,
	[ID_SAP] [varchar](4) NOT NULL,
	[CD_STR_RT] [int] NOT NULL,
	[ID_CTAB] [int] NOT NULL DEFAULT ((0)),
	[ESTADO] [int] NULL DEFAULT ((0)),
	TS_DEP	datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
   CREATE TABLE [dbo].[TR_DEP_EOD](
	[ID_TRN] [int] NOT NULL,
	[TY_DEP] [char](3) NOT NULL,
	[MO_DEP] [decimal](14, 3) NOT NULL,
	[TY_TND] [int] NOT NULL,
	[ID_SAP] [varchar](4) NOT NULL,
	[CD_STR_RT] [int] NOT NULL,
	[ID_CTAB] [int] NOT NULL DEFAULT ((0)),
	[ESTADO] [int] NOT NULL DEFAULT ((0)),
	[CD_CARDPID] [varchar](3) NULL,
	TS_DEP	datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
   CREATE TABLE [dbo].[TR_DEP_TYP](
	[TY_DEP] [char](3) NULL,
	[DES_DEP] [varchar](50) NULL
   )

  CREATE TABLE TR_CRY_FWRD
   (	
	ID_TRN 		int NOT NULL, 
	ID_TRN_BSN_EOD 		int NOT NULL, 
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_CTL
   (	
	ID_TRN 		int NOT NULL, 
	TY_TRN_CTL 	VARCHAR(4), 
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_CTL_TND
   (	
	ID_TRN 			int NOT NULL, 
	CD_RSN 			VARCHAR(4), 
	TY_TND_CTL 		VARCHAR(2), 
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_DS_TND
   (	
	ID_TRN 				int NOT NULL, 
	ID_RPSTY_TND_FM 	int NOT NULL, 
	ID_RPSTY_TND_TO 	int NOT NULL, 
	ID_WRKR 			int NULL, 
	ID_BG_DS 			int NULL, 
	DE_DS 				VARCHAR(255), 
	MO_DS 				decimal(16,5) NOT NULL DEFAULT 0, 
	MO_DS_FRG_CY 		decimal(16,5) NOT NULL DEFAULT 0, 
	MO_OVR 				decimal(16,5) NOT NULL DEFAULT 0, 
	MO_OVR_FRG_CY 		decimal(16,5) NOT NULL DEFAULT 0, 
	MO_SHRT 			decimal(16,5) NOT NULL DEFAULT 0, 
	MO_SHRT_FRG_CY 		decimal(16,5) NOT NULL DEFAULT 0, 
	DS_TY 				int NULL, 
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_INVC
   (	
	ID_TRN 		int NOT NULL, 
	INVC_NMB 	VARCHAR(20), 
	ID_CPR 		bigint NULL, 
	FL_CP 		int NULL,
	SUB_TOTAL   VARCHAR(12),
	TOTAL    	VARCHAR(12),
	IMP_1 		int NOT NULL DEFAULT 0, 
	NM_CST      VARCHAR(250),
	ID_CST      VARCHAR(20),
	PRIMARY KEY (ID_TRN)
   )
   
   CREATE TABLE TR_TY_RTN
   (	
	ID_TY_RTN		int NOT NULL, 
	TY_RTN_NM 		VARCHAR(50), 
	PRIMARY KEY (ID_TY_RTN)
   )
   
   CREATE TABLE [dbo].[TR_TY_TRN](
	[TY_TRN] 		[int] NOT NULL,
	[CD_TY_TRN] [varchar](50) NULL,
	PRIMARY KEY (TY_TRN)
   )
   
   CREATE TABLE [dbo].[TR_TY_TAX](
	[ID_IMP] [int] IDENTITY(1,1) NOT NULL,
	[CD_TAX] [int] NOT NULL,
	[CD_IMP] [int] NOT NULL
	)

   CREATE TABLE TR_RTN
   (	
	ID_TRN 			int NOT NULL, 
	RTN_NMB 		VARCHAR(20), 
	ORGL_AI_TRN		int NULL,
	ORGL_INVC_NMB 	VARCHAR(20), 
	ORGL_STR_CD		int NULL,
	TY_RTN			int NULL,
	IMP_1 			int NOT NULL DEFAULT 0, 
	ORGL_DC_DY_BSN	datetime NOT NULL, 
	ORGL_CD_WS		int NOT NULL, 
	CD_OPR		 	VARCHAR(10) NOT NULL DEFAULT '0', 
	CD_SUP		 	VARCHAR(10) NOT NULL DEFAULT '0', 
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_LON_TND
   (	
	ID_TRN 		int NOT NULL, 
	OTB_CD_STR 	int NULL, 
	INB_CD_WS 	int NULL,
	OPERATOR    VARCHAR(12),
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_LTM_MDF
   (	
	ID_TRN 		int NOT NULL, 
	AI_LN_ITM 	int NOT NULL, 
	ID_PRM 		int NULL, 
	Y_MDF 		VARCHAR(2), 
	PE_MDF 		decimal(10,5), 
	MO_MDF 		decimal(14,3) NOT NULL DEFAULT 0, 
	FL_PRRT 	bit NULL, 
	FL_CNCL 	bit NULL,
	TY_MDF 		VARCHAR(20),
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )
   
  CREATE TABLE TR_LTM_TND_RTN
   (	
	ID_TRN 		int NOT NULL, 
	AI_LN_ITM 	int NOT NULL, 
	STS 		int NULL,
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )

  CREATE TABLE TR_LTM_MOTO_DT
   (	
	ID_TRN 		int NOT NULL, 
	AI_LN_ITM 	int NOT NULL, 
	SRL_NBR 	VARCHAR(20),
	CC_OPERADOR int NULL,
	CD_ITM	    bigint NOT NULL,
	FL_VD       int NOT NULL DEFAULT 0,
	FL_RV       int NOT NULL DEFAULT 0, 
	DIRECCION 	VARCHAR(250),
	CIUDAD 		VARCHAR(250),
	TELEFONO 	VARCHAR(20),
	NACIONALIDAD VARCHAR(250),
	FL_CELL int NOT NULL DEFAULT 1,
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )
   
   CREATE TABLE CO_CRD_DT
   (	
	ID_TRN 		int NOT NULL, 
	SQ_NBR 		int NOT NULL, 
	CRD_NBR 	VARCHAR(20),
	CRD_TY 		VARCHAR(5),
	FL_AUT_SYS	int NOT NULL DEFAULT 0,
	ACT_CD      VARCHAR(10), 
	SEQ_TRX		VARCHAR(6),
	TM			VARCHAR(6),
	CD_CST		VARCHAR(13),
	AMNT		decimal(14,3) NOT NULL DEFAULT 0,
	CP_DSP		decimal(14,3) NOT NULL DEFAULT 0,
	CD_RSP		VARCHAR(2),
	STS_CRD		VARCHAR(1),
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
   CREATE TABLE CO_CSM_SYS_DT
   (	
	ID_CSM_SYS_DT 		int IDENTITY (1, 1) NOT NULL, 
	INVC_NMB 			VARCHAR(20),
	ACNT_NMB 			VARCHAR(20),
	SEQ_TRX				VARCHAR(6),
	AUT_NMB				VARCHAR(6),
	AMNT_1				int NOT NULL DEFAULT 0,
	AMNT_2				int NOT NULL DEFAULT 0,
	RSP_CD 				VARCHAR(2),
	DC_DY_BSN 			datetime, 
	PRIMARY KEY (ID_CSM_SYS_DT)
   )
   
   CREATE TABLE CO_PTS_DT
   (	
	ID_CO_PTS_DT 		int IDENTITY (1, 1) NOT NULL, 
	CD_STR_RT 			int NOT NULL, 
	CD_WS 				VARCHAR(50) NOT NULL, 
	DC_DY_BSN			datetime NOT NULL, 
	AI_TRN				int NOT NULL, 
	CD_ITM				bigint NOT NULL,
	ORDL_NBR			int NOT NULL,
	PTS					int NOT NULL DEFAULT 0,
	CD_PRM				VARCHAR(24),
	FL_RV 				INT NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_CO_PTS_DT)
   )
   
   CREATE TABLE CO_CHK_DT
   (	
	ID_TRN 			int NOT NULL, 
	SQ_NBR 			int NOT NULL, 
	BNK 			VARCHAR(45),
	CHK_ACC_NBR 	VARCHAR(35),
	CHK_NBR	    	VARCHAR(25),
	CHK_DT      	VARCHAR(12),
	CHK_AMNT      	VARCHAR(25), 
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
   CREATE TABLE CO_BILL_DT
   (	
	ID_TRN 		int NOT NULL, 
	SQ_NBR 		int NOT NULL, 
	DNM 		VARCHAR(15),
	NBR 		VARCHAR(25),
	NM	    	VARCHAR(45),
	CD_CPR      VARCHAR(20), 
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
   CREATE TABLE CO_BON_SOL
   (	
	ID_TRN 		int NOT NULL, 
	SQ_NBR 		int NOT NULL, 
	AI_TRN 		VARCHAR(20),
	ID_CLIENTE 		VARCHAR(13),
	CUPO	    	VARCHAR(8),
	MONTO_DSC	    VARCHAR(8)
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
   CREATE TABLE CO_REC_ELEC
   (	
	ID_TRN 		int NOT NULL, 
	SQ_NBR 		int NOT NULL, 
	CD_ITM 		VARCHAR(20),
	STR 			VARCHAR(4),
	WS	    		VARCHAR(3),
	REF 			VARCHAR(20),
	TIPO 			VARCHAR(2),
	NUM	    		VARCHAR(13),
	MONTO	    	VARCHAR(20),
	NUM_AUTO		VARCHAR(10),
	HORA_TRX		VARCHAR(6),
	FL_CANCL		VARCHAR(1),
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
   CREATE TABLE CO_RECAUDOS
   (	
	ID_TRN 		int NOT NULL, 
	SQ_NBR 		int NOT NULL, 
	TY_STR 		VARCHAR(2),
	TY_REC 		VARCHAR(2),
	CD_ITM	    VARCHAR(14),
	MONTO       VARCHAR(8), 
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )

    CREATE TABLE CO_DSC_EMP
   (	
	ID_TRN 		int NOT NULL, 
	SQ_NBR 		int NOT NULL,
	CD_ITM 		VARCHAR(14),
	MO_DSC_EMP	decimal(14,3) NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
    CREATE TABLE CO_DSC_EMP_TOT
   (	
	ID_TRN 		int NOT NULL,
	AI_TRN	 	VARCHAR(20),
	MO_DSC_TOT  decimal(14,3) NOT NULL DEFAULT 0, 
	PRIMARY KEY (ID_TRN)
   )
   
   CREATE TABLE CO_CPN_PRM_DTA
   (	
	ID_TRN 		int NOT NULL, 
	SQ_NBR 		int NOT NULL,
	CD_CPN 		VARCHAR(14),
	QTY			int NOT NULL DEFAULT 0,
	QTY_DEV 	int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
   CREATE TABLE CO_PTS_PRM_DTA
   (	
	ID_TRN 			int NOT NULL, 
	SQ_NBR 			int NOT NULL,
	COD_NEGOCIO 	int NOT NULL DEFAULT 0,
	QTY				int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
    CREATE TABLE CO_ASSOCIATED_DATA
   (	
	ID_TRN 			int NOT NULL,
	STR_TYPE	 	VARCHAR(2),
	PRS_TYPE  		VARCHAR(2),
	CTA_NUMBER	 	VARCHAR(16),
	FL_REDEP_PTS  	VARCHAR(1),
	CUSTOMER_ID	 	VARCHAR(20),
	PORTADOR_ID	 	VARCHAR(20),
	PORTADOR_NAME 	VARCHAR(60),
	PRIMARY KEY (ID_TRN)
  )
   
     CREATE TABLE CO_DATOS_EMP
   (	
	ID_TRN 		int NOT NULL, 
	SQ_NBR 		int NOT NULL, 
	TRX_NUM 	VARCHAR(20),
	TER_NUM 	VARCHAR(3),
	EMP_NUM	    VARCHAR(20),
	ID_PORTADOR      VARCHAR(20),
	NOM_PORTADOR 	VARCHAR(20),
	TRJ_PISTA_A	    VARCHAR(76),
	TRJ_PISTA_B      VARCHAR(37), 
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
    CREATE TABLE CO_TRANSF_BANC
   (	
	ID_TRN 		int NOT NULL, 
	SQ_NBR 		int NOT NULL, 
	ID_BANCO 	VARCHAR(3),
	NUM_CTA 	VARCHAR(20),
	MONTO	    VARCHAR(8),
	FL_TND      VARCHAR(1), 
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
   CREATE TABLE CO_TND_PINPAD
   (	
	ID_TRN 					int NOT NULL, 
	SQ_NBR 					int NOT NULL, 
	COD_ADQ 				VARCHAR(1),
	COD_DIF 				VARCHAR(2),
	PLZ_DIF	    			VARCHAR(2),
	MSM_GRACIA      		VARCHAR(2), 
	MONTO 					decimal(14,3) NOT NULL DEFAULT 0,
	MONTO_B_GRAB_IVA 		decimal(14,3) NOT NULL DEFAULT 0,
	MONTO_B_NO_GRAB_IVA	    decimal(14,3) NOT NULL DEFAULT 0,
	IVA_TRX      			decimal(14,3) NOT NULL DEFAULT 0,
	INTERES      			decimal(14,3) NOT NULL DEFAULT 0,
	SEQ_TRX 				VARCHAR(6),
	HORA_TRX 				VARCHAR(6),
	FECHA_TRX	   			VARCHAR(8),
	NUM_AUTO      			VARCHAR(6), 
	MID 					VARCHAR(15),
	TID 					VARCHAR(8),
	CID	    				VARCHAR(15),
	FL_RV 					int NOT NULL DEFAULT 0,
	ARQC					VARCHAR(16),
	AID						VARCHAR(20),
	BNK_NM					VARCHAR(20),
	BRND_NM					VARCHAR(20),
	LOTE 					int NULL,
	PRIMARY KEY (ID_TRN, SQ_NBR)
   )
   
   CREATE TABLE CO_FERRI_ALM
   (	
	ID_TRN 		int NOT NULL, 
	TRN_NBR 	VARCHAR(20), 
	ALM_NBR 	VARCHAR(4),
	PRIMARY KEY (ID_TRN)
   )
      
   CREATE TABLE CO_DEDUCIBLE
   (	
	ID_TRN 			int NOT NULL, 
	DEDUC_COMEST 	VARCHAR(9), 
	DEDUC_ROPA 		VARCHAR(9), 
	DEDUC_ESC 		VARCHAR(9),
	PRIMARY KEY (ID_TRN)
   )
      
  CREATE TABLE TR_LTM_RTL_TRN
   (	
	ID_TRN 				int NOT NULL, 
	AI_LN_ITM 			int NOT NULL, 
	TS_LN_ITM_BGN 		datetime, 
	FL_VD_LN_ITM 		bit NULL, 
	TS_LN_ITM_END 		datetime, 
	LU_MTH_LTM_RTL_TRN 	VARCHAR(50), 
	CD_TYP_LTM_TRN_RTL 	VARCHAR(2), 
	ID_TYP_LTM_TRN_RTL 	int NULL, 
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )
  
  CREATE TABLE TR_LTM_SLS_RTN
   (	
	ID_TRN 				int NOT NULL, 
	AI_LN_ITM 			int NOT NULL, 
	ID_ITM 				int NOT NULL, 
	ID_DPT_PS 			int NULL, 
	MO_PRC_REG 			decimal(14,3) NOT NULL DEFAULT 0, 
	QU_ITM_LM_RTN_SLS 	decimal(9,2) NOT NULL DEFAULT 0, 
	QU_UN 				decimal(9,2) NOT NULL DEFAULT 0, 
	MO_EXTND 			decimal(14,3) NOT NULL DEFAULT 0, 
	LU_MTH_ID_ENR 		VARCHAR(50), 
	CD_MRHRC_GP 		int NULL, 
	MO_TX 				int NULL DEFAULT 0, 
	MO_DSC_UN_EXT 		int NOT NULL DEFAULT 0, 
	FL_PRC_ALT 			int NOT NULL DEFAULT 0, 
	FL_PRM				bit NOT NULL DEFAULT 0,
	ORDL_NBR 			int NOT NULL,	
	FL_MAY				bit NOT NULL DEFAULT 0,
	FL_RED				bit NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )
   
   CREATE TABLE TR_LTM_RTN
   (	
	ID_TRN 				int NOT NULL, 
	AI_LN_ITM 			int NOT NULL, 
	OGNL_AI_LN_ITM		int NOT NULL, 
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )
   
   CREATE TABLE TR_LTM_PRM
   (
   	ID_TRN 				int NOT NULL, 
	AI_LN_ITM 			int NOT NULL, 
	AI_LN_ITM_PRM		int NOT NULL,
	MO_PRM				DECIMAL(14,3) NOT NULL DEFAULT 0,
	CD_PRM				VARCHAR(24),
	FL_VD				bit NOT NULL DEFAULT 0,
	ORDL_NBR 			int NOT NULL, 
	PRIMARY KEY (ID_TRN, AI_LN_ITM, AI_LN_ITM_PRM)
   )
   
  CREATE TABLE TR_LTM_SLS_RTN_TX
   (	
	ID_TRN 		int NOT NULL, 
	AI_LN_ITM 	int NOT NULL, 
	TX_A 		int NOT NULL DEFAULT 0, 
	TX_B 		int NOT NULL DEFAULT 0, 
	TX_C 		int NOT NULL DEFAULT 0, 
	TX_D 		int NOT NULL DEFAULT 0, 
	TX_E 		int NOT NULL DEFAULT 0, 
	TX_F 		int NOT NULL DEFAULT 0, 
	TX_G 		int NOT NULL DEFAULT 0, 
	TX_H 		int NOT NULL DEFAULT 0, 
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )

  CREATE TABLE TR_LTM_TND
   (	
	ID_TRN 				int NOT NULL, 
	AI_LN_ITM 			int NOT NULL, 
	TY_LTM_TND 			VARCHAR(10), 
	FL_IS_CHNG 			decimal(1,0), 
	ID_TND 				int NOT NULL, 
	ID_ACNT_TND 		VARCHAR(20), 
	MO_FRG_CY 			decimal(14,3) NOT NULL DEFAULT 0, 
	ID_CNY_FRG 			int NULL, 
	MO_RTE_EXC 			decimal(10,5) NOT NULL DEFAULT 0, 
	MO_ITM_LN_TND 		decimal(14,3) NOT NULL DEFAULT 0, 
	MO_FE_ITM_LN_TND 	decimal(14,3) NOT NULL DEFAULT 0, 
	STS_ITM_LN_TND 		int NOT NULL DEFAULT 0, 
	MO_TRN_AMT 			decimal(14,3) NOT NULL DEFAULT 0, 
	MO_FE_MSC_TOT 		decimal(14,3) NOT NULL DEFAULT 0, 
	FL_IS_LOST 			decimal(1, 0) NOT NULL DEFAULT 0,
	AI_LN_ITM_VD		int NOT NULL, 
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )

  CREATE TABLE TR_LTM_TND_CTL_TND
   (	
	ID_TRN 				int NOT NULL, 
	AI_TND_CTL_ITM 		int NOT NULL, 
	ID_TND 				int NOT NULL, 
	ID_CNY 				int NULL, 
	ID_DNM 				int NULL, 
	MO_FRG_CY 			decimal(14,3) NOT NULL DEFAULT 0, 
	RT_EXC 				decimal(14,3) NOT NULL DEFAULT 0, 
	MO_TND_FN_TRN 		decimal(14,3) NOT NULL DEFAULT 0, 
	QU_TND_FN_TRN 		decimal(7,0) NOT NULL DEFAULT 0, 
	MO_FE_MSC_TOT 		decimal(16,5) NOT NULL DEFAULT 0, 
	QU_VCHRS_TND_TRN 	decimal(7,0) NOT NULL DEFAULT 0, 
	PRIMARY KEY (ID_TRN, AI_TND_CTL_ITM)
   )
   
  CREATE TABLE TR_LTM_TX
   (	
	ID_TRN 		int NOT NULL, 
	AI_LN_ITM 	int NOT NULL, 
	PE_TXBLE 	decimal(5,2) NOT NULL DEFAULT 0, 
	MO_TXBL 	decimal(14,3) NOT NULL DEFAULT 0, 
	PE_TX 		decimal(5,2) NOT NULL DEFAULT 0, 
	MO_TX 		decimal(14,3) NOT NULL DEFAULT 0, 
	TY_TX 		VARCHAR(4), 
	SUB_TY_TX 	VARCHAR(4), 
	PRIMARY KEY (ID_TRN, AI_LN_ITM)
   )

  CREATE TABLE TR_PKP_TND
   (	
	ID_TRN 		int NOT NULL, 
	OTB_CD_WS 	int NULL, 
	INB_CD_STR 	int NULL, 
	FL_AUT_PKP 	bit NULL DEFAULT 0,
	OPERATOR    VARCHAR(12),
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_RCP_TND
   (	
	ID_TRN 				int NOT NULL, 
	ID_RPSTY_TND_FM 	int NOT NULL, 
	ID_RPSTY_TND_TO 	int NOT NULL, 
	ID_WRKR 			int NULL, 
	DE_DS 				VARCHAR(255), 
	MO_DS 				decimal(16,5) NOT NULL DEFAULT 0, 
	MO_DS_FRG_CY 		decimal(16,5) NOT NULL DEFAULT 0, 
	RCP_TY 				int NULL, 
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_RTL
   (	
	ID_TRN 			int NOT NULL, 
	CD_TYP_TRN_RTL 	VARCHAR(2), 
	ID_RPSTY_TND 	int NULL, 
	ID_CNY 			int NULL, 
	IN_RNG_ELPSD 	decimal(10,0) NOT NULL DEFAULT 0, 
	IN_TND_ELPSD 	decimal(10,0) NOT NULL DEFAULT 0, 
	IN_ELPSD_IDL 	decimal(10,0) NOT NULL DEFAULT 0, 
	IN_LCK_ELPSD 	decimal(10,0) NOT NULL DEFAULT 0, 
	QU_UN_RTL_TRN 	decimal(5,0) NOT NULL DEFAULT 0, 
	QU_ITM_LN_SC 	decimal(7,0) NOT NULL DEFAULT 0, 
	PE_ITM_LN_SC 	decimal(5,2) NOT NULL DEFAULT 0, 
	QU_ITM_LN_KY 	decimal(7,0) NOT NULL DEFAULT 0, 
	PE_ITM_LN_KY 	decimal(5,2) NOT NULL DEFAULT 0, 
	QU_DPT_KY 		decimal(7,0) NOT NULL DEFAULT 0, 
	PE_DPT_KY 		decimal(5,2) NOT NULL DEFAULT 0, 
	TS_TRN_RCP 		datetime, 
	ID_CT 			int NULL,
	TX_INC 			int NOT NULL DEFAULT 0, 
	PRIMARY KEY (ID_TRN)
   )
   
  CREATE TABLE TR_SGN_OFF
   (	
	ID_TRN 		int NOT NULL, 
	QTY_OF_TR 	int NULL, 
	PRIMARY KEY (ID_TRN)
   )
   
  CREATE TABLE TR_SGN_ON
   (	
	ID_TRN 		int NOT NULL, 
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_STLM_TL
   (	
	ID_TRN 		int NOT NULL, 
	PRIMARY KEY (ID_TRN)
   )

  CREATE TABLE TR_TOT_RTL
   (	
	ID_TRN 			int NOT NULL, 
	ID_TR_TOT_TYP 	int NOT NULL, 
	MO_TOT_RTL_TRN 	decimal(14,3), 
	FL_CNCL 		decimal(1,0) NOT NULL DEFAULT 0, 
	PRIMARY KEY (ID_TRN, ID_TR_TOT_TYP)
   )

  CREATE TABLE TR_TOT_TYP
   (	
	ID_TR_TOT_TYP 	int IDENTITY (1, 1) NOT NULL, 
	TY_TRN_TOT 		VARCHAR(40) NOT NULL, 
	NM_TYP_TRN_TOT 	VARCHAR(100), 
	PRIMARY KEY (ID_TR_TOT_TYP)
   )
   
    CREATE TABLE TR_TRN
   (	
	ID_TRN int IDENTITY (1, 1) NOT NULL, 
	ID_OPR int NULL, 
	ID_WS int NULL, 
	DC_DY_BSN datetime NOT NULL, 
	ID_CLD_PRD int NOT NULL, 
	ID_CLD_SUB_PRD int NOT NULL, 
	ID_TRN_SSN_SRT int NOT NULL DEFAULT 0, 
	ID_BSN_UN int NULL, 
	TY_TRN int NULL, 
	ID_CTR_RVN_CST int NULL, 
	AI_TRN int NULL, 
	TS_TRN_BGN datetime, 
	TS_TRN_END datetime, 
	FL_TRG_TRN bit NULL, 
	FL_KY_OFL bit NULL, 
	FL_CNCL bit NULL, 
	FL_VD bit NULL, 
	FL_SPN bit NULL, 
	ID_TRN_ADTN_VCHR int NULL, 
	PRIMARY KEY (ID_TRN)
   )
    
   CREATE TABLE CO_TLOG 
   (	
    ID_TLOG int IDENTITY (1, 1) NOT NULL, 
	NOM_TLOG VARCHAR(100), 
	DES_CLAVE int NULL, 
	STATUS 			VARCHAR(1),
	FEC_TLOG datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (ID_TLOG)
   )
   
   CREATE UNIQUE INDEX CO_TLOG_PK ON CO_TLOG (ID_TLOG) 
   
   CREATE TABLE CO_PRM_PRV
   (
	ID_PRM_PRV 	int IDENTITY (1, 1) NOT NULL, 
	CD_PRM 		VARCHAR(20), 
	DES_PRM 	VARCHAR(255), 
	CD_PRV 		VARCHAR(20), 
	PRIMARY KEY (ID_PRM_PRV)
   )
   
   CREATE TABLE CO_TKT_DT 
   (
 	ID_TRN INT NOT NULL,
 	SQ_NBR INT NOT NULL,
 	CD_TKT VARCHAR(10),
 	TKT_TYP INT NOT NULL DEFAULT 0,
 	QTY  INT NOT NULL DEFAULT 0,
 	ORD_NUM VARCHAR(2000),
 	PRIMARY KEY(ID_TRN, SQ_NBR)
	)
	
	CREATE TABLE CO_ITM_SLS_MAY
   (	
	ID_TRN 			int NOT NULL, 
	AI_LN_ITM 		int NOT NULL, 
	AI_LN_ITM_MAY 	int NOT NULL, 
	PRIMARY KEY (ID_TRN, AI_LN_ITM, AI_LN_ITM_MAY)
   )
   
   ALTER TABLE AS_ITM ADD FOREIGN KEY (ID_MRHRC_GP) REFERENCES CO_MRHRC_GP (ID_MRHRC_GP)
   ALTER TABLE AS_ITM_STR ADD FOREIGN KEY (ID_BSN_UN) REFERENCES PA_STR_RTL (ID_BSN_UN)
   ALTER TABLE AS_SF ADD FOREIGN KEY (ID_RPSTY_TND) REFERENCES AS_RPSTY_TND (ID_RPSTY_TND)
   ALTER TABLE AS_TL ADD FOREIGN KEY (ID_RPSTY_TND) REFERENCES AS_RPSTY_TND (ID_RPSTY_TND)
   ALTER TABLE AS_TL_OPR ADD FOREIGN KEY (ID_RPSTY_TND) REFERENCES AS_TL (ID_RPSTY_TND)
   ALTER TABLE AS_TL_WS ADD FOREIGN KEY (ID_RPSTY_TND) REFERENCES AS_TL (ID_RPSTY_TND)
   ALTER TABLE AS_WS ADD FOREIGN KEY (ID_BSN_UN) REFERENCES PA_STR_RTL (ID_BSN_UN)
   ALTER TABLE CO_ALS_ELTNC_CPN_ITM_CD ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE CO_ALS_ELTNC_CPN_ITM_CD ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_ASSC_CPN ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_AUT_CPN_DTA ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_BNS_RDM_PNTS ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE CO_BNS_RDM_PNTS ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_CPN_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE CO_CPN_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_CPN_TRCKNG ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_GASTO_EFE_CER ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_MRHRC_GP ADD FOREIGN KEY (ID_DPT_PS) REFERENCES ID_DPT_PS (ID_DPT_PS)
   ALTER TABLE CO_PRFRD_CT_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_PRFRD_CT_SCN_PNT_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_RDM_CPN_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE CO_RDM_CPN_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_REL_CER ADD FOREIGN KEY (ID_CPR) REFERENCES CO_CPR_CER (ID_CPR)
   ALTER TABLE CO_RTNC_CER ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_USED_TGTD_CPNS ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_VALE_EMP_CER ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_RESERVA ADD FOREIGN KEY (ID_ITM,ID_BSN_UN) REFERENCES AS_ITM_STR (ID_ITM,ID_BSN_UN)
   ALTER TABLE EXCPTN_LOG ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE EXCPTN_LOG ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE LO_EXTDST ADD FOREIGN KEY (ID_RPSTY_TND) REFERENCES AS_RPSTY_TND (ID_RPSTY_TND)
   ALTER TABLE MGR_OVRD ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE MGR_OVRD ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE RTNC_USD ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE TR_BSN_EOD ADD FOREIGN KEY (ID_TRN) REFERENCES TR_CTL (ID_TRN)
   ALTER TABLE TR_CTL_TND ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN) 
   ALTER TABLE TR_DS_TND ADD FOREIGN KEY (ID_RPSTY_TND_FM) REFERENCES AS_SF (ID_RPSTY_TND)
   ALTER TABLE TR_DS_TND ADD FOREIGN KEY (ID_RPSTY_TND_TO) REFERENCES LO_EXTDST (ID_RPSTY_TND)
   ALTER TABLE TR_DS_TND ADD FOREIGN KEY (ID_TRN) REFERENCES TR_CTL_TND (ID_TRN)
   ALTER TABLE TR_INVC ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE CO_FERRI_ALM ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE CO_DEDUCIBLE ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE TR_LON_TND ADD FOREIGN KEY (ID_TRN) REFERENCES TR_CTL_TND (ID_TRN)
   ALTER TABLE TR_LTM_MDF ADD FOREIGN KEY (ID_TRN, AI_LN_ITM) REFERENCES TR_LTM_RTL_TRN (ID_TRN, AI_LN_ITM)
   ALTER TABLE TR_LTM_MOTO_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_CRD_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_CHK_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_BILL_DT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_BON_SOL ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_TND_PINPAD ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_DSC_EMP ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_DSC_EMP_TOT ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE CO_CPN_PRM_DTA ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_PTS_PRM_DTA ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
--   ALTER TABLE CO_ASSOCIATED_DATA ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE CO_DATOS_EMP ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE CO_REC_ELEC ADD FOREIGN KEY (ID_TRN) REFERENCES TR_TRN (ID_TRN)
   ALTER TABLE TR_LTM_RTL_TRN ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE TR_LTM_SLS_RTN ADD FOREIGN KEY (ID_ITM) REFERENCES AS_ITM (ID_ITM) 
   ALTER TABLE TR_LTM_SLS_RTN ADD FOREIGN KEY (ID_TRN, AI_LN_ITM) REFERENCES TR_LTM_RTL_TRN (ID_TRN, AI_LN_ITM)
   ALTER TABLE TR_LTM_TND ADD FOREIGN KEY (ID_TND) REFERENCES AS_TND (ID_TND)
   ALTER TABLE TR_LTM_TND ADD FOREIGN KEY (ID_CNY_FRG) REFERENCES CO_CNY (ID_CNY)
   ALTER TABLE TR_LTM_TND_CTL_TND ADD FOREIGN KEY (ID_TND) REFERENCES AS_TND (ID_TND)
   ALTER TABLE TR_LTM_TND_CTL_TND ADD FOREIGN KEY (ID_CNY) REFERENCES CO_CNY (ID_CNY)
   ALTER TABLE TR_LTM_TND_CTL_TND ADD FOREIGN KEY (ID_TRN) REFERENCES TR_CTL_TND (ID_TRN)
   ALTER TABLE TR_LTM_TX ADD FOREIGN KEY (ID_TRN, AI_LN_ITM) REFERENCES TR_LTM_RTL_TRN (ID_TRN, AI_LN_ITM)
   ALTER TABLE TR_PKP_TND ADD FOREIGN KEY (ID_TRN) REFERENCES TR_CTL_TND (ID_TRN)
   ALTER TABLE TR_RCP_TND ADD FOREIGN KEY (ID_RPSTY_TND_TO) REFERENCES AS_SF (ID_RPSTY_TND)
   ALTER TABLE TR_RCP_TND ADD FOREIGN KEY (ID_RPSTY_TND_FM) REFERENCES LO_EXTDST (ID_RPSTY_TND)
   ALTER TABLE TR_RCP_TND ADD FOREIGN KEY (ID_TRN) REFERENCES TR_CTL_TND (ID_TRN)
   ALTER TABLE TR_SGN_OFF ADD FOREIGN KEY (ID_TRN) REFERENCES TR_CTL (ID_TRN)
   ALTER TABLE TR_SGN_ON ADD FOREIGN KEY (ID_TRN) REFERENCES TR_CTL (ID_TRN)
   ALTER TABLE TR_STLM_TL ADD FOREIGN KEY (ID_TRN) REFERENCES TR_CTL_TND (ID_TRN)
   ALTER TABLE TR_TOT_RTL ADD FOREIGN KEY (ID_TRN) REFERENCES TR_RTL (ID_TRN)
   ALTER TABLE TR_TOT_RTL ADD FOREIGN KEY (ID_TR_TOT_TYP) REFERENCES TR_TOT_TYP (ID_TR_TOT_TYP)
   ALTER TABLE TR_TRN ADD FOREIGN KEY (ID_BSN_UN) REFERENCES PA_STR_RTL (ID_BSN_UN)
   ALTER TABLE TR_TRN ADD FOREIGN KEY (ID_OPR) REFERENCES PA_OPR (ID_OPR)
   ALTER TABLE TR_TRN ADD FOREIGN KEY (ID_WS) REFERENCES AS_WS (ID_WS);
   
   
