USE [master]
GO
----------------------
-- CREATE ARTS_EC DB--
----------------------
CREATE DATABASE [ARTS_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ARTS_EC', FILENAME = N'C:\ALLC\DBDATA\ARTS_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ARTS_EC_log', FILENAME = N'C:\ALLC\DBDATA\ARTS_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ARTS_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [ARTS_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ARTS_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ARTS_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ARTS_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ARTS_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [ARTS_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ARTS_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ARTS_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [ARTS_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ARTS_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ARTS_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ARTS_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ARTS_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ARTS_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ARTS_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ARTS_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ARTS_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ARTS_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ARTS_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ARTS_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ARTS_EC] SET  READ_WRITE 
GO
ALTER DATABASE [ARTS_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ARTS_EC] SET  MULTI_USER 
GO
ALTER DATABASE [ARTS_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ARTS_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ARTS_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ARTS_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [ARTS_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [ARTS_EC] WITH PASSWORD=N'ARTS_EC', DEFAULT_DATABASE=[ARTS_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [ARTS_EC]
GO
CREATE SCHEMA [ARTS_EC] AUTHORIZATION [dbo]
GO
CREATE USER [ARTS_EC] FOR LOGIN [ARTS_EC] WITH DEFAULT_SCHEMA=[ARTS_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[ARTS_EC] TO [ARTS_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [ARTS_EC]
GO

----------------------
-- CREATE COTZ_EC DB--
----------------------

CREATE DATABASE [COTZ_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COTZ_EC', FILENAME = N'C:\ALLC\DBDATA\COTZ_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'COTZ_EC_log', FILENAME = N'C:\ALLC\DBDATA\COTZ_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [COTZ_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [COTZ_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [COTZ_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [COTZ_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [COTZ_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [COTZ_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [COTZ_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [COTZ_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [COTZ_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [COTZ_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [COTZ_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [COTZ_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [COTZ_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [COTZ_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [COTZ_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [COTZ_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [COTZ_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [COTZ_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [COTZ_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [COTZ_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [COTZ_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [COTZ_EC] SET  READ_WRITE 
GO
ALTER DATABASE [COTZ_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [COTZ_EC] SET  MULTI_USER 
GO
ALTER DATABASE [COTZ_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [COTZ_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [COTZ_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [COTZ_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [COTZ_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [COTZ_EC] WITH PASSWORD=N'COTZ_EC', DEFAULT_DATABASE=[COTZ_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [COTZ_EC]
GO
CREATE SCHEMA [COTZ_EC] AUTHORIZATION [dbo]
GO
CREATE USER [COTZ_EC] FOR LOGIN [COTZ_EC] WITH DEFAULT_SCHEMA=[COTZ_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[COTZ_EC] TO [COTZ_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [COTZ_EC]
GO

----------------------
-- CREATE CRM_EC DB--
----------------------

CREATE DATABASE [CRM_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CRM_EC', FILENAME = N'C:\ALLC\DBDATA\CRM_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CRM_EC_log', FILENAME = N'C:\ALLC\DBDATA\CRM_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CRM_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [CRM_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CRM_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CRM_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CRM_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CRM_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [CRM_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CRM_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CRM_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [CRM_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CRM_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CRM_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CRM_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CRM_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CRM_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CRM_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CRM_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CRM_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CRM_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CRM_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CRM_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CRM_EC] SET  READ_WRITE 
GO
ALTER DATABASE [CRM_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CRM_EC] SET  MULTI_USER 
GO
ALTER DATABASE [CRM_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CRM_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CRM_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CRM_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [CRM_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [CRM_EC] WITH PASSWORD=N'CRM_EC', DEFAULT_DATABASE=[CRM_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [CRM_EC]
GO
CREATE SCHEMA [CRM_EC] AUTHORIZATION [dbo]
GO
CREATE USER [CRM_EC] FOR LOGIN [CRM_EC] WITH DEFAULT_SCHEMA=[CRM_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[CRM_EC] TO [CRM_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [CRM_EC]
GO

----------------------
-- CREATE CVMT_EC DB--
----------------------

CREATE DATABASE [CVMT_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CVMT_EC', FILENAME = N'C:\ALLC\DBDATA\CVMT_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CVMT_EC_log', FILENAME = N'C:\ALLC\DBDATA\CVMT_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CVMT_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [CVMT_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CVMT_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CVMT_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CVMT_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CVMT_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [CVMT_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CVMT_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CVMT_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [CVMT_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CVMT_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CVMT_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CVMT_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CVMT_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CVMT_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CVMT_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CVMT_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CVMT_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CVMT_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CVMT_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CVMT_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CVMT_EC] SET  READ_WRITE 
GO
ALTER DATABASE [CVMT_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CVMT_EC] SET  MULTI_USER 
GO
ALTER DATABASE [CVMT_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CVMT_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CVMT_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CVMT_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [CVMT_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [CVMT_EC] WITH PASSWORD=N'CVMT_EC', DEFAULT_DATABASE=[CVMT_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [CVMT_EC]
GO
CREATE SCHEMA [CVMT_EC] AUTHORIZATION [dbo]
GO
CREATE USER [CVMT_EC] FOR LOGIN [CVMT_EC] WITH DEFAULT_SCHEMA=[CVMT_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[CVMT_EC] TO [CVMT_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [CVMT_EC]
GO

----------------------
-- CREATE DEVS_EC DB--
----------------------

CREATE DATABASE [DEVS_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DEVS_EC', FILENAME = N'C:\ALLC\DBDATA\DEVS_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DEVS_EC_log', FILENAME = N'C:\ALLC\DBDATA\DEVS_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [DEVS_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [DEVS_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DEVS_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DEVS_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DEVS_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DEVS_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [DEVS_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DEVS_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DEVS_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [DEVS_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DEVS_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DEVS_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DEVS_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DEVS_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DEVS_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DEVS_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DEVS_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DEVS_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DEVS_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DEVS_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DEVS_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DEVS_EC] SET  READ_WRITE 
GO
ALTER DATABASE [DEVS_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DEVS_EC] SET  MULTI_USER 
GO
ALTER DATABASE [DEVS_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DEVS_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DEVS_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DEVS_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [DEVS_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [DEVS_EC] WITH PASSWORD=N'DEVS_EC', DEFAULT_DATABASE=[DEVS_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [DEVS_EC]
GO
CREATE SCHEMA [DEVS_EC] AUTHORIZATION [dbo]
GO
CREATE USER [DEVS_EC] FOR LOGIN [DEVS_EC] WITH DEFAULT_SCHEMA=[DEVS_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[DEVS_EC] TO [DEVS_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [DEVS_EC]
GO

----------------------
-- CREATE EYES_EC DB--
----------------------

CREATE DATABASE [EYES_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EYES_EC', FILENAME = N'C:\ALLC\DBDATA\EYES_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EYES_EC_log', FILENAME = N'C:\ALLC\DBDATA\EYES_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [EYES_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [EYES_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EYES_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EYES_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EYES_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EYES_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [EYES_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EYES_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EYES_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [EYES_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EYES_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EYES_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EYES_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EYES_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EYES_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EYES_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EYES_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EYES_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EYES_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EYES_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EYES_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EYES_EC] SET  READ_WRITE 
GO
ALTER DATABASE [EYES_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EYES_EC] SET  MULTI_USER 
GO
ALTER DATABASE [EYES_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EYES_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [EYES_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [EYES_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [EYES_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [EYES_EC] WITH PASSWORD=N'EYES_EC', DEFAULT_DATABASE=[EYES_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [EYES_EC]
GO
CREATE SCHEMA [EYES_EC] AUTHORIZATION [dbo]
GO
CREATE USER [EYES_EC] FOR LOGIN [EYES_EC] WITH DEFAULT_SCHEMA=[EYES_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[EYES_EC] TO [EYES_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [EYES_EC]
GO

----------------------
-- CREATE OPERAC_EC DB--
----------------------

CREATE DATABASE [OPERAC_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OPERAC_EC', FILENAME = N'C:\ALLC\DBDATA\OPERAC_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OPERAC_EC_log', FILENAME = N'C:\ALLC\DBDATA\OPERAC_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [OPERAC_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [OPERAC_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OPERAC_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OPERAC_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OPERAC_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OPERAC_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [OPERAC_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OPERAC_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OPERAC_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [OPERAC_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OPERAC_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OPERAC_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OPERAC_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OPERAC_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OPERAC_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OPERAC_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OPERAC_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OPERAC_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OPERAC_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OPERAC_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OPERAC_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OPERAC_EC] SET  READ_WRITE 
GO
ALTER DATABASE [OPERAC_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OPERAC_EC] SET  MULTI_USER 
GO
ALTER DATABASE [OPERAC_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OPERAC_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [OPERAC_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [OPERAC_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [OPERAC_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [OPERAC_EC] WITH PASSWORD=N'OPERAC_EC', DEFAULT_DATABASE=[OPERAC_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [OPERAC_EC]
GO
CREATE SCHEMA [OPERAC_EC] AUTHORIZATION [dbo]
GO
CREATE USER [OPERAC_EC] FOR LOGIN [OPERAC_EC] WITH DEFAULT_SCHEMA=[OPERAC_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[OPERAC_EC] TO [OPERAC_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [OPERAC_EC]
GO

----------------------
-- CREATE PRCFLJ_EC DB--
----------------------

CREATE DATABASE [PRCFLJ_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRCFLJ_EC', FILENAME = N'C:\ALLC\DBDATA\PRCFLJ_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PRCFLJ_EC_log', FILENAME = N'C:\ALLC\DBDATA\PRCFLJ_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [PRCFLJ_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [PRCFLJ_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [PRCFLJ_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PRCFLJ_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PRCFLJ_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PRCFLJ_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PRCFLJ_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PRCFLJ_EC] SET  READ_WRITE 
GO
ALTER DATABASE [PRCFLJ_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PRCFLJ_EC] SET  MULTI_USER 
GO
ALTER DATABASE [PRCFLJ_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PRCFLJ_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [PRCFLJ_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [PRCFLJ_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [PRCFLJ_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [PRCFLJ_EC] WITH PASSWORD=N'PRCFLJ_EC', DEFAULT_DATABASE=[PRCFLJ_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [PRCFLJ_EC]
GO
CREATE SCHEMA [PRCFLJ_EC] AUTHORIZATION [dbo]
GO
CREATE USER [PRCFLJ_EC] FOR LOGIN [PRCFLJ_EC] WITH DEFAULT_SCHEMA=[PRCFLJ_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[PRCFLJ_EC] TO [PRCFLJ_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [PRCFLJ_EC]
GO

----------------------
-- CREATE RACE_EC DB--
----------------------

CREATE DATABASE [RACE_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RACE_EC', FILENAME = N'C:\ALLC\DBDATA\RACE_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RACE_EC_log', FILENAME = N'C:\ALLC\DBDATA\RACE_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [RACE_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [RACE_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RACE_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RACE_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RACE_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RACE_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [RACE_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RACE_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RACE_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [RACE_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RACE_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RACE_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RACE_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RACE_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RACE_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RACE_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RACE_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RACE_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RACE_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RACE_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RACE_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RACE_EC] SET  READ_WRITE 
GO
ALTER DATABASE [RACE_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RACE_EC] SET  MULTI_USER 
GO
ALTER DATABASE [RACE_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RACE_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [RACE_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [RACE_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [RACE_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [RACE_EC] WITH PASSWORD=N'RACE_EC', DEFAULT_DATABASE=[RACE_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [RACE_EC]
GO
CREATE SCHEMA [RACE_EC] AUTHORIZATION [dbo]
GO
CREATE USER [RACE_EC] FOR LOGIN [RACE_EC] WITH DEFAULT_SCHEMA=[RACE_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[RACE_EC] TO [RACE_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [RACE_EC]
GO

----------------------
-- CREATE SAADMIN DB--
----------------------

CREATE DATABASE [SAADMIN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SAADMIN', FILENAME = N'C:\ALLC\DBDATA\SAADMIN.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SAADMIN_log', FILENAME = N'C:\ALLC\DBDATA\SAADMIN_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SAADMIN] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [SAADMIN] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SAADMIN] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SAADMIN] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SAADMIN] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SAADMIN] SET ARITHABORT OFF 
GO
ALTER DATABASE [SAADMIN] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SAADMIN] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SAADMIN] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [SAADMIN] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SAADMIN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SAADMIN] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SAADMIN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SAADMIN] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SAADMIN] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SAADMIN] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SAADMIN] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SAADMIN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SAADMIN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SAADMIN] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SAADMIN] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SAADMIN] SET  READ_WRITE 
GO
ALTER DATABASE [SAADMIN] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SAADMIN] SET  MULTI_USER 
GO
ALTER DATABASE [SAADMIN] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SAADMIN] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [SAADMIN] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SAADMIN]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SAADMIN] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [SAADMIN] WITH PASSWORD=N'SAADMIN', DEFAULT_DATABASE=[SAADMIN], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [SAADMIN]
GO
CREATE SCHEMA [SAADMIN] AUTHORIZATION [dbo]
GO
CREATE USER [SAADMIN] FOR LOGIN [SAADMIN] WITH DEFAULT_SCHEMA=[SAADMIN]
GO
ALTER AUTHORIZATION ON SCHEMA::[SAADMIN] TO [SAADMIN]
GO
ALTER ROLE [db_owner] ADD MEMBER [SAADMIN]
GO

----------------------
-- CREATE TDVAL_EC DB--
----------------------

CREATE DATABASE [TDVAL_EC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TDVAL_EC', FILENAME = N'C:\ALLC\DBDATA\TDVAL_EC.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TDVAL_EC_log', FILENAME = N'C:\ALLC\DBDATA\TDVAL_EC_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [TDVAL_EC] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [TDVAL_EC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TDVAL_EC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TDVAL_EC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TDVAL_EC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TDVAL_EC] SET ARITHABORT OFF 
GO
ALTER DATABASE [TDVAL_EC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TDVAL_EC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TDVAL_EC] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [TDVAL_EC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TDVAL_EC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TDVAL_EC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TDVAL_EC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TDVAL_EC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TDVAL_EC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TDVAL_EC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TDVAL_EC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TDVAL_EC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TDVAL_EC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TDVAL_EC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TDVAL_EC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TDVAL_EC] SET  READ_WRITE 
GO
ALTER DATABASE [TDVAL_EC] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TDVAL_EC] SET  MULTI_USER 
GO
ALTER DATABASE [TDVAL_EC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TDVAL_EC] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [TDVAL_EC] SET DELAYED_DURABILITY = DISABLED 
GO
USE [TDVAL_EC]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [TDVAL_EC] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE LOGIN [TDVAL_EC] WITH PASSWORD=N'TDVAL_EC', DEFAULT_DATABASE=[TDVAL_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [TDVAL_EC]
GO
CREATE SCHEMA [TDVAL_EC] AUTHORIZATION [dbo]
GO
CREATE USER [TDVAL_EC] FOR LOGIN [TDVAL_EC] WITH DEFAULT_SCHEMA=[TDVAL_EC]
GO
ALTER AUTHORIZATION ON SCHEMA::[TDVAL_EC] TO [TDVAL_EC]
GO
ALTER ROLE [db_owner] ADD MEMBER [TDVAL_EC]
GO