USE [PRCFLJ_EC]
GO
CREATE LOGIN [CER_BALANZA] WITH PASSWORD='CER_BALANZA', DEFAULT_DATABASE=[PRCFLJ_EC], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [CER_BALANZA] ENABLE
GO
/****** Object:  User [CER_BALANZA]    Script Date: 9/20/2016 2:35:07 PM ******/
CREATE USER [CER_BALANZA] FOR LOGIN [CER_BALANZA] WITH DEFAULT_SCHEMA=[PRCFLJ_EC]
GO
GRANT CONNECT TO [CER_BALANZA] AS [dbo]
GO
GRANT ALTER ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT CONTROL ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT DELETE ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT INSERT ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT REFERENCES ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT SELECT ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT TAKE OWNERSHIP ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT UPDATE ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT VIEW DEFINITION ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT VIEW CHANGE TRACKING ON [dbo].[ARTICBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT REFERENCES ON [dbo].[T_USERBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT SELECT ON [dbo].[T_USERBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT TAKE OWNERSHIP ON [dbo].[T_USERBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT UPDATE ON [dbo].[T_USERBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT VIEW DEFINITION ON [dbo].[T_USERBALANZA] TO [CER_BALANZA] AS [dbo]
GO
GRANT VIEW CHANGE TRACKING ON [dbo].[T_USERBALANZA] TO [CER_BALANZA] AS [dbo];