USE CRM_EC
GO

  CREATE TABLE MN_DATACRM 
   (	
    COD_DATACRM int IDENTITY (1, 1) NOT NULL, 
	DES_DATACRM VARCHAR(200), 
	TIPO_DATACRM int NULL, 
	IND_ACTIVO int NULL, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(), 
	AMBITO int NULL,
	PRIMARY KEY (COD_DATACRM)
   )
   
  CREATE UNIQUE INDEX MN_DATACRM_PK ON MN_DATACRM (COD_DATACRM) 
   
  CREATE TABLE MN_DATACRMOPC 
   (	
    COD_DATACRMOPC int IDENTITY (1, 1) NOT NULL, 
	COD_DATACRM int NULL, 
	DES_DATACRMOPC VARCHAR(200), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (COD_DATACRMOPC)
   )
   
  CREATE UNIQUE INDEX MN_DATACRMOPC_PK ON MN_DATACRMOPC (COD_DATACRMOPC) 
   
  CREATE TABLE MN_DEMOGRAF 
   (	
    COD_DEMOGRAF int IDENTITY (1, 1) NOT NULL, 
	DES_DEMOGRAF VARCHAR(200), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (COD_DEMOGRAF)
   ) 
   
  CREATE UNIQUE INDEX MN_DEMOGRAF_PK ON MN_DEMOGRAF (COD_DEMOGRAF)
   
  CREATE TABLE MN_ESTADO 
   (	
    COD_ESTADO int IDENTITY (1, 1) NOT NULL, 
	DES_ESTADO VARCHAR(50), 
	COL_ESTADO CHAR(6), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(), 
	ABR_ESTADO VARCHAR(18), 
	CSF_ESTADO VARCHAR(200), 
	VAL_ESTADO int NULL,
	PRIMARY KEY (COD_ESTADO)
   ) 
   
  CREATE UNIQUE INDEX MN_ESTADO_PK ON MN_ESTADO (COD_ESTADO)
   
  CREATE TABLE MN_EST_TARJETA 
   (	
    COD_EST_TARJETA int IDENTITY (1, 1) NOT NULL, 
	DES_EST_TARJETA VARCHAR(200), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(), 
	COL_ESTADO VARCHAR(6), 
	CSF_ESTADO VARCHAR(200),
	PRIMARY KEY (COD_EST_TARJETA)
   )
   
  CREATE UNIQUE INDEX MN_EST_TARJETA_PK ON MN_EST_TARJETA (COD_EST_TARJETA) 
   
  CREATE TABLE MN_INGRESO 
   (	
    COD_INGRESO int IDENTITY (1, 1) NOT NULL, 
	MIN_INGRESO int NULL, 
	MAX_INGRESO int NULL, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (COD_INGRESO)
   )
   
  CREATE UNIQUE INDEX MN_INGRESO_PK ON MN_INGRESO (COD_INGRESO) 
   
  CREATE TABLE MN_TIPO_TARJETA 
   (	
    COD_TIPO_TARJETA int IDENTITY (1, 1) NOT NULL, 
	DES_TIPO_TARJETA VARCHAR(200), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (COD_TIPO_TARJETA)
   )
   
  CREATE UNIQUE INDEX MN_TIPO_TARJETA_PK ON MN_TIPO_TARJETA (COD_TIPO_TARJETA) 
   
  CREATE TABLE OP_ACTIVIDAD 
   (	
    COD_CLIENTE bigint NULL, 
	TOT_PUNTOS int NOT NULL DEFAULT 0, 
	TOT_TRANS int NOT NULL DEFAULT 0, 
	PTOS_REEMBOLSO int NOT NULL DEFAULT 0, 
	AUTO_MONTO_TIENDA int NOT NULL DEFAULT 0, 
	ULT_FECHA_COMPRA datetime, 
	ULT_ASIGNA_PUNTO int NULL, 
	NIVEL_CLIENTE int NULL, 
	NUM_MENSAJE int NULL, 
	TAR_COUPONID int NULL, 
	COD_GRPDSCTO int NULL, 
	MULTIPLICADOR int NULL, 
	ALT_NUM_CLIENTE int NULL, 
	ULT_FEC_REEMBOLSO datetime, 
	COD_CAMPANIA int NULL, 
	FEC_INI_CAMPANIA datetime, 
	TOT_PTOS_CAMPANIA int NULL, 
	NUM_TRAN_CAMPANIA int NULL, 
	TOT_REEMB_CAMPANIA int NULL, 
	SALDO_VTAS_CAMPANIA int NULL, 
	IDREG int NOT NULL DEFAULT 0, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
  CREATE TABLE OP_CAMPANIA 
   (	
    COD_CAMPANIA int IDENTITY (1, 1) NOT NULL, 
	DES_CAMPANIA VARCHAR(200), 
	FECHA_INI datetime, 
	FECHA_TER datetime, 
	IND_ACTIVO int NULL, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (COD_CAMPANIA)
   )
   
  CREATE UNIQUE INDEX OP_CAMPANIA_PK ON OP_CAMPANIA (COD_CAMPANIA) 
   
  CREATE TABLE OP_CAMPANIA_MOV 
   (	
    MOV_CAMPANIA int IDENTITY (1, 1) NOT NULL, 
	COD_CAMPANIA int NULL, 
	FECHA_INI datetime, 
	FECHA_TER datetime, 
	IND_ACTIVO int NULL, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (MOV_CAMPANIA)
   ) 
   
  CREATE UNIQUE INDEX OP_CAMPANIA_MOV_PK ON OP_CAMPANIA_MOV (MOV_CAMPANIA) 
   
  CREATE TABLE OP_CLIENTE 
   (	
    COD_CLIENTE bigint IDENTITY (1, 1) NOT NULL, 
	COD_TIPOCLIENTE int NULL, 
	IDENTIFICACION VARCHAR(18), 
	COD_TIPOID int NULL, 
	NOMBRE VARCHAR(75), 
	APELLIDO_P VARCHAR(50), 
	APELLIDO_M VARCHAR(50), 
	GENERO VARCHAR(1), 
	FEC_NACIMIENTO datetime, 
	DIRECCION VARCHAR(200), 
	COD_REGION int not NULL DEFAULT 0, 
	COD_CIUDAD int NULL, 
	COD_POSTAL int NULL, 
	TEL_PARTICULAR VARCHAR(50), 
	TEL_OFICINA VARCHAR(50), 
	TEL_CELULAR VARCHAR(50), 
	EMAIL VARCHAR(200), 
	DIRECC_LINE2 VARCHAR(100), 
	COD_AREA_TEL_PART VARCHAR(4), 
	COD_AREA_TEL_OFIC VARCHAR(4), 
	NUM_LIC_COND VARCHAR(20), 
	EXT_LIC_COND VARCHAR(5), 
	NUM_SEGURO_SOC VARCHAR(10), 
	EXT_SEGURO_SOC VARCHAR(4), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(), 
	COD_POSTAL_ALFA VARCHAR(9), 
	PRIMARY KEY (COD_CLIENTE)
   )
   
  CREATE UNIQUE INDEX OP_CLIENTE_PK ON OP_CLIENTE (COD_CLIENTE) 
   
  CREATE TABLE OP_CLIENTEANT 
   (	
    COD_CLIENTE bigint NOT NULL, 
	COD_DATACRM int NULL, 
	DATA_CLIENTE VARCHAR(500), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
  CREATE TABLE OP_CLIENTEMPRC 
   (	
    COD_CLIENTE bigint NOT NULL, 
	COD_MARCAPRC int NULL, 
	IND_ACTIVO int NOT NULL DEFAULT 0
   )
   
  CREATE TABLE OP_DATACRM 
   (	
    COD_CLIENTE bigint NOT NULL, 
	COD_ESTADO int NOT NULL DEFAULT 1, 
	COD_NEGOCIO int NULL, 
	COD_TIENDA int NULL, 
	COD_INGRESO int NOT NULL DEFAULT 0, 
	COD_DEMOGRAF int NOT NULL DEFAULT 0, 
	FEC_REGISTRO datetime DEFAULT SYSDATETIMEOFFSET(), 
	TAM_FAMILIA int NOT NULL DEFAULT 1, 
	EDAD_HIJO1 int NULL, 
	EDAD_HIJO2 int NULL, 
	EDAD_HIJO3 int NULL, 
	EDAD_HIJO4 int NULL, 
	EDAD_HIJO5 int NULL, 
	EDAD_HIJO6 int NULL, 
	EDAD_HIJO7 int NULL, 
	TOT_AJUSTES int NULL, 
	TOT_REEMBOLSOS int NULL, 
	TOT_AJUSTE_PTOS_SUM int NULL, 
	TOT_AJUSTE_PTOS_RES int NULL, 
	ULTM_NUM_AJUSTE int NULL, 
	ULTM_NUM_REEMBOLSO int NULL, 
	ULTM_FEC_AJUSTE datetime, 
	ULTM_FEC_REEMBOLSO datetime, 
	FEC_ACTUALIZA datetime, 
	FEC_RESERVA datetime, 
	AUTORIZA_REF_CLIENTE VARCHAR(1), 
	ALIAS_REF_CLIENTE VARCHAR(1), 
	CUENTA_REFER int NULL, 
	NUM_MONTO_RESERVA int NULL, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
  CREATE TABLE OP_GRPDSCTO 
   (	
    COD_GRPDSCTO int IDENTITY (1, 1) NOT NULL, 
	DES_GRPDSCTO VARCHAR(200), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (COD_GRPDSCTO)
   )
   
  CREATE UNIQUE INDEX OP_GRPDSCTO_PK ON OP_GRPDSCTO (COD_GRPDSCTO) 
   
  CREATE TABLE OP_MARCAPRC 
   (	
    COD_MARCAPRC int IDENTITY (1, 1) NOT NULL, 
	DES_MARCAPRC VARCHAR(200), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (COD_MARCAPRC)
   ) 
   
  CREATE UNIQUE INDEX OP_MARCAPRC_PK ON OP_MARCAPRC (COD_MARCAPRC)
   
  CREATE TABLE OP_REG_PUNTOS 
   (	
    COD_CLIENTE bigint NOT NULL, 
	TIPO_TRANSAC int NULL, 
	FEC_TRANSAC datetime, 
	HRA_TRANSAC VARCHAR(5), 
	NUM_TERMINAL int NULL, 
	TRANSACCION int NULL, 
	OPERADOR int NULL, 
	SUM_PUNTOS int NULL, 
	RES_PUNTOS int NULL, 
	COD_NEGOCIO int NULL, 
	COD_TIENDA int NULL, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
  CREATE TABLE OP_TARJETAS 
   (	
    COD_TARJETA int IDENTITY (1, 1) NOT NULL, 
	COD_CLIENTE bigint NULL, 
	NUM_TARJETA VARCHAR(25), 
	COD_EST_TARJETA int NULL, 
	COD_TIPO_TARJETA int NULL, 
	FEC_ENTREGA datetime DEFAULT SYSDATETIMEOFFSET(), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
  CREATE TABLE PM_TIPOCLIENTE 
   (	
    COD_TIPOCLIENTE int IDENTITY (1, 1) NOT NULL, 
	DES_TIPOCLIENTE VARCHAR(200), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (COD_TIPOCLIENTE)
   )
   
  CREATE UNIQUE INDEX PM_TIPOCLIENTE_PK ON PM_TIPOCLIENTE (COD_TIPOCLIENTE) 
   
  CREATE TABLE PM_TIPOID 
   (	
    COD_TIPOID int IDENTITY (1, 1) NOT NULL, 
	TIPO_PERSONA int NULL, 
	DES_TIPOID VARCHAR(200), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (COD_TIPOID)
   )
   
  CREATE UNIQUE INDEX PM_TIPOID_PK ON PM_TIPOID (COD_TIPOID) 
  
  
  ALTER TABLE MN_DATACRMOPC ADD CONSTRAINT MN_DATACRMOPC_FK1 FOREIGN KEY (COD_DATACRM) REFERENCES MN_DATACRM (COD_DATACRM)
  ALTER TABLE OP_CAMPANIA_MOV ADD CONSTRAINT OP_CAMPANIA_MOV_FK1 FOREIGN KEY (COD_CAMPANIA) REFERENCES OP_CAMPANIA (COD_CAMPANIA)
  ALTER TABLE OP_CLIENTE ADD CONSTRAINT OP_CLIENTE_FK1 FOREIGN KEY (COD_TIPOCLIENTE) REFERENCES PM_TIPOCLIENTE (COD_TIPOCLIENTE)
  ALTER TABLE OP_CLIENTEANT ADD CONSTRAINT OP_CLIENTEANT_FK1 FOREIGN KEY (COD_CLIENTE) REFERENCES OP_CLIENTE (COD_CLIENTE)
  ALTER TABLE OP_CLIENTEMPRC ADD CONSTRAINT OP_CLIENTEMPRC_FK1 FOREIGN KEY (COD_CLIENTE) REFERENCES OP_CLIENTE (COD_CLIENTE)
  ALTER TABLE OP_DATACRM ADD CONSTRAINT OP_DATACRM_FK1 FOREIGN KEY (COD_CLIENTE) REFERENCES OP_CLIENTE (COD_CLIENTE)