USE CVMT_EC
GO

  CREATE TABLE CM_CARTAS 
   (	
    ID_CARTA int IDENTITY (1, 1) NOT NULL, 
	ID_TRN int NULL, 
	FECHA_C datetime DEFAULT SYSDATETIMEOFFSET(), 
	ESTADO int NOT NULL DEFAULT 0, 
	SRL_NBR VARCHAR(20),
	CC_OPERADOR int NULL, 
	DES_CLAVE int NULL, 
	FECHA_E datetime, 
	NOMBXML VARCHAR(200),
	COD_CANTON INT NULL DEFAULT 0,
	PRIMARY KEY (ID_CARTA)
   )
   
  CREATE UNIQUE INDEX CM_CARTAS_PK ON CM_CARTAS (ID_CARTA) 
  