USE EYES_EC
GO

  CREATE TABLE FE_MESSAGE 
   (	
    ID_MESSAGE int IDENTITY (1, 1) NOT NULL, 
	EVENT_DATE datetime, 
	CHANNEL VARCHAR(1), 
	PM_SOURCE VARCHAR(18), 
	MESSAGE_GROUP VARCHAR(1), 
	MESSAGE_NUMBER int NULL, 
	SOURCE_NUMBER VARCHAR(15), 
	EVENT_NUMBER VARCHAR(4), 
	SEVERITY int NOT NULL, 
	DATA VARCHAR(150), 
	ID_EQUIPO int NULL, 
	COD_USUARIO int NULL, 
	FEC_ACTUALIZACION datetime DEFAULT SYSDATETIMEOFFSET(),
	ID_LOCAL int NULL, 
	PRIMARY KEY (ID_MESSAGE)
   )
   
  CREATE UNIQUE INDEX XPKMESSAGE ON FE_MESSAGE (ID_MESSAGE) 
   
  CREATE TABLE FM_EQUIPO 
   (	
    ID_EQUIPO int IDENTITY (1, 1) NOT NULL, 
	DES_CLAVE VARCHAR(18), 
	DES_EQUIPO VARCHAR(25), 
	IP VARCHAR(15), 
	IND_ONLINE int NULL, 
	IND_ACTIVO int NULL, 
	ID_TIPO int NULL, 
	ID_LOCAL int NULL, 
	COD_USUARIO int NOT NULL DEFAULT 0, 
	FEC_ACTUALIZACION datetime DEFAULT SYSDATETIMEOFFSET(), 
	ID_NEGOCIO int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_EQUIPO)
   )
   
  CREATE UNIQUE INDEX XPKFP_DISPOSITIVO ON FM_EQUIPO (ID_EQUIPO) 
   
  CREATE TABLE FM_TIP_ESTADO 
   (	
    ID_TIP_ESTADO int IDENTITY (1, 1) NOT NULL, 
	VAL_TIP_ESTADO int NULL, 
	DES_TIP_ESTADO VARCHAR(75), 
	ABR_TIP_ESTADO VARCHAR(10), 
	BGCOLOR_TIP_ESTADO VARCHAR(7), 
	CSSFONT_TIP_ESTADO VARCHAR(250), 
	COD_USUARIO int NULL DEFAULT 0, 
	FEC_ACTUALIZACION datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (ID_TIP_ESTADO)
   ) 
   
  CREATE UNIQUE INDEX FM_TIP_ESTADO_PK ON FM_TIP_ESTADO (ID_TIP_ESTADO) 
   
  CREATE TABLE FM_TIPO_EQUIPO 
   (	
    ID_TIPO int IDENTITY (1, 1) NOT NULL, 
	COD_TIPO VARCHAR(3), 
	DES_TIPO VARCHAR(25), 
	COD_USUARIO int NULL DEFAULT 0, 
	FEC_ACTUALIZACION datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (ID_TIPO)
   )
   
  CREATE UNIQUE INDEX XPKFP_TIPO_DISPOSITIVO ON FM_TIPO_EQUIPO (ID_TIPO) 
  
     
  CREATE TABLE FM_TIP_SEVER 
   (	
    ID_TIP_SEVER int IDENTITY (1, 1) NOT NULL, 
    VAL_TIP_SEVER int NULL,
	DES_TIP_SEVER VARCHAR(75), 
	ABR_TIP_SEVER VARCHAR(10), 
	BGCOLOR_TIP_SEVER VARCHAR(7), 
	CSSFONT_TIP_SEVER VARCHAR(250), 
	COD_USUARIO int NULL DEFAULT 0, 
	FEC_ACTUALIZACION datetime DEFAULT SYSDATETIMEOFFSET(),
	PRIMARY KEY (ID_TIP_SEVER)
   )
   
  CREATE UNIQUE INDEX XPKFM_TIP_SEVER ON FM_TIP_SEVER (ID_TIP_SEVER) 
   
  CREATE TABLE FP_EJECUCION 
   (	
    ID_EJECUCION int IDENTITY (1, 1) NOT NULL, 
	ID_PROCESO int NULL, 
	EXECUTION_DATE datetime, 
	ID_EQUIPO int NULL, 
	TIP_ESTADO int NULL, 
	DATA VARCHAR(150), 
	COD_USUARIO int NULL, 
	FEC_ACTUALIZACION datetime DEFAULT SYSDATETIMEOFFSET(),
	ID_LOCAL int NULL, 
	PRIMARY KEY (ID_EJECUCION)
   )
   
  CREATE UNIQUE INDEX XPKFP_EJEC_PROC ON FP_EJECUCION (ID_EJECUCION)
   
  CREATE TABLE FP_INGRESO_MENSAJE 
   (	
    DES_TRAMA VARCHAR(250), 
	IND_PROCESADO int NULL
   ) 
   
  CREATE TABLE FP_MONITOR 
   (	
    ID_EQUIPO int NOT NULL, 
	ID_PROCESO int NOT NULL, 
	TIP_ESTADO int NULL, 
	ID_LOCAL int NULL, 
	ID_NEGOCIO int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_EQUIPO,ID_PROCESO)
   )
   
  CREATE UNIQUE INDEX XPKFP_MONITOR ON FP_MONITOR (ID_EQUIPO, ID_PROCESO) 
   
  CREATE TABLE FP_MONITOR_DET 
   (	
    ID_EQUIPO int NOT NULL, 
	ID_PROCESO int NOT NULL, 
	ID_EJECUCION int NOT NULL,
	PRIMARY KEY (ID_EQUIPO,ID_PROCESO,ID_EJECUCION)
   )
   
  CREATE UNIQUE INDEX XPKFP_MONITOR_MSG ON FP_MONITOR_DET (ID_EQUIPO, ID_PROCESO, ID_EJECUCION) 
   
  CREATE TABLE FP_PROCESO 
   (	
    ID_PROCESO int IDENTITY (1, 1) NOT NULL, 
	DES_CLAVE VARCHAR(18) NOT NULL, 
	DES_PROCESO VARCHAR(50), 
	COD_USUARIO int NULL DEFAULT 0, 
	FEC_ACTUALIZACION datetime DEFAULT SYSDATETIMEOFFSET(), 
	ABR_PROCESO VARCHAR(18),
	PRIMARY KEY (ID_PROCESO)
   )
   
  CREATE UNIQUE INDEX XPKFP_PROCESO ON FP_PROCESO (ID_PROCESO) 
  
  ALTER TABLE FM_EQUIPO ADD CONSTRAINT R_10 FOREIGN KEY (ID_TIPO) REFERENCES FM_TIPO_EQUIPO (ID_TIPO) ON DELETE SET NULL
  ALTER TABLE FP_EJECUCION ADD CONSTRAINT R_3 FOREIGN KEY (ID_PROCESO) REFERENCES FP_PROCESO (ID_PROCESO) ON DELETE SET NULL
  ALTER TABLE FP_MONITOR ADD CONSTRAINT R_14 FOREIGN KEY (ID_PROCESO) REFERENCES FP_PROCESO (ID_PROCESO)
  ALTER TABLE FP_MONITOR_DET ADD CONSTRAINT R_16 FOREIGN KEY (ID_EQUIPO, ID_PROCESO) REFERENCES FP_MONITOR (ID_EQUIPO, ID_PROCESO)
  
  CREATE TABLE STR_STS
  (
  	ID_STR_STS 		int IDENTITY (1, 1) NOT NULL,
  	TML				int NULL,
  	STR_CD			int NOT NULL,
  	LOG_NM			VARCHAR(8),
  	NMB_CL			int NULL,
  	CL_FL			int NULL,
  	DT_TM			DATETIME NULL,
  	MNTR			int NULL,
  	CL_CTL_FL		int NULL,
  	INDICAT_0		int NULL,
  	INDICAT_1		int NULL,
  	RSRVD			VARCHAR(46) NULL,
  	PRIMARY KEY (ID_STR_STS)
  )
  
    CREATE TABLE WS_STS
  (
  	ID_WS_STS 		int IDENTITY (1, 1) NOT NULL,
  	PRD				int NOT NULL,
  	TML				int NOT NULL,
  	OPR				int NULL,
  	STR_CD			int NOT NULL,
  	TRN_NMB			int NULL,
  	NMB_LO			int NULL,
  	AMT_LO			int NULL,
  	NMB_PKP			int NULL,
  	AMT_PKP			int NULL,
  	GS_PSTV			int NULL,
  	GS_NV			int NULL,
  	AMT_MSC			int NULL,
  	NMB_TRN			int NULL,
  	TL_AMT_CSH		int NULL,
  	TL_AMT_CHK		int NULL,
  	TL_AMT_FDS		int NULL,
  	TL_AMT_MSC_1	int NULL,
  	TL_AMT_MSC_2	int NULL,
  	TL_AMT_MSC_3	int NULL,
  	TL_AMT_MF		int NULL,
  	TL_AMT_STR		int NULL,
  	TRN_TY			int NULL,
  	STS				int NULL,
  	STS_2			int NULL,
  	ULT_NUM_FACT 	VARCHAR(15),
  	PRIMARY KEY (ID_WS_STS)
  )
  
  CREATE TABLE CFG_PINPAD
   (	
    IDPINPAD int IDENTITY NOT NULL, 
	COD_TIENDA int NOT NULL, 
	DIR_IP VARCHAR(15) NOT NULL DEFAULT '',
	MASCARA VARCHAR(15) NOT NULL DEFAULT '', 
	GATEWAY VARCHAR(15) NOT NULL DEFAULT '',
	DIR_IP_HP_RA VARCHAR(15) NOT NULL DEFAULT '',
	PRT_HP_RA VARCHAR(6) NOT NULL DEFAULT '',
	DIR_IP_HA_RA VARCHAR(15) NOT NULL DEFAULT '',
	PRT_HA_RA VARCHAR(6) NOT NULL DEFAULT '',
	DIR_IP_HP_RB VARCHAR(15) NOT NULL DEFAULT '',
	PRT_HP_RB VARCHAR(6) NOT NULL DEFAULT '',
	DIR_IP_HA_RB VARCHAR(15) NOT NULL DEFAULT '',
	PRT_HA_RB VARCHAR(6) NOT NULL DEFAULT '',
	PRT_ESCH VARCHAR(6) NOT NULL DEFAULT '',
	TID_DATA VARCHAR(8) NOT NULL DEFAULT '',
	TID_MED VARCHAR(8) NOT NULL DEFAULT '',
	CID_CAJA VARCHAR(15) NOT NULL DEFAULT '               ',
	FECHA_ULT_CIERRE datetime DEFAULT SYSDATETIMEOFFSET(),
	ACTUALIZAR int NULL DEFAULT 0, 
	IDP_LCL int DEFAULT 0,
	PRIMARY KEY (IDPINPAD)
   )
   
   CREATE TABLE CFG_LOTE_PINPAD
   (	
    DES_CLAVE int NOT NULL, 
	NUM_LOT_R_DATA VARCHAR(6) NOT NULL DEFAULT '',
	SEQ_TRX_DATA VARCHAR(6) NOT NULL DEFAULT '',
	NUM_LOT_R_MED VARCHAR(6) NOT NULL DEFAULT '',
	SEQ_TRX_MED VARCHAR(6) NOT NULL DEFAULT '',
	MID_DATA VARCHAR(15) NOT NULL DEFAULT '',
	MID_MED VARCHAR(15) NOT NULL DEFAULT '',
	PRIMARY KEY (DES_CLAVE)
   )
   
   CREATE TABLE SYS_FRM_DT
   (	
    ID_SYS_FRM_DT int IDENTITY NOT NULL, 
    MT	VARCHAR(4),
	BM1 VARCHAR(64),
	BM2 VARCHAR(64),
	PRY_ACC_NBR VARCHAR(19),
	PRC_CD VARCHAR(6),
	TRX_AMNT VARCHAR(12),
	SYS_TRC_ADT_NBR VARCHAR(6),
	LCL_TRX_TM VARCHAR(6),
	LCL_TRX_DT VARCHAR(4),
	EXP_DT VARCHAR(4),
	POS_ENTRY_MD VARCHAR(4),
	NT_INT_ID VARCHAR(4),
	POS_CND_CD VARCHAR(2),
	TRCK_2 VARCHAR(38),
	RT_RF_NBR VARCHAR(12),
	AUT_NBR	VARCHAR(6),
	RSP_CD	VARCHAR(2),
	TRML_ID	VARCHAR(8),
	MRCHNT_ID VARCHAR(15),
	TRCK_1	VARCHAR(80),
	NRO_LO_ACT	VARCHAR(6),
	ADD_DT_105	VARCHAR(18),
	ADD_DT_112	VARCHAR(500),
	ADD_DT_114	VARCHAR(2),
	RSVD_NAT_USE	VARCHAR(8),
	ADD_DT_120	VARCHAR(700),
	ADD_DT_122	VARCHAR(700),
	RSVD_PRV_USE	VARCHAR(500),
	RSVD	VARCHAR(500),
	REG_DT	datetime,
	PRIMARY KEY (ID_SYS_FRM_DT)
   )