USE OPERAC_EC
GO

  CREATE TABLE OP_CODSUPER
   (	ID_CODSUPER int IDENTITY (1, 1) NOT NULL, 
	ID_OPERADOR int NOT NULL, 
	CODE128 VARCHAR(20), 
	CLAVE VARCHAR(8), 
	ESTADO int NULL, 
	IDREG int NULL, 
	FECHA_INI datetime DEFAULT SYSDATETIMEOFFSET(), 
	FECHA_FIN datetime,
	PRIMARY KEY (ID_CODSUPER)
   ) 

   CREATE UNIQUE INDEX OP_CODSUPER_PK ON OP_CODSUPER (ID_CODSUPER)
   
  CREATE TABLE OP_ENHSEC 
   (	
    ID_ENHSEC int IDENTITY (1, 1) NOT NULL, 
	DESCRIP_ES VARCHAR(200), 
	DESCRIP_EN VARCHAR(200), 
	PADD_NVL int NULL, 
	MNVL_DEP int NOT NULL DEFAULT 0, 
	PRIMARY KEY (ID_ENHSEC)
   )
   
  CREATE UNIQUE INDEX OP_ENHSEC_PK ON OP_ENHSEC (ID_ENHSEC)
  
  CREATE TABLE OP_INDICAT 
   (	
    ID_INDICAT int IDENTITY (1, 1) NOT NULL, 
	DESCRIP_ES VARCHAR(200), 
	DESCRIP_EN VARCHAR(200), 
	IDREG int NOT NULL DEFAULT 4, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(), 
	INDICAT int NULL, 
	RESERVADO int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_INDICAT)
   )
   
  CREATE UNIQUE INDEX OP_INDICAT_PK ON OP_INDICAT (ID_INDICAT)
   
  CREATE TABLE OP_INDICATOPC 
   (	
    ID_INDICATOPC int IDENTITY (1, 1) NOT NULL, 
	ID_INDICAT int NULL, 
	DESCRIP_ES VARCHAR(200), 
	DESCRIP_EN VARCHAR(200), 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(), 
	BITPOS int NULL, 
	RESERVADO int NOT NULL DEFAULT 0, 
	POSICION int NULL,
	PRIMARY KEY (ID_INDICATOPC)
   )
   
  CREATE UNIQUE INDEX OP_INDICATOPC_PK ON OP_INDICATOPC (ID_INDICATOPC) 
   
 
  CREATE TABLE OP_MODMDA
   (	ID_MODOPERA int NOT NULL, 
	ID_INDICAT int NOT NULL, 
	ID_INDICATOPC int NOT NULL, 
	VALUE int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_MODOPERA, ID_INDICAT, ID_INDICATOPC)
   ) 
   
    CREATE TABLE OP_MODNVA
   (	ID_MODOPERA int NOT NULL, 
	ID_NVLAUTO int NOT NULL, 
	VALUE VARCHAR(1) DEFAULT 'N',
	PRIMARY KEY (ID_MODOPERA,ID_NVLAUTO)
   ) 
   
    CREATE TABLE OP_MODOPERA
   (	ID_MODOPERA int NOT NULL, 
	DES_MODOPERA VARCHAR(200), 
	NVA_GRUPO int NULL, 
	NVA_USUARIO int NULL, 
	NIVEL_AUT int NULL, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(),
	EST_MODOPERA int NOT NULL DEFAULT 0,
	US_SUITE int NULL DEFAULT 0,
	PRIMARY KEY (ID_MODOPERA)
   )
   
   CREATE TABLE OP_MODUDF
   (	ID_MODOPERA int NOT NULL, 
	ID_NVLAUTO int NOT NULL, 
	VALUE VARCHAR(1) DEFAULT 'N',
	PRIMARY KEY (ID_MODOPERA,ID_NVLAUTO)
   )
  
  CREATE TABLE OP_NVLAUTO 
   (	
    ID_NVLAUTO int IDENTITY (1, 1) NOT NULL, 
	ID_ENHSEC int NULL,
	DESCRIP_ES VARCHAR(200), 
	DESCRIP_EN VARCHAR(200),
	POS_NVL int NULL,
	NVL_DEP int NOT NULL DEFAULT 0, 
	PRIMARY KEY (ID_NVLAUTO)
   )
   
  CREATE UNIQUE INDEX OP_NVLAUTO_PK ON OP_NVLAUTO (ID_NVLAUTO) 
   
  CREATE TABLE OP_OPERADOR 
   (	
    ID_OPERADOR int IDENTITY (1, 1) NOT NULL, 
	NOMBRE VARCHAR(200), 
	APELLIDO_M VARCHAR(200), 
	APELLIDO_P VARCHAR(200), 
	NOMB_ACE VARCHAR(20), 
	FECHA_NAC datetime, 
	STR_ESTADO int NULL, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(), 
	CC_OPERADOR int NULL, 
	REG_ESTADO int NOT NULL DEFAULT 0, 
	COD_NEGOCIO int NULL DEFAULT 0, 
	COD_NEGOCIO_ANT int NULL DEFAULT 0, 
	COD_TIENDA int NULL, 
	COD_TIENDA_ANT int NULL, 
	IP_TIENDA VARCHAR(15), 
	IP_TIENDA_ANT VARCHAR(15), 
	NVA_GRUPO int NOT NULL DEFAULT 3, 
	NVA_USUARIO int NOT NULL DEFAULT 1,
	NIVEL_AUT int NOT NULL DEFAULT 0,
	ID_MODOPERA int NOT NULL DEFAULT 0,
	INICIALES_OP VARCHAR(3),
	IND_SEG_MEJ int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_OPERADOR)
   )
   
  CREATE UNIQUE INDEX OP_OPERADOR_PK ON OP_OPERADOR (ID_OPERADOR) 
   
  CREATE TABLE OP_OPERAMDA 
   (	
    ID_OPERADOR int NOT NULL, 
	ID_INDICAT int NULL, 
	ID_INDICATOPC int NULL, 
	VALUE int NOT NULL DEFAULT 0, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
  CREATE TABLE OP_OPERAMOV 
   (	
    IDMOV int IDENTITY (1, 1) NOT NULL, 
	ID_OPERADOR int NULL, 
	STR_ESTADO int NULL, 
	REG_ESTADO int NULL, 
	CC_OPERADOR int NULL, 
	COD_NEGOCIO int NULL, 
	COD_TIENDA int NULL, 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET(), 
	HORA VARCHAR(8), 
	IP_CLIENTE VARCHAR(200),
	PRIMARY KEY (IDMOV)
   ) 
   
  CREATE UNIQUE INDEX OP_OPERAMOV_PK ON OP_OPERAMOV (IDMOV) 
   
  CREATE TABLE OP_OPERANVA 
   (	
    ID_OPERADOR int NOT NULL, 
	ID_NVLAUTO int NULL, 
	VALUE VARCHAR(1) DEFAULT 'N', 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
  ALTER TABLE OP_INDICATOPC ADD CONSTRAINT OP_INDICATOPC_FK1 FOREIGN KEY (ID_INDICAT) REFERENCES OP_INDICAT (ID_INDICAT)
  
  CREATE TABLE OP_OPERAUDF 
   (	
    ID_OPERADOR int NOT NULL, 
	ID_NVLAUTO int NULL, 
	VALUE VARCHAR(1) DEFAULT 'N', 
	IDREG int NULL, 
	FECHA datetime DEFAULT SYSDATETIMEOFFSET()
   )
   
    CREATE UNIQUE INDEX OP_OPERAUDF_PK ON OP_OPERAUDF (ID_OPERADOR) 
    
