USE RACE_EC
GO

  CREATE TABLE RA_NVL1 
   (	
    COD_NVL1 int IDENTITY (1, 1) NOT NULL, 
	DES_ES  VARCHAR(250), 
	DES_EN  VARCHAR(250), 
	COD_ACE int NOT NULL DEFAULT 0, 
	PRIMARY KEY (COD_NVL1)
   );
   
  CREATE UNIQUE INDEX RA_NVL1_PK ON RA_NVL1 (COD_NVL1);
  
  CREATE TABLE RA_NVL2 
   (	
    COD_NVL2 int IDENTITY (1, 1) NOT NULL, 
	COD_NVL1 int NULL,
    DES_ES  VARCHAR(250), 
	DES_EN  VARCHAR(250), 
	COD_ACE int NOT NULL DEFAULT 0, 
	DES_ACE  VARCHAR(250), 
	ACTIVO int NOT NULL DEFAULT 0, 
	PRIMARY KEY (COD_NVL2)
   );
   
  CREATE UNIQUE INDEX RA_NVL2_PK ON RA_NVL2 (COD_NVL2);
   
  CREATE TABLE RA_PRMT 
   (	
    COD_PRMT int IDENTITY (1, 1) NOT NULL, 
	COD_NVL2 int NULL, 
	DES_PRMT  VARCHAR(250), 
	PRIMARY KEY (COD_PRMT)
   );
   
  CREATE UNIQUE INDEX RA_PRMT_PK ON RA_PRMT (COD_PRMT);
  