  USE TDVAL_EC
  GO

CREATE TABLE [dbo].[BDV_VAL](
	[ID_BDVAL] [int] IDENTITY(1,1) NOT NULL,
	[ESTADO] [int] NOT NULL DEFAULT ((0)),
	[FECHA] [datetime] NULL DEFAULT (sysdatetimeoffset()),
	[IDREG] [int] NULL,
	[ID_BSN_UN] [int] NULL,
	[ID_TRN_EOD] [int] NULL,
	TY_DEP	char(2),
	ID_CTAB int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID_BDVAL)
   )
   
  CREATE UNIQUE INDEX BDVAL_PK ON BDV_VAL (ID_BDVAL) 
   
  CREATE TABLE BDV_RET 
   (	
    ID_BDVAL int NOT NULL, 
	ID_TRN int NOT NULL, 
	[MO_RET] [int] NULL,
	PRIMARY KEY (ID_BDVAL, ID_TRN)
   )
   
  CREATE UNIQUE INDEX BDV_RET_PK ON BDV_RET (ID_BDVAL, ID_TRN)
  
  ALTER TABLE BDV_RET ADD CONSTRAINT BDV_RET_FK1 FOREIGN KEY (ID_BDVAL) REFERENCES BDV_VAL (ID_BDVAL)
  
  CREATE TABLE [dbo].[DEP_TCKSYF](
	[ID_DEP] [int] NOT NULL,
	[MO_SYF] [int] NOT NULL,
	[TY_SYF] [int] NOT NULL
  )
  
  CREATE TABLE [dbo].[DEP_TCKTND](
	[ID_DEP] [int] NOT NULL,
	[ID_TND] [int] NOT NULL,
	[ID_VAR_TND] [int] NOT NULL,
	[MO_DEV_TND] [int] NOT NULL
  )
  
  CREATE TABLE [dbo].[DEP_TICKET](
	[ID_DEP] [int] IDENTITY(1,1) NOT NULL,
	[ID_TRN] [int] NOT NULL,
	[TY_DEP] [int] NOT NULL DEFAULT 0,
	[ID_BSN_DEP] [int] NOT NULL DEFAULT 0,
	[ID_BNC_DEP] [int] NOT NULL DEFAULT 0,
	[ID_BAG] [int] NOT NULL DEFAULT 0,
	[DE_DEP] [varchar](200) NULL,
	[MO_DEP] [int] NOT NULL DEFAULT 0,
	[ID_ESTADO] [int] NOT NULL DEFAULT 0,
	[ID_REG] [int] NOT NULL DEFAULT 0,
	[TS_DEP] [datetime] NOT NULL DEFAULT sysdatetimeoffset()
   );